name: llm_env

channels:
  - conda-forge

dependencies:
  # Python packages
  - python 
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - jupyter
  - python-dotenv
  - tiktoken
  - nltk
  - openai
  - pandas_market_calendars
  - tqdm
  - kagglehub

  # R packages
  - r-base 
  - r-ggplot2
  - r-dplyr 
  - r-sandwich 
  - r-lmtest 
  - r-furrr 
  - r-Matrix
  - r-logger
  - r-latex2exp
  - r-lemon
  - r-kableExtra
  - r-viridis
  - r-tidyverse
  - r-tidyr
  - r-stargazer
  - r-fixest
  - r-modelsummary
  - r-glue
  - r-viridis
  - r-purrr
  # - r-extrafont

