---
title: "Results for Regressions with LHS Proxy"
header-includes:
  - \usepackage{amsmath}
  - \usepackage[capposition=top]{floatrow}
  - \usepackage{caption}
output:
  pdf_document: 
    fig_caption: true
    fig_crop: false
date: "Sep 24, 2024"
editor_options: 
  chunk_output_type: console
---

```{r, warning=FALSE, message=FALSE, echo=FALSE}
repo_dir <- "~/Documents/LanguageModel_Labels/congressional_bills"
knitr::opts_knit$set(root.dir = repo_dir)

data_dir <- file.path(repo_dir, "Data/Estimation/LHS") 
fig_dir <- file.path(repo_dir, "Figures/Estimation/LHS")
dir.create(fig_dir, showWarnings=FALSE, recursive = TRUE)

knitr_default_plot <- knitr::knit_hooks$get("plot")  
knitr::knit_hooks$set(plot = function(x, options) {  
  x <- knitr_default_plot(x, options) 
  if(!is.null(options$fig.note)) {  
    x  <- gsub(
      "\\end{figure}", 
      sprintf("\\floatfoot*{Note: %s}\\end{figure}", options$fig.note), 
      x, fixed=T)  
  }
  return(x)
})


knitr::opts_chunk$set(
   # tidy = TRUE, tidy.opts = list(comment = FALSE)
  warning=FALSE,
  message=FALSE,
  echo = FALSE,
  dpi=300,
  out.height = "\\textheight",
  out.width = "\\textwidth",
  out.extra = "keepaspectratio=true"
)

require(dplyr)
require(ggplot2)
require(latex2exp)
require(kableExtra)
require(extrafont)
require(lemon)
source(file.path(repo_dir, "Code/ggplot_theme.r"))
source(file.path(repo_dir, "Code/Estimation/3.3.1_lhs_figures.r"))
source(file.path(repo_dir, "Code/Estimation/3.3.2_lhs_tables.r"))

stripe <- function(nstriped=3, nrow=50){
  start_row <- rep(seq(0, (2*nstriped)*nrow, by=2*nstriped), each=nstriped)
  return(start_row + rep(1:nstriped, times=length(start_row)/nstriped))
}
```


```{r, fig.height=5.5, fig.width=9, fig.cap="$\\beta$ vs. Prompt. Proxy on the LHS.", fig.align="center", fig.note="The coefficients were obtained by fitting the model $Y_t = \\alpha + \\beta V$ using 10,000 bills, with 95\\% confidence intervals computed via robust standard errors. Here, $Y_t$ are indicator for topic $t \\in$ \\{Health; Banking, Finance, and Domestic Commerce; Defense; Government Operations; Public Lands and Water Management; Other\\} and $V \\in \\{\\text{Democrat}; \\text{Senate}; \\text{DW1}\\}$ are the covariates. The human-based coefficients $\\beta^\\star$ (red) were estimated using $Y_{t}^\\text{Human} := 1\\{Y^\\text{Human} = t\\}$, while LLM-based coefficients $\\beta^\\text{LLM}$ (GPT-3.5 in green circles, GPT-4o in blue triangles) used $Y_{t,m,p}^\\text{LLM} := 1\\{Y_{m,p}^\\text{LLM} = t\\}$, with $m \\in \\{\\text{GPT-3.5}, \\text{GPT-4o}\\}$ denoting the LLM model and $p \\in \\{1, \\ldots, 12\\}$ representing the prompt. In each subplot, the bias estimates were sorted in ascending order for clarity."}
fig01
```

```{r, fig.height=5.5, fig.width=9, fig.cap="t-scores of $\\beta$ vs. Prompt. Proxy on the LHS.", fig.align="center", fig.note="The t-scores were obtained by fitting the model $Y_t = \\alpha + \\beta V$ using 10,000 bills, with 95\\% confidence intervals computed via robust standard errors. Here, $Y_t$ are indicator for topic $t \\in$ \\{Health; Banking, Finance, and Domestic Commerce; Defense; Government Operations; Public Lands and Water Management; Other\\} and $V \\in \\{\\text{Democrat}; \\text{Senate}; \\text{DW1}\\}$ are the covariates. The human-based coefficients $\\beta^\\star$ (red) were estimated using $Y_{t}^\\text{Human} := 1\\{Y^\\text{Human} = t\\}$, while LLM-based coefficients $\\beta^\\text{LLM}$ (GPT-3.5 in green circles, GPT-4o in blue triangles) used $Y_{t,m,p}^\\text{LLM} := 1\\{Y_{m,p}^\\text{LLM} = t\\}$, with $m \\in \\{\\text{GPT-3.5}, \\text{GPT-4o}\\}$ denoting the LLM model and $p \\in \\{1, \\ldots, 12\\}$ representing the prompt. In each subplot, the t-score estimates were sorted in ascending order for clarity."}
fig02
```

\clearpage


```{r, fig.height=3.5, fig.width=4, fig.cap="Bias Density of $\\beta^\\text{LLM}$. Proxy on the LHS.", fig.align="center", fig.note="The bias estimates were calculated as the difference between the LLM-based coefficient $\\beta^\\text{LLM}$ and the human-based coefficient $\\beta^\\star$, using a regression of the form $Y_t = \\alpha + \\beta V$, where $t \\in$ \\{Health; Banking, Finance, and Domestic Commerce; Defense; Government Operations; Public Lands and Water Management; Other\\} represents major topics and $V \\in \\{\\text{Democrat}; \\text{Senate}; \\text{DW1}\\}$ are the covariates. For $\\beta^\\star$, $Y_t^\\text{Human} := 1\\{Y^\\text{Human} = t\\}$, while for $\\beta^\\text{LLM}$, $Y_{t,m,p}^\\text{LLM} := 1\\{Y_{m,p}^\\text{LLM} = t\\}$, with $m \\in \\{\\text{GPT-3.5}, \\text{GPT-4o}\\}$ denoting the LLM model and $p \\in \\{1, \\ldots, 12\\}$ representing the prompt. The human-based coefficient $\\beta^\\star$ was computed using the full 10,000 bills, whereas the LLM-based coefficient $\\beta^\\text{LLM}$ was calculated as the average of $N = 1,000$ simulation runs, with each run’s estimate based on a sample of 5,000 bills. These bias estimates are independent of the validation proportion $\\eta$, though they were generated in the experiment run with $\\eta = 5\\%$."}
fig03
```



```{r, fig.height=3.5, fig.width=4, fig.cap="Normalized Bias Density of $\\beta^\\text{LLM}$. Proxy on the LHS.", fig.align="center", fig.note="The normalized bias estimates were calculated as the difference between the LLM-based coefficient $\\beta^\\text{LLM}$ and the human-based coefficient $\\beta^\\star$, divided by the sample standard deviation computed across $N=1000$ samples. All other variables are as defined in the previous figure. These bias estimates are independent of the validation proportion $\\eta$, though they were generated in the experiment run with $\\eta = 5\\%$"}
fig04
```


\clearpage

```{r, fig.height=4.5, fig.width=9, fig.cap="Bias Density of $\\beta$ by Model and Proportion of Validation Samples. Proxy on the LHS.", fig.align="center"}
fig05
```

```{r, fig.height=4.5, fig.width=9, fig.cap="Normalized Bias Density of $\\beta$ by Model and Proportion of Validation Samples. Proxy on the LHS.", fig.align="center"}
fig06
```

\clearpage

```{r, fig.height=3, fig.width=9, fig.cap="MSE Empirical CDF of $\\beta$ by Proportion of Validation Samples. Proxy on the LHS.", fig.align="center"}
fig07
```

```{r, fig.height=4.5, fig.width=9, fig.cap="MSE Empirical CDF of $\\beta$ by Model and Proportion of Validation Samples. Proxy on the LHS.", fig.align="center"}
fig08
```

\clearpage

```{r, results='asis'}
kable_styling(tab01, latex_options = "striped", stripe_index = stripe(3))
kable_styling(tab02, latex_options = "striped", stripe_index = stripe(3))
kable_styling(tab03, latex_options = "striped", stripe_index = stripe(3))
kable_styling(tab04, latex_options = "striped", stripe_index = stripe(3))
kable_styling(tab05, latex_options = "striped", stripe_index = stripe(3))
kable_styling(tab06, latex_options = "striped", stripe_index = stripe(3))
kable_styling(tab07, latex_options = "striped", stripe_index = stripe(3))
kable_styling(tab08, latex_options = "striped", stripe_index = stripe(3))
```
