---
title: "Results for Regressions with RHS Proxy"
header-includes:
  - \usepackage{amsmath}
  - \usepackage[capposition=top]{floatrow}
  - \usepackage{caption}
output:
  pdf_document: 
    fig_caption: true
    fig_crop: false
date: "Sep 24, 2024"
editor_options: 
  chunk_output_type: console
---

```{r, warning=FALSE, message=FALSE, echo=FALSE}
repo_dir <- "~/Documents/LanguageModel_Labels/congressional_bills"
knitr::opts_knit$set(root.dir = repo_dir)

data_dir <- file.path(repo_dir, "Data/Estimation/RHS") 
fig_dir <- file.path(repo_dir, "Figures/Estimation/RHS")
dir.create(fig_dir, showWarnings=FALSE, recursive = TRUE)

knitr_default_plot <- knitr::knit_hooks$get("plot")  
knitr::knit_hooks$set(plot = function(x, options) {  
  x <- knitr_default_plot(x, options) 
  if(!is.null(options$fig.note)) {  
    x  <- gsub(
      "\\end{figure}", 
      sprintf("\\floatfoot*{Note: %s}\\end{figure}", options$fig.note), 
      x, fixed=T)  
  }
  return(x)
})


knitr::opts_chunk$set(
   # tidy = TRUE, tidy.opts = list(comment = FALSE)
  warning=FALSE,
  message=FALSE,
  echo = FALSE,
  dpi=300,
  out.height = "\\textheight",
  out.width = "\\textwidth",
  out.extra = "keepaspectratio=true"
)

require(dplyr)
require(ggplot2)
require(latex2exp)
require(kableExtra)
require(extrafont)
require(lemon)
source(file.path(repo_dir, "Code/ggplot_theme.r"))
source(file.path(repo_dir, "Code/Estimation/3.4.1_rhs_figures.r"))
# source(file.path(repo_dir, "Code/Estimation/3.4.2_rhs_tables.r"))

stripe <- function(nstriped=3, nrow=50){
  start_row <- rep(seq(0, (2*nstriped)*nrow, by=2*nstriped), each=nstriped)
  return(start_row + rep(1:nstriped, times=length(start_row)/nstriped))
}
```


```{r fig01_coef, fig.height=5.5, fig.width=9, fig.cap="$\\beta_t$  vs. Prompt for all $t$. Proxy on the RHS.", fig.align="center", fig.note="The coefficients were obtained by fitting the model $V = Y^\\top\\beta = \\sum_{t} Y_t \\beta_t$ using 10,000 bills, with 95\\% confidence intervals computed via robust standard errors. Here,  $V \\in \\{\\text{Democrat}; \\text{Senate}; \\text{DW1}\\}$ and $t \\in$ \\{Health; Banking, Finance, and Domestic Commerce; Defense; Government Operations; Public Lands and Water Management; Other\\}. The human-based coefficients $\\beta^\\star$ (red) were estimated using $Y_t^\\text{Human} := 1\\{Y^\\text{Human} = t\\}$, while LLM-based coefficients $\\beta^\\text{LLM}$ (GPT-3.5 in green circles, GPT-4o in blue triangles) used $Y_{t,m,p}^\\text{LLM} := 1\\{Y_{m,p}^\\text{LLM} = t\\}$, with $m \\in \\{\\text{GPT-3.5}, \\text{GPT-4o}\\}$ denoting the LLM model and $p \\in \\{1, \\ldots, 12\\}$ representing the prompt. In each subplot, the bias estimates were sorted in ascending order for clarity."}
fig01
```

```{r fig02_tscore, fig.height=5.5, fig.width=9, fig.cap="t-scores of each $\\beta_t$ vs. Prompt for all $t$. Proxy on the RHS.", fig.align="center", fig.note="The t-scores were obtained by fitting the model $V = Y^\\top\\beta = \\sum_{t} Y_t \\beta_t$ using 10,000 bills, with 95\\% confidence intervals computed via robust standard errors. Here, $V \\in \\{\\text{Democrat}; \\text{Senate}; \\text{DW1}\\}$ and $t \\in$ \\{Health; Banking, Finance, and Domestic Commerce; Defense; Government Operations; Public Lands and Water Management; Other\\}. The human-based coefficients $\\beta^\\star$ (red) were estimated using $Y_t^\\text{Human} := 1\\{Y^\\text{Human} = t\\}$, while LLM-based coefficients $\\beta^\\text{LLM}$ (GPT-3.5 in green circles, GPT-4o in blue triangles) used $Y_{t,m,p}^\\text{LLM} := 1\\{Y_{m,p}^\\text{LLM} = t\\}$, with $m \\in \\{\\text{GPT-3.5}, \\text{GPT-4o}\\}$ denoting the LLM model and $p \\in \\{1, \\ldots, 12\\}$ representing the prompt. In each subplot, the t-score estimates were sorted in ascending order for clarity."}
fig02
```


\clearpage

```{r fig03_bias1_llm, fig.height=2.3, fig.width=9, fig.cap="Bias Density of $\\beta_t^\\text{LLM}$ for all $t$. Proxy on the RHS.", fig.align="center", fig.note="The bias estimates were calculated as the difference between the LLM-based coefficient $\\beta_t^\\text{LLM}$ and the human-based coefficient $\\beta_t^\\star$, using a regression of the form $V = Y^\\top\\beta = \\sum_{t} Y_t \\beta_t$, where $V \\in \\{\\text{Democrat}; \\text{Senate}; \\text{DW1}\\}$ and $t \\in$ \\{Health; Banking, Finance, and Domestic Commerce; Defense; Government Operations; Public Lands and Water Management; Other\\}. For human-based coefficients, the covariates are $Y_t^\\text{Human} := 1\\{Y^\\text{Human} = t\\}$, while for LLM-based coefficients, the covariates are $Y_{t,m,p}^\\text{LLM} := 1\\{Y_{m,p}^\\text{LLM} = t\\}$, with $m \\in \\{\\text{GPT-3.5}, \\text{GPT-4o}\\}$ denoting the LLM model and $p \\in \\{1, \\ldots, 12\\}$ representing the prompt. The human-based coefficient $\\beta_t^\\star$ was computed using the full 10,000 bills, whereas the LLM-based coefficient $\\beta_t^\\text{LLM}$ was calculated as the average of $N = 1,000$ simulation runs, with each run’s estimate based on a sample of 5,000 bills. The bias estimates are independent of the validation proportion $\\eta$, though they were generated in the experiment run with $\\eta = 5\\%$."}
fig03
```


```{r fig04_bias1_norm_llm, fig.height=2.3, fig.width=9, fig.cap="Normalized Bias Density of $\\beta_t^\\text{LLM}$ for all $t$. Proxy on the RHS.", fig.align="center", fig.note="The normalized bias estimates were calculated as the difference between the LLM-based coefficient $\\beta_t^\\text{LLM}$ and the human-based coefficient $\\beta_t^\\star$, divided by the coefficient's sample standard deviation computed across $N=1000$ samples. All other variables are as defined in the previous figure. The bias estimates are independent of the validation proportion $\\eta$, though they were generated in the experiment run with $\\eta = 5\\%$."}
fig04
```


\clearpage

```{r fig05_bias2, fig.height=7, fig.width=9, fig.cap="Bias Density of $\\beta_{t}$, for all $t$, by Model and Proportion of Validation Samples. Proxy on the RHS.", fig.align="center"}
fig05
```

\clearpage 

```{r fig06_bias2_norm, fig.height=7, fig.width=9, fig.cap="Normalized Bias Density of $\\beta_{t}$, for all $t$, by Model and Proportion of Validation Samples. Proxy on the RHS.", fig.align="center"}
fig06
```

\clearpage

```{r fig07_mse1, fig.height=7, fig.width=9, fig.cap="MSE Empirical CDF of $\\beta_t$ for all $t$ by Proportion of Validation Samples. Proxy on the RHS.", fig.align="center"}
fig07
```

```{r fig08_mse2, fig.height=7, fig.width=9, fig.cap="MSE Empirical CDF of $\\beta_{t}$, for all $t$, by Model and Proportion of Validation Samples. Proxy on the RHS.", fig.align="center"}
fig08
```


<!-- \clearpage -->

<!-- ```{r tab_data} -->
<!-- regression.levels <- c("5k_V_Yllm", "train_V_Yhuman", "Vtilde_Ytilde") -->
<!-- regression.labels <- c("LLM", "Human Validation", "Debiased") -->

<!-- model.levels <- c("gpt-3.5-turbo-0125", "gpt-4o-2024-05-13") -->
<!-- model.labels <- c("GPT-3.5", "GPT-4o") -->

<!-- proportion.levels <- c(0.05, 0.10, 0.25, 0.50) -->
<!-- proportion.labels <- sprintf("%s\\%%", proportion.levels*100) -->

<!-- regressions.averaged <- read.csv(file.path(data_dir, "rhs_5k_llm_human_debiased_averaged.csv")) %>% -->
<!--   rename(proportion=train_proportion) %>% -->
<!--    mutate( -->
<!--      bias_norm = bias_mean/coef_sd,  -->
<!--      Y = coef_name, -->
<!--      V = factor(V, levels=V.levels), -->
<!--      model = factor(model, levels=model.levels, labels=model.labels), -->
<!--      regression = factor(regression, levels=regression.levels, labels=regression.labels), -->
<!--      proportion = factor(proportion, levels=proportion.levels, labels=proportion.labels), -->
<!--      ) %>% -->
<!--   filter(Y!="Other") -->

<!-- alpha <- 0.10 -->
<!-- probs <- c(alpha/2, 1-alpha/2) -->

<!-- stripe <- function(nstriped=3, nrow=50){ -->
<!--   start_row <- rep(seq(0, (2*nstriped)*nrow, by=2*nstriped), each=nstriped) -->
<!--   return(start_row + rep(1:nstriped, times=length(start_row)/nstriped)) -->
<!-- } -->


<!-- ``` -->

<!-- ```{r tab_bias1, results='asis'} -->
<!-- bias1 <- regressions.averaged %>% -->
<!--   mutate(statistic=bias_mean) %>% -->
<!--   group_by(Y, proportion, regression) %>% -->
<!--   summarise( -->
<!--     "Mean" = mean(statistic), -->
<!--     "SD" = sd(statistic), -->
<!--     "Median" = median(statistic), -->
<!--     "5\\%" = quantile(statistic, probs[1]), -->
<!--     "95\\%" = quantile(statistic, probs[2]), -->
<!--     .groups = "drop" -->
<!--     ) %>% -->
<!--   rename(c( -->
<!--     "Validation Proportion" = proportion,  -->
<!--     "Bias" = regression) -->
<!--     ) -->
<!-- ``` -->

<!-- ```{r tab_bias1_3, results='asis'} -->
<!-- bias1 %>%  -->
<!--   filter(Y=="3") %>% select(!Y) %>% -->
<!--   kbl(., align="rlrrrrr", -->
<!--       caption="Bias Summary Statistics of $\\beta_{t}$, $t=$Health, by Proportion of Validation Samples. -->
<!--       Proxy on the RHS: $V = Y^\\top \\beta = \\sum_{t} Y_t \\beta_t$", -->
<!--       digits=3, booktabs=T, linesep = "", escape=F) %>% -->
<!--     kable_styling(latex_options = "striped", stripe_index = stripe(3)) -->
<!-- ``` -->

<!-- ```{r tab_bias1_14, results='asis'} -->
<!-- bias1 %>%  -->
<!--   filter(Y=="14") %>% select(!Y) %>% -->
<!--   kbl(., align="rlrrrrr", -->
<!--       caption="Bias Summary Statistics of $\\beta_{t}$, $t=$Banking, Finance, and Domestic Commerce, by Proportion of Validation Samples. -->
<!--       Proxy on the RHS: $V = Y^\\top \\beta = \\sum_{t} Y_t \\beta_t$", -->
<!--       digits=3, booktabs=T, linesep = "", escape=F) %>% -->
<!--     kable_styling(latex_options = "striped", stripe_index = stripe(3)) -->
<!-- ``` -->

<!-- ```{r tab_bias1_15, results='asis'} -->
<!-- bias1 %>%  -->
<!--   filter(Y=="15") %>% select(!Y) %>% -->
<!--   kbl(., align="rlrrrrr", -->
<!--       caption="Bias Summary Statistics of $\\beta_{t}$, $t=$Defense, by Proportion of Validation Samples. -->
<!--       Proxy on the RHS: $V = Y^\\top \\beta = \\sum_{t} Y_t \\beta_t$", -->
<!--       digits=3, booktabs=T, linesep = "", escape=F) %>% -->
<!--     kable_styling(latex_options = "striped", stripe_index = stripe(3)) -->
<!-- ``` -->

<!-- ```{r tab_bias1_19, results='asis'} -->
<!-- bias1 %>%  -->
<!--   filter(Y=="19") %>% select(!Y) %>% -->
<!--   kbl(., align="rlrrrrr", -->
<!--       caption="Bias Summary Statistics of $\\beta_{t}$, $t=$Government Operations, by Proportion of Validation Samples. -->
<!--       Proxy on the RHS: $V = Y^\\top \\beta = \\sum_{t} Y_t \\beta_t$", -->
<!--       digits=3, booktabs=T, linesep = "", escape=F) %>% -->
<!--     kable_styling(latex_options = "striped", stripe_index = stripe(3)) -->
<!-- ``` -->

<!-- ```{r tab_bias1_20, results='asis'} -->
<!-- bias1 %>%  -->
<!--   filter(Y=="20") %>% select(!Y) %>% -->
<!--   kbl(., align="rlrrrrr", -->
<!--       caption="Bias Summary Statistics of $\\beta_{t}$, $t=$Public Lands and Water Management, by Proportion of Validation Samples. -->
<!--       Proxy on the RHS: $V = Y^\\top \\beta = \\sum_{t} Y_t \\beta_t$", -->
<!--       digits=3, booktabs=T, linesep = "", escape=F) %>% -->
<!--     kable_styling(latex_options = "striped", stripe_index = stripe(3)) -->

<!-- ``` -->


<!-- ```{r tab_bias1_norm, results='asis'} -->
<!-- bias1_norm <- regressions.averaged %>% -->
<!--   mutate(statistic=bias_norm) %>% -->
<!--   group_by(Y, proportion, regression) %>% -->
<!--   summarise( -->
<!--     "Mean" = mean(statistic), -->
<!--     "SD" = sd(statistic), -->
<!--     "Median" = median(statistic), -->
<!--     "5\\%" = quantile(statistic, probs[1]), -->
<!--     "95\\%" = quantile(statistic, probs[2]), -->
<!--     .groups = "drop" -->
<!--     ) %>% -->
<!--   rename(c( -->
<!--     "Validation Proportion" = proportion,  -->
<!--     "Normalized Bias" = regression) -->
<!--     ) -->
<!-- ``` -->

<!-- ```{r tab_bias1_norm_3, results='asis'} -->
<!-- bias1_norm %>%  -->
<!--   filter(Y=="3") %>% select(!Y) %>% -->
<!--   kbl(., align="rlrrrrr", -->
<!--     caption="Normalized Bias Summary Statistics of $\\beta_{t}$, $t=$Health, by Proportion of Validation Samples. -->
<!--       Proxy on the RHS: $V = Y^\\top \\beta = \\sum_{t} Y_t \\beta_t$", -->
<!--     digits=3, booktabs=T, linesep = "", escape=F) %>% -->
<!--   kable_styling(latex_options = "striped", stripe_index = stripe(3)) -->
<!-- ``` -->

<!-- ```{r tab_bias1_norm_14, results='asis'} -->
<!-- bias1_norm %>%  -->
<!--   filter(Y=="14") %>% select(!Y) %>% -->
<!--   kbl(., align="rlrrrrr", -->
<!--     caption="Normalized Bias Summary Statistics of $\\beta_{t}$, $t=$Banking, Finance, and Domestic Commerce, by Proportion of Validation Samples. -->
<!--       Proxy on the RHS: $V = Y^\\top \\beta = \\sum_{t} Y_t \\beta_t$", -->
<!--     digits=3, booktabs=T, linesep = "", escape=F) %>% -->
<!--   kable_styling(latex_options = "striped", stripe_index = stripe(3)) -->
<!-- ``` -->

<!-- ```{r tab_bias1_norm_15, results='asis'} -->
<!-- bias1_norm %>%  -->
<!--   filter(Y=="15") %>% select(!Y) %>% -->
<!--   kbl(., align="rlrrrrr", -->
<!--     caption="Normalized Bias Summary Statistics of $\\beta_{t}$, $t=$Defense, by Proportion of Validation Samples. -->
<!--       Proxy on the RHS: $V = Y^\\top \\beta = \\sum_{t} Y_t \\beta_t$", -->
<!--     digits=3, booktabs=T, linesep = "", escape=F) %>% -->
<!--   kable_styling(latex_options = "striped", stripe_index = stripe(3)) -->
<!-- ``` -->

<!-- ```{r tab_bias1_norm_19, results='asis'} -->
<!-- bias1_norm %>%  -->
<!--   filter(Y=="19") %>% select(!Y) %>% -->
<!--   kbl(., align="rlrrrrr", -->
<!--     caption="Normalized Bias Summary Statistics of $\\beta_{t}$, $t=$Government Operations, by Proportion of Validation Samples. -->
<!--       Proxy on the RHS: $V = Y^\\top \\beta = \\sum_{t} Y_t \\beta_t$", -->
<!--     digits=3, booktabs=T, linesep = "", escape=F) %>% -->
<!--   kable_styling(latex_options = "striped", stripe_index = stripe(3)) -->
<!-- ``` -->

<!-- ```{r tab_bias1_norm_20, results='asis'} -->
<!-- bias1_norm %>%  -->
<!--   filter(Y=="20") %>% select(!Y) %>% -->
<!--   kbl(., align="rlrrrrr", -->
<!--     caption="Normalized Bias Summary Statistics of $\\beta_{t}$, $t=$Public Lands and Water Management, by Proportion of Validation Samples. -->
<!--       Proxy on the RHS: $V = Y^\\top \\beta = \\sum_{t} Y_t \\beta_t$", -->
<!--     digits=3, booktabs=T, linesep = "", escape=F) %>% -->
<!--   kable_styling(latex_options = "striped", stripe_index = stripe(3)) -->
<!-- ``` -->



<!-- ```{r tab_bias2, results='asis'} -->
<!-- bias2 <- regressions.averaged %>% -->
<!--   mutate(statistic=bias_mean) %>% -->
<!--   group_by(Y, model, proportion, regression) %>% -->
<!--   summarise( -->
<!--     "Mean" = mean(statistic), -->
<!--     "SD" = sd(statistic), -->
<!--     "Median" = median(statistic), -->
<!--     "5\\%" = quantile(statistic, probs[1]), -->
<!--     "95\\%" = quantile(statistic, probs[2]), -->
<!--     .groups = "drop" -->
<!--     ) %>% -->
<!--   rename(c( -->
<!--     "Model" = model,  -->
<!--     "Validation Proportion" = proportion,  -->
<!--     "Bias" = regression -->
<!--     )) -->
<!-- ``` -->

<!-- ```{r tab_bias2_3, results='asis'} -->
<!-- bias2 %>%  -->
<!--   filter(Y=="3") %>% select(!Y) %>% -->
<!--   kbl(., align="lrlrrrrr", -->
<!--     caption="Bias Summary Statistics of $\\beta_{t}$, $t=$Health, by Model and Proportion of Validation Samples. -->
<!--       Proxy on the RHS: $V = Y^\\top \\beta = \\sum_{t} Y_t \\beta_t$", -->
<!--     digits=3, booktabs=T, linesep = "", escape=F) %>% -->
<!--   kable_styling(latex_options = "striped", stripe_index = stripe(3)) -->
<!-- ``` -->

<!-- ```{r tab_bias2_14, results='asis'} -->
<!-- bias2 %>%  -->
<!--   filter(Y=="14") %>% select(!Y) %>% -->
<!--   kbl(., align="lrlrrrrr", -->
<!--     caption="Bias Summary Statistics of $\\beta_{t}$, $t=$Banking, Finance, and Domestic Commerce, by Model and Proportion of Validation Samples. -->
<!--       Proxy on the RHS: $V = Y^\\top \\beta = \\sum_{t} Y_t \\beta_t$", -->
<!--     digits=3, booktabs=T, linesep = "", escape=F) %>% -->
<!--   kable_styling(latex_options = "striped", stripe_index = stripe(3)) -->
<!-- ``` -->

<!-- ```{r tab_bias2_15, results='asis'} -->
<!-- bias2 %>%  -->
<!--   filter(Y=="15") %>% select(!Y) %>% -->
<!--   kbl(., align="lrlrrrrr", -->
<!--     caption="Bias Summary Statistics of $\\beta_{t}$, $t=$Defense, by Model and Proportion of Validation Samples. -->
<!--       Proxy on the RHS: $V = Y^\\top \\beta = \\sum_{t} Y_t \\beta_t$", -->
<!--     digits=3, booktabs=T, linesep = "", escape=F) %>% -->
<!--   kable_styling(latex_options = "striped", stripe_index = stripe(3)) -->
<!-- ``` -->

<!-- ```{r tab_bias2_19, results='asis'} -->
<!-- bias2 %>%  -->
<!--   filter(Y=="19") %>% select(!Y) %>% -->
<!--   kbl(., align="lrlrrrrr", -->
<!--     caption="Bias Summary Statistics of $\\beta_{t}$, $t=$Government Operations, by Model and Proportion of Validation Samples. -->
<!--       Proxy on the RHS: $V = Y^\\top \\beta = \\sum_{t} Y_t \\beta_t$", -->
<!--     digits=3, booktabs=T, linesep = "", escape=F) %>% -->
<!--   kable_styling(latex_options = "striped", stripe_index = stripe(3)) -->
<!-- ``` -->

<!-- ```{r tab_bias2_20, results='asis'} -->
<!-- bias2 %>%  -->
<!--   filter(Y=="20") %>% select(!Y) %>% -->
<!--   kbl(., align="lrlrrrrr", -->
<!--     caption="Bias Summary Statistics of $\\beta_{t}$, $t=$Public Lands and Water Management, by Model and Proportion of Validation Samples. -->
<!--       Proxy on the RHS: $V = Y^\\top \\beta = \\sum_{t} Y_t \\beta_t$", -->
<!--     digits=3, booktabs=T, linesep = "", escape=F) %>% -->
<!--   kable_styling(latex_options = "striped", stripe_index = stripe(3)) -->
<!-- ``` -->


<!-- ```{r tab_bias2_norm, results='asis'} -->
<!-- bias2_norm <- regressions.averaged %>% -->
<!--   mutate(statistic=bias_norm) %>% -->
<!--   group_by(Y, model, proportion, regression) %>% -->
<!--   summarise( -->
<!--     "Mean" = mean(statistic), -->
<!--     "SD" = sd(statistic), -->
<!--     "Median" = median(statistic), -->
<!--     "5\\%" = quantile(statistic, probs[1]), -->
<!--     "95\\%" = quantile(statistic, probs[2]), -->
<!--     .groups = "drop" -->
<!--     ) %>% -->
<!--   rename(c( -->
<!--     "Model" = model,  -->
<!--     "Validation Proportion" = proportion,  -->
<!--     "Normalized Bias" = regression -->
<!--     )) -->
<!-- ``` -->

<!-- ```{r tab_bias2_norm_3, results='asis'} -->
<!-- bias2_norm %>%  -->
<!--   filter(Y=="3") %>% select(!Y) %>% -->
<!--   kbl(., align="lrlrrrrr", -->
<!--     caption="Normalized Bias Summary of $\\beta_{t}$, $t=$Health, Statistics by Model and Proportion of Validation Samples. -->
<!--       Proxy on the RHS: $V = Y^\\top \\beta = \\sum_{t} Y_t \\beta_t$", -->
<!--     digits=3, booktabs=T, linesep = "", escape=F) %>% -->
<!--   kable_styling(latex_options = "striped", stripe_index = stripe(3)) -->
<!-- ``` -->

<!-- ```{r tab_bias2_norm_14, results='asis'} -->
<!-- bias2_norm %>%  -->
<!--   filter(Y=="14") %>% select(!Y) %>% -->
<!--   kbl(., align="lrlrrrrr", -->
<!--     caption="Normalized Bias Summary Statistics of $\\beta_{t}$, $t=$Banking, Finance, and Domestic Commerce, by Model and Proportion of Validation Samples. -->
<!--       Proxy on the RHS: $V = Y^\\top \\beta = \\sum_{t} Y_t \\beta_t$", -->
<!--     digits=3, booktabs=T, linesep = "", escape=F) %>% -->
<!--   kable_styling(latex_options = "striped", stripe_index = stripe(3)) -->
<!-- ``` -->

<!-- ```{r tab_bias2_norm_15, results='asis'} -->
<!-- bias2_norm %>%  -->
<!--   filter(Y=="15") %>% select(!Y) %>% -->
<!--   kbl(., align="lrlrrrrr", -->
<!--     caption="Normalized Bias Summary Statistics of $\\beta_{t}$, $t=$Defense, by Model and Proportion of Validation Samples. -->
<!--       Proxy on the RHS: $V = Y^\\top \\beta = \\sum_{t} Y_t \\beta_t$", -->
<!--     digits=3, booktabs=T, linesep = "", escape=F) %>% -->
<!--   kable_styling(latex_options = "striped", stripe_index = stripe(3)) -->
<!-- ``` -->

<!-- ```{r tab_bias2_norm_19, results='asis'} -->
<!-- bias2_norm %>%  -->
<!--   filter(Y=="19") %>% select(!Y) %>% -->
<!--   kbl(., align="lrlrrrrr", -->
<!--     caption="Normalized Bias Summary Statistics of $\\beta_{t}$, $t=$Government Operations, by Model and Proportion of Validation Samples. -->
<!--       Proxy on the RHS: $V = Y^\\top \\beta = \\sum_{t} Y_t \\beta_t$", -->
<!--     digits=3, booktabs=T, linesep = "", escape=F) %>% -->
<!--   kable_styling(latex_options = "striped", stripe_index = stripe(3)) -->
<!-- ``` -->

<!-- ```{r tab_bias2_norm_20, results='asis'} -->
<!-- bias2_norm %>%  -->
<!--   filter(Y=="20") %>% select(!Y) %>% -->
<!--   kbl(., align="lrlrrrrr", -->
<!--     caption="Normalized Bias Summary Statistics of $\\beta_{t}$, $t=$Public Lands and Water Management, by Model and Proportion of Validation Samples. -->
<!--       Proxy on the RHS: $V = Y^\\top \\beta = \\sum_{t} Y_t \\beta_t$", -->
<!--     digits=3, booktabs=T, linesep = "", escape=F) %>% -->
<!--   kable_styling(latex_options = "striped", stripe_index = stripe(3)) -->
<!-- ``` -->

<!-- ```{r tab_mse1, results='asis'} -->
<!-- mse1 <- regressions.averaged %>% -->
<!--   mutate(statistic=mse_mean) %>% -->
<!--   group_by(Y, proportion, regression) %>% -->
<!--   summarise( -->
<!--     "Mean" = mean(statistic), -->
<!--     "SD" = sd(statistic), -->
<!--     "Median" = median(statistic), -->
<!--     "5\\%" = quantile(statistic, probs[1]), -->
<!--     "95\\%" = quantile(statistic, probs[2]), -->
<!--     .groups = "drop") %>% -->
<!--   rename(c( -->
<!--     "Validation Proportion" = proportion, -->
<!--     "MSE" = regression) -->
<!--     ) -->
<!-- ``` -->

<!-- ```{r tab_mse1_3, results='asis'} -->
<!-- mse1 %>%  -->
<!--   filter(Y=="3") %>% select(!Y) %>% -->
<!--   kbl(., align="rlrrrrr", -->
<!--     caption="MSE Summary Statistics of $\\beta_{t}$, $t=$Health, by Proportion of Validation Samples. -->
<!--       Proxy on the RHS: $V = Y^\\top \\beta = \\sum_{t} Y_t \\beta_t$", -->
<!--     digits=3, booktabs=T, linesep = "", escape=F) %>% -->
<!--   kable_styling(latex_options = "striped", stripe_index = stripe(3)) -->
<!-- ``` -->

<!-- ```{r tab_mse1_14, results='asis'} -->
<!-- mse1 %>%  -->
<!--   filter(Y=="14") %>% select(!Y) %>% -->
<!--   kbl(., align="rlrrrrr", -->
<!--     caption="MSE Summary Statistics of $\\beta_{t}$, $t=$Banking, Finance, and Domestic Commerce, by Proportion of Validation Samples. -->
<!--       Proxy on the RHS: $V = Y^\\top \\beta = \\sum_{t} Y_t \\beta_t$", -->
<!--     digits=3, booktabs=T, linesep = "", escape=F) %>% -->
<!--   kable_styling(latex_options = "striped", stripe_index = stripe(3)) -->
<!-- ``` -->

<!-- ```{r tab_mse1_15, results='asis'} -->
<!-- mse1 %>%  -->
<!--   filter(Y=="15") %>% select(!Y) %>% -->
<!--   kbl(., align="rlrrrrr", -->
<!--     caption="MSE Summary Statistics of $\\beta_{t}$, $t=$Defense, by Proportion of Validation Samples. -->
<!--       Proxy on the RHS: $V = Y^\\top \\beta = \\sum_{t} Y_t \\beta_t$", -->
<!--     digits=3, booktabs=T, linesep = "", escape=F) %>% -->
<!--   kable_styling(latex_options = "striped", stripe_index = stripe(3)) -->
<!-- ``` -->

<!-- ```{r tab_mse1_19, results='asis'} -->
<!-- mse1 %>%  -->
<!--   filter(Y=="19") %>% select(!Y) %>% -->
<!--   kbl(., align="rlrrrrr", -->
<!--     caption="MSE Summary Statistics of $\\beta_{t}$, $t=$Government Operations, by Proportion of Validation Samples. -->
<!--       Proxy on the RHS: $V = Y^\\top \\beta = \\sum_{t} Y_t \\beta_t$", -->
<!--     digits=3, booktabs=T, linesep = "", escape=F) %>% -->
<!--   kable_styling(latex_options = "striped", stripe_index = stripe(3)) -->
<!-- ``` -->

<!-- ```{r tab_mse1_20, results='asis'} -->
<!-- mse1 %>%  -->
<!--   filter(Y=="20") %>% select(!Y) %>% -->
<!--   kbl(., align="rlrrrrr", -->
<!--     caption="MSE Summary Statistics of $\\beta_{t}$, $t=$Public Lands and Water Management, by Proportion of Validation Samples. -->
<!--       Proxy on the RHS: $V = Y^\\top \\beta = \\sum_{t} Y_t \\beta_t$", -->
<!--     digits=3, booktabs=T, linesep = "", escape=F) %>% -->
<!--   kable_styling(latex_options = "striped", stripe_index = stripe(3)) -->
<!-- ``` -->


<!-- ```{r tab_mse2, results='asis'} -->
<!-- mse2 <- regressions.averaged %>% -->
<!--   mutate(statistic=mse_mean) %>% -->
<!--   group_by(Y, model, proportion, regression) %>% -->
<!--   summarise( -->
<!--     "Mean" = mean(statistic), -->
<!--     "SD" = sd(statistic), -->
<!--     "Median" = median(statistic), -->
<!--     "5\\%" = quantile(statistic, probs[1]), -->
<!--     "95\\%" = quantile(statistic, probs[2]), -->
<!--     .groups = "drop") %>% -->
<!--   rename(c( -->
<!--     "Model" = model, -->
<!--     "Validation Proportion" = proportion, -->
<!--     "MSE" = regression -->
<!--     )) -->
<!-- ``` -->

<!-- ```{r tab_mse2_3, results='asis'} -->
<!-- mse2 %>%  -->
<!--   filter(Y=="3") %>% select(!Y) %>% -->
<!--   kbl(., align="lrlrrrrr", -->
<!--     caption="MSE Summary Statistics of $\\beta_{t}$, $t=$Health, by Model and Proportion of Validation Samples. -->
<!--       Proxy on the RHS: $V = Y^\\top \\beta = \\sum_{t} Y_t \\beta_t$", -->
<!--     digits=3, booktabs=T, linesep = "", escape=F) %>% -->
<!--   kable_styling(latex_options = "striped", stripe_index = stripe(3)) -->
<!-- ``` -->

<!-- ```{r tab_mse2_14, results='asis'} -->
<!-- mse2 %>%  -->
<!--   filter(Y=="14") %>% select(!Y) %>% -->
<!--   kbl(., align="lrlrrrrr", -->
<!--     caption="MSE Summary Statistics of $\\beta_{t}$, $t=$Banking, Finance, and Domestic Commerce, by Model and Proportion of Validation Samples. -->
<!--       Proxy on the RHS: $V = Y^\\top \\beta = \\sum_{t} Y_t \\beta_t$", -->
<!--     digits=3, booktabs=T, linesep = "", escape=F) %>% -->
<!--   kable_styling(latex_options = "striped", stripe_index = stripe(3)) -->
<!-- ``` -->

<!-- ```{r tab_mse2_15, results='asis'} -->
<!-- mse2 %>%  -->
<!--   filter(Y=="15") %>% select(!Y) %>% -->
<!--   kbl(., align="lrlrrrrr", -->
<!--     caption="MSE Summary Statistics of $\\beta_{t}$, $t=$Defense, by Model and Proportion of Validation Samples. -->
<!--       Proxy on the RHS: $V = Y^\\top \\beta = \\sum_{t} Y_t \\beta_t$", -->
<!--     digits=3, booktabs=T, linesep = "", escape=F) %>% -->
<!--   kable_styling(latex_options = "striped", stripe_index = stripe(3)) -->
<!-- ``` -->

<!-- ```{r tab_mse2_19, results='asis'} -->
<!-- mse2 %>%  -->
<!--   filter(Y=="19") %>% select(!Y) %>% -->
<!--   kbl(., align="lrlrrrrr", -->
<!--     caption="MSE Summary Statistics of $\\beta_{t}$, $t=$Government Operations, by Model and Proportion of Validation Samples. -->
<!--       Proxy on the RHS: $V = Y^\\top \\beta = \\sum_{t} Y_t \\beta_t$", -->
<!--     digits=3, booktabs=T, linesep = "", escape=F) %>% -->
<!--   kable_styling(latex_options = "striped", stripe_index = stripe(3)) -->
<!-- ``` -->

<!-- ```{r tab_mse2_20, results='asis'} -->
<!-- mse2 %>%  -->
<!--   filter(Y=="20") %>% select(!Y) %>% -->
<!--   kbl(., align="lrlrrrrr", -->
<!--     caption="MSE Summary Statistics of $\\beta_{t}$, $t=$Public Lands and Water Management, by Model and Proportion of Validation Samples. -->
<!--       Proxy on the RHS: $V = Y^\\top \\beta = \\sum_{t} Y_t \\beta_t$", -->
<!--     digits=3, booktabs=T, linesep = "", escape=F) %>% -->
<!--   kable_styling(latex_options = "striped", stripe_index = stripe(3)) -->
<!-- ``` -->

<!-- ```{r tab_coverage1, results='asis'} -->
<!-- coverage1 <- regressions.averaged %>% -->
<!--   mutate(statistic=coverage_mean) %>% -->
<!--   group_by(Y, proportion, regression) %>% -->
<!--   summarise( -->
<!--     "Mean" = mean(statistic), -->
<!--     "SD" = sd(statistic), -->
<!--     "Median" = median(statistic), -->
<!--     "5\\%" = quantile(statistic, probs[1]), -->
<!--     "95\\%" = quantile(statistic, probs[2]), -->
<!--     .groups = "drop") %>% -->
<!--   rename(c( -->
<!--     "Validation Proportion" = proportion, -->
<!--     "Coverage" = regression) -->
<!--     ) -->
<!-- ``` -->


<!-- ```{r tab_coverage1_3, results='asis'} -->
<!-- coverage1 %>%  -->
<!--   filter(Y=="3") %>% select(!Y) %>% -->
<!--   kbl(., align="rllrrrrr", -->
<!--     caption="Coverage Summary Statistics of $\\beta_{t}$, $t=$Health, by Proportion of Validation Samples. -->
<!--       Proxy on the RHS: $V = Y^\\top \\beta = \\sum_{t} Y_t \\beta_t$", -->
<!--     digits=3, booktabs=T, linesep = "", escape=F) %>% -->
<!--   kable_styling(latex_options = "striped", stripe_index = stripe(3)) -->
<!-- ``` -->


<!-- ```{r tab_coverage1_14, results='asis'} -->
<!-- coverage1 %>%  -->
<!--   filter(Y=="14") %>% select(!Y) %>% -->
<!--   kbl(., align="rllrrrrr", -->
<!--     caption="Coverage Summary Statistics of $\\beta_{t}$, $t=$Banking, Finance, and Domestic Commerce, by Proportion of Validation Samples. -->
<!--       Proxy on the RHS: $V = Y^\\top \\beta = \\sum_{t} Y_t \\beta_t$", -->
<!--     digits=3, booktabs=T, linesep = "", escape=F) %>% -->
<!--   kable_styling(latex_options = "striped", stripe_index = stripe(3)) -->
<!-- ``` -->


<!-- ```{r tab_coverage1_15, results='asis'} -->
<!-- coverage1 %>%  -->
<!--   filter(Y=="15") %>% select(!Y) %>% -->
<!--   kbl(., align="rllrrrrr", -->
<!--     caption="Coverage Summary Statistics of $\\beta_{t}$, $t=$Defense, by Proportion of Validation Samples. -->
<!--       Proxy on the RHS: $V = Y^\\top \\beta = \\sum_{t} Y_t \\beta_t$", -->
<!--     digits=3, booktabs=T, linesep = "", escape=F) %>% -->
<!--   kable_styling(latex_options = "striped", stripe_index = stripe(3)) -->
<!-- ``` -->


<!-- ```{r tab_coverage1_19, results='asis'} -->
<!-- coverage1 %>%  -->
<!--   filter(Y=="19") %>% select(!Y) %>% -->
<!--   kbl(., align="rllrrrrr", -->
<!--     caption="Coverage Summary Statistics of $\\beta_{t}$, $t=$Government Operations, by Proportion of Validation Samples. -->
<!--       Proxy on the RHS: $V = Y^\\top \\beta = \\sum_{t} Y_t \\beta_t$", -->
<!--     digits=3, booktabs=T, linesep = "", escape=F) %>% -->
<!--   kable_styling(latex_options = "striped", stripe_index = stripe(3)) -->
<!-- ``` -->


<!-- ```{r tab_coverage1_20, results='asis'} -->
<!-- coverage1 %>%  -->
<!--   filter(Y=="20") %>% select(!Y) %>% -->
<!--   kbl(., align="rllrrrrr", -->
<!--     caption="Coverage Summary Statistics of $\\beta_{t}$, $t=$Public Lands and Water Management, by Proportion of Validation Samples. -->
<!--       Proxy on the RHS: $V = Y^\\top \\beta = \\sum_{t} Y_t \\beta_t$", -->
<!--     digits=3, booktabs=T, linesep = "", escape=F) %>% -->
<!--   kable_styling(latex_options = "striped", stripe_index = stripe(3)) -->
<!-- ``` -->



<!-- ```{r tab_coverage2, results='asis'} -->
<!-- coverage2 <- regressions.averaged %>% -->
<!--   mutate(statistic=coverage_mean) %>% -->
<!--   group_by(Y, model, proportion, regression) %>% -->
<!--   summarise( -->
<!--     "Mean" = mean(statistic), -->
<!--     "SD" = sd(statistic), -->
<!--     "Median" = median(statistic), -->
<!--     "5\\%" = quantile(statistic, probs[1]), -->
<!--     "95\\%" = quantile(statistic, probs[2]), -->
<!--     .groups = "drop") %>% -->
<!--   rename(c( -->
<!--     "Model" = model, -->
<!--     "Validation Proportion" = proportion, -->
<!--     "MSE" = regression -->
<!--     )) -->
<!-- ``` -->

<!-- ```{r tab_coverage2_3, results='asis'} -->
<!-- coverage2 %>%  -->
<!--   filter(Y=="3") %>% select(!Y) %>% -->
<!--   kbl(., align="lrlrrrrr", -->
<!--     caption="Coverage Summary Statistics of $\\beta_{t}$, $t=$Health, by Model and Proportion of Validation Samples. -->
<!--       Proxy on the RHS: $V = Y^\\top \\beta = \\sum_{t} Y_t \\beta_t$", -->
<!--     digits=3, booktabs=T, linesep = "", escape=F) %>% -->
<!--   kable_styling(latex_options = "striped", stripe_index = stripe(3)) -->
<!-- ``` -->

<!-- ```{r tab_coverage2_14, results='asis'} -->
<!-- coverage2 %>%  -->
<!--   filter(Y=="14") %>% select(!Y) %>% -->
<!--   kbl(., align="lrlrrrrr", -->
<!--     caption="Coverage Summary Statistics of $\\beta_{t}$, $t=$Banking, Finance, and Domestic Commerce, by Model and Proportion of Validation Samples. -->
<!--       Proxy on the RHS: $V = Y^\\top \\beta = \\sum_{t} Y_t \\beta_t$", -->
<!--     digits=3, booktabs=T, linesep = "", escape=F) %>% -->
<!--   kable_styling(latex_options = "striped", stripe_index = stripe(3)) -->
<!-- ``` -->

<!-- ```{r tab_coverage2_15, results='asis'} -->
<!-- coverage2 %>%  -->
<!--   filter(Y=="15") %>% select(!Y) %>% -->
<!--   kbl(., align="lrlrrrrr", -->
<!--     caption="Coverage Summary Statistics of $\\beta_{t}$, $t=$Defense, by Model and Proportion of Validation Samples. -->
<!--       Proxy on the RHS: $V = Y^\\top \\beta = \\sum_{t} Y_t \\beta_t$", -->
<!--     digits=3, booktabs=T, linesep = "", escape=F) %>% -->
<!--   kable_styling(latex_options = "striped", stripe_index = stripe(3)) -->
<!-- ``` -->

<!-- ```{r tab_coverage2_19, results='asis'} -->
<!-- coverage2 %>%  -->
<!--   filter(Y=="19") %>% select(!Y) %>% -->
<!--   kbl(., align="lrlrrrrr", -->
<!--     caption="Coverage Summary Statistics of $\\beta_{t}$, $t=$Government Operations, by Model and Proportion of Validation Samples. -->
<!--       Proxy on the RHS: $V = Y^\\top \\beta = \\sum_{t} Y_t \\beta_t$", -->
<!--     digits=3, booktabs=T, linesep = "", escape=F) %>% -->
<!--   kable_styling(latex_options = "striped", stripe_index = stripe(3)) -->
<!-- ``` -->

<!-- ```{r tab_coverage2_20, results='asis'} -->
<!-- coverage2 %>%  -->
<!--   filter(Y=="20") %>% select(!Y) %>% -->
<!--   kbl(., align="lrlrrrrr", -->
<!--     caption="Coverage Summary Statistics of $\\beta_{t}$, $t=$Public Lands and Water Management, by Model and Proportion of Validation Samples. -->
<!--       Proxy on the RHS: $V = Y^\\top \\beta = \\sum_{t} Y_t \\beta_t$", -->
<!--     digits=3, booktabs=T, linesep = "", escape=F) %>% -->
<!--   kable_styling(latex_options = "striped", stripe_index = stripe(3)) -->
<!-- ``` -->
