---
title: "Results RHS"
header-includes:
  - \usepackage{amsmath}
  - \usepackage[capposition=top]{floatrow}
  - \usepackage{caption}
output:
  pdf_document: 
    fig_caption: true
    fig_crop: false
date: "Aug 12, 2024"
editor_options: 
  chunk_output_type: console
---

```{r knitr_setup, warning=FALSE, message=FALSE, echo=FALSE}
repo_dir = "/Users/haya1/Documents/LanguageModel_Labels/congressional_bills_v2"
data_dir = file.path(repo_dir, "Data") 
fig_dir = file.path(repo_dir, "Figures and Tables/4.4_rhs_results/")
dir.create(fig_dir, showWarnings=FALSE, recursive = TRUE)

knitr_default_plot <- knitr::knit_hooks$get("plot")  
knitr::knit_hooks$set(plot = function(x, options) {  
  x <- knitr_default_plot(x, options) 
  if(!is.null(options$fig.note)) {  
    x  <- gsub(
      "\\end{figure}", 
      sprintf("\\floatfoot*{Note: %s}\\end{figure}", options$fig.note), 
      x, fixed=T)  
  }
  return(x)
})
knitr::opts_knit$set(root.dir = repo_dir)
knitr::opts_chunk$set(
  warning=FALSE, 
  message=FALSE, 
  echo = FALSE, 
  dev = "jpeg", 
  dpi=300, 
  fig.path = fig_dir,
  out.height = "\\textheight",  
  out.width = "\\textwidth",
  out.extra = "keepaspectratio=true"
  )

require(dplyr)
require(ggplot2)
require(latex2exp)
require(kableExtra)
require(extrafont)
require(lemon)
source(file.path(repo_dir, "Code/ggplot_theme.r"))
```

# Proxy on the RHS


```{r data_10k}
# Note: prompts were sorted based on the coefficients values of GPT3.5 model.
V.levels <- c("Democrat", "Senate", "DW1")

model.levels <- c("star", "gpt-3.5-turbo-0125", "gpt-4o-2024-05-13")
model.labels <- c("Human", "GPT-3.5", "GPT-4o")

Y.labeller <- function(Y) TeX(sprintf("$Y_{%s}$", Y)) 

prompt_index <- read.csv(file.path(data_dir, "rhs_10k_llm.csv")) %>%
  filter(tolower(model)=="gpt-3.5-turbo-0125") %>%
  group_by(V, coef_name) %>%
  arrange(V, coef_name, coef) %>% mutate(prompt.ordered_coef = row_number()) %>% # create prompt index ordered by coef
  arrange(V, coef_name, t) %>% mutate(prompt.ordered_t = row_number()) %>% # create prompt index ordered by t scores
  ungroup() %>%
  select(V, coef_name, prompt, prompt.ordered_coef, prompt.ordered_t) %>%
  distinct()

regressions.llm <- read.csv(file.path(data_dir, "rhs_10k_llm.csv")) %>%
  merge(x=., y=prompt_index, all=TRUE, sort=FALSE) %>%
  mutate(
    prompt.ordered_coef = as.factor(prompt.ordered_coef),
    prompt.ordered_t = as.factor(prompt.ordered_t),
    model = factor(model, levels=model.levels, labels=model.labels),
    Y = sub("Y","", coef_name), 
    V = factor(V, levels=V.levels)
    ) # %>%
  # filter(coef_name!="Other")

regressions.human <- read.csv(file.path(data_dir, "rhs_10k_human.csv")) %>%
  mutate(
    model = "star",
    model = factor(model, levels=model.levels, labels=model.labels),
    Y = sub("Y","", coef_name), 
    V = factor(V, levels=V.levels)
    ) # %>%
  # filter(coef_name!="Other")
```



```{r fig01_coef, fig.height=5.5, fig.width=9, fig.cap="$\\beta_t$  vs. Prompt for all $\\beta$s. Proxy on the RHS.", fig.align="center", fig.note="The coefficients were obtained by fitting the model $V = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19} \\beta_{19}+ Y_{20} \\beta_{20} + Y_\\text{Other} \\beta_\\text{Other}$ over 10,000 bills, with 95\\% confidence intervals computed using robust standard errors. Here, $Y_t$ denotes the indicator for topic $t$, where $Y_t = 1\\{Y = t\\}$ for $t \\in \\mathcal{T}$ and $Y_\\text{Other} = 1\\{Y \\notin \\mathcal{T}\\}$, with $\\mathcal{T} = \\{3, 14, 15, 19, 20\\}$ is the 5 most-common human-labeled topics in the bills data. The variable $V$ takes one of the following bills variables: Democrat, Senate, or DW1, where $\text{Democrat} = 1\\{\\text{Party} = \\text{Democrat}\\}$, $\\text{Senate} = 1\\{\\text{Chamber} = \\text{Senate}\\}$, and DW1 is the imputed DW1 score for the bill sponsor. The regressions based on human-labeled topics (red) were estimated with $Y_{t}^\\text{Human} = 1\\{Y^\\text{Human} = t\\}$, while the LLM-based regressions (GPT-3.5 in green, circles; and GPT-4o in blue, triangles) were estimated with $Y_{t,m,p}^\\text{LLM} = 1\\{Y_{m,p}^\\text{LLM} = t\\}$, where $m \\in \\{\\text{GPT-3.5}, \\text{GPT-4o}\\}$ denotes the LLM model and $p \\in \\{1, \\ldots, 12\\}$ denotes the prompt modifications. In each subplot, the indices for the prompts reflect the order chosen based on sorting the estimated values of the GPT-3.5 model in ascending order. The corresponding estimates for GPT-4o are aligned according to this order."}


coefs <- regressions.llm %>%
  ggplot(aes(x=prompt.ordered_coef, color=model, shape=model)) +

  geom_hline(aes(yintercept=lci, color=model), linetype="dashed", linewidth=0.3, data=regressions.human) +
  geom_hline(aes(yintercept=uci, color=model), linetype="dashed", linewidth=0.3, data=regressions.human) +
  geom_hline(aes(yintercept=coef, color=model), linewidth=0.5, data=regressions.human) +

  geom_errorbar(aes(ymin=lci, ymax=uci), position=position_dodge(width=0.5), width=0.5, linewidth=0.3) +
  geom_point(aes(y=coef), size=1.25, alpha=0.7, position=position_dodge(width=0.5)) +
  
  facet_grid(V ~ Y, labeller=labeller(Y=Y.labeller, .default = label_parsed), scales="free_y") +
  
  xlab("Prompt Index") +
  ylab("Coefficients") +
  
  scale_color_manual(name=NULL, values=my_colors, labels=model.labels) +
  guides(color = guide_legend(override.aes = list(shape = c(NA, 16, 17))), 
         shape = "none") +  # merge color and shape legends
  theme.point

coefs
```

```{r fig02_tscore, fig.height=5.5, fig.width=9, fig.cap="t-scores of each $\\beta_t$ vs. Prompt. Proxy on the RHS.", fig.align="center", fig.note="The t-scores were obtained by fitting the model $V = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19} \\beta_{19}+ Y_{20} \\beta_{20} + Y_\\text{Other} \\beta_\\text{Other}$ over 10,000 bills, with 95\\% confidence intervals computed using robust standard errors. Here, $Y_t$ denotes the indicator for topic $t$, where $Y_t = 1\\{Y = t\\}$ for $t \\in \\mathcal{T}$ and $Y_\\text{Other} = 1\\{Y \\notin \\mathcal{T}\\}$, with $\\mathcal{T} = \\{3, 14, 15, 19, 20\\}$ is the 5 most-common human-labeled topics in the bills data. The variable $V$ takes one of the following bills variables: Democrat, Senate, or DW1, where $\text{Democrat} = 1\\{\\text{Party} = \\text{Democrat}\\}$, $\\text{Senate} = 1\\{\\text{Chamber} = \\text{Senate}\\}$, and DW1 is the imputed DW1 score for the bill sponsor. The regressions based on human-labeled topics (red) were estimated with $Y_{t}^\\text{Human} = 1\\{Y^\\text{Human} = t\\}$, while the LLM-based regressions (GPT-3.5 in green, circles; and GPT-4o in blue, triangles) were estimated with $Y_{t,m,p}^\\text{LLM} = 1\\{Y_{m,p}^\\text{LLM} = t\\}$, where $m \\in \\{\\text{GPT-3.5}, \\text{GPT-4o}\\}$ denotes the LLM model and $p \\in \\{1, \\ldots, 12\\}$ denotes the prompt modifications. In each subplot, the indices for the prompts reflect the order chosen based on sorting the estimated values of the GPT-3.5 model in ascending order. The corresponding estimates for GPT-4o are aligned according to this order."}
tscores <- regressions.llm %>%
  ggplot(aes(x=prompt.ordered_t, color=model, shape=model)) +

  # geom_hline(aes(yintercept=t, color=model), linewidth=0.5, data=regressions.human) +
  geom_point(aes(y=t), size=1.25, alpha=0.7, position=position_dodge(width=0.5)) +

  facet_grid(V ~ Y, labeller=labeller(Y=Y.labeller, .default = label_parsed), scales="free_y") +
  
  xlab("Prompt Index") +
  ylab("t-scores") +

  scale_color_manual(name=NULL, values=my_colors, labels=model.labels[2:3]) +
  guides(color = guide_legend(override.aes = list(shape = c(NA, 16, 17)[2:3])), 
         shape = "none") +  # merge color and shape legends
  
  theme.point

tscores
```


\clearpage

```{r data_regressions.averaged}
regression.levels <- c("5k_V_Yllm", "train_V_Yhuman", "Vtilde_Ytilde")
regression.labels <- c("LLM", "Human Validation", "Debiased")

model.levels <- c("gpt-3.5-turbo-0125", "gpt-4o-2024-05-13")
model.labels <- c("GPT3.5", "GPT4o")

Y.levels <- c("3", "14", "15", "19", "20", "Other")

regressions.averaged <- read.csv(file.path(data_dir, "rhs_5k_llm_human_debiased_averaged.csv")) %>%
   mutate(
     bias_norm = bias_mean/coef_sd, 
     Y = factor(sub("Y","", coef_name), levels=Y.levels), 
     V = factor(V, levels=V.levels),
     model = factor(model, levels=model.levels, labels=model.labels),
     regression = factor(regression, levels=regression.levels, labels=regression.labels)
     ) %>%
  rename(proportion=train_proportion) # %>%
  # filter(Y!="Other")

facet.labeller <- labeller(
  Y = function(Y) TeX(sprintf("$Y_{%s}$", Y)),
  proportion = function(proportion) paste("'", sprintf("Validation Proportion=%s%%", as.numeric(proportion)*100),"'"),
  .default = label_parsed
  )

n_bins <- 30
```

```{r fig03_bias1, fig.height=9, fig.width=8, fig.cap="Bias Density Plots for all $\\beta$s by Proportion of Validation Samples. Proxy on the RHS.", fig.align="center", fig.note="The bias estimates were computed as the difference between the coefficient estimates from $N = 1000$ simulation runs, $\\bar{\\beta}_{V, \\eta, m,p} = \\sum_{i=1}^N \\beta_{t, V, \\eta, m,p}^{(i)} / N$, and the human-based coefficient from the entire set of 10,000 bills,  $\\beta_{t,V}^\\star$, using a regression model of the form $V = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19} \\beta_{19}+ Y_{20} \\beta_{20} + Y_\\text{Other} \\beta_\\text{Other}$, for topic $t\\in\\{3, 14, 15, 19, 20, \\text{Other}\\}$, variable $V\\in\\{\\text{Democrat}, \\text{Senate}, \\text{DW1}\\}$, validation proportion $\\eta\\in\\{5\\%, 10\\%, 25\\%, 50\\%\\}$, LLM model $m \\in \\{\\text{GPT-3.5}, \\text{GPT-4o}\\}$, and prompt $p \\in \\{1, \\ldots, 12\\}$. For the LLM-based models (green), a random sample of 5,000 bills drawn from the original 10,000 was used, with LLM-based labels, $Y_{t,m,p}^\\text{LLM} = 1\\{Y_{m,p}^\\text{LLM} = t\\}$. For the other two models—human-based (red) and debiased-based (brown)—the 5,000 sample were split into two subsets: validation and primary, with the size of the validation set determined by the validation proportion, $\\eta$. In the human-based model, only the human labels in the validation set were used, $Y_{t}^\\text{Human} = 1\\{Y^\\text{Human} = t\\}$, whereas the debiased estimates use both the validation and primary sets, with $Y_{t}^\\text{Human}$ from validation set used to estimate measurement errors and $Y_{t,m,p}^\\text{LLM}$ from the primary set used to obtain the coefficient estimates used to compute the reported bias."}

bias1 <- regressions.averaged %>%
  # filter(proportion!=0.25) %>%
  ggplot(aes(x=bias_mean, y=after_stat(max(group)*count/tapply(count, PANEL, FUN=sum)[PANEL]), 
             group=regression, fill=regression)) +
  geom_histogram(bins=n_bins, position=position_dodge()) +
  facet_grid(Y ~ proportion, labeller=facet.labeller, scales="free_x") +
  
  xlab("Bias") +
  ylab("Probability Densities") +
  
  scale_fill_manual(name=NULL, values=my_colors) +
  scale_x_symmetric(mid=0) + 
  scale_y_continuous(minor_breaks=seq(0,1, by=0.05), limits=c(0,1)) +
  theme.bar

bias1

```


```{r fig04_bias1_norm, fig.height=9, fig.width=8, fig.cap="Normalized Bias Density of $\\beta_1$ by Proportion of Validation Samples. Proxy on the LHS.", fig.align="center", fig.note="The normalized bias estimates were computed as the normalized difference between the coefficient estimates from $N = 1000$ simulation runs, $\\bar{\\beta}_{t, V, \\eta, m,p}$, and the human-based coefficient from the entire set of 10,000 bills,  $\\beta_{t,V}^\\star$, divided by the sample standard deviation, $s_{t,V,\\eta, m,p}$, where $s^2_{t,V,\\eta, m,p} = \\sum_{i=1}^N (\\beta_{t,V, \\eta, m,p}^{(i)} - \\bar{\\beta}_{t,V, \\eta, m,p})^2/(N-1)$ and all variables are as defined previously."}

bias1_norm <- regressions.averaged %>%
  # filter(proportion!=0.25) %>%
  ggplot(aes(x=bias_norm, y=after_stat(max(group)*count/tapply(count, PANEL, FUN=sum)[PANEL]),
             group=regression, fill=regression)) +
  geom_histogram(binwidth=0.09, position=position_dodge()) +
  facet_grid(Y ~ proportion, labeller=facet.labeller, scales="free_x") +
  
  xlab("Normalized Bias") +
  ylab("Probability Densities") +
  
  scale_fill_manual(name=NULL, values=my_colors) +
  scale_x_symmetric(mid=0) +
  scale_y_continuous(minor_breaks=seq(0,1, by=0.05), limits=c(0,1)) +
  theme.bar

bias1_norm
```


\clearpage

```{r fig05_bias2_3, fig.height=3*1.5, fig.width=8, fig.cap="Bias Density of $\\beta_{3}$ by Model and Proportion of Validation Samples. Proxy on the RHS.", fig.align="center"}
bias2 <- regressions.averaged %>%
  filter(
    # proportion!=0.25,
    Y=="3"
    ) %>%
  ggplot(aes(x=bias_mean, y=after_stat(max(group)*count/tapply(count, PANEL, FUN=sum)[PANEL]), 
             group=regression, fill=regression)) +
  geom_histogram(bins=n_bins, position=position_dodge()) +
  facet_grid(model ~ proportion, labeller=facet.labeller, scales="free_x") +
  
  xlab("Bias") +
  ylab("Probability Densities") +
  
  scale_fill_manual(name=NULL, values=my_colors) +
  scale_x_symmetric(mid=0) +
  scale_y_continuous(minor_breaks=seq(0,1, by=0.05), limits=c(0,1)) +
  theme.bar

bias2
```

```{r fig06_bias2_14, fig.height=3*1.5, fig.width=8, fig.cap="Bias Density of $\\beta_{14}$ by Model and Proportion of Validation Samples. Proxy on the RHS.", fig.align="center"}

bias2 <- regressions.averaged %>%
  filter(
    # proportion!=0.25,
    Y=="14"
    ) %>%
  ggplot(aes(x=bias_mean, y=after_stat(max(group)*count/tapply(count, PANEL, FUN=sum)[PANEL]), 
             group=regression, fill=regression)) +
  geom_histogram(bins=n_bins, position=position_dodge()) +
  facet_grid(model ~ proportion, labeller=facet.labeller, scales="free_x") +
  
  xlab("Bias") +
  ylab("Probability Densities") +
  
  scale_fill_manual(name=NULL, values=my_colors) +
  scale_x_symmetric(mid=0) +
  scale_y_continuous(minor_breaks=seq(0,1, by=0.05), limits=c(0,1)) +
  theme.bar

bias2
```


```{r fig07_bias2_15, fig.height=3*1.5, fig.width=8, fig.cap="Bias Density of $\\beta_{15}$ by Model and Proportion of Validation Samples. Proxy on the RHS.", fig.align="center"}

bias2 <- regressions.averaged %>%
  filter(
    # proportion!=0.25,
    Y=="15"
    ) %>%
  ggplot(aes(x=bias_mean, y=after_stat(max(group)*count/tapply(count, PANEL, FUN=sum)[PANEL]), 
             group=regression, fill=regression)) +
  geom_histogram(bins=n_bins, position=position_dodge()) +
  facet_grid(model ~ proportion, labeller=facet.labeller, scales="free_x") +
  
  xlab("Bias") +
  ylab("Probability Densities") +
  
  scale_fill_manual(name=NULL, values=my_colors) +
  scale_x_symmetric(mid=0) +
  scale_y_continuous(minor_breaks=seq(0,1, by=0.05), limits=c(0,1)) +
  theme.bar

bias2
```

```{r fig08_bias2_19, fig.height=3*1.5, fig.width=8, fig.cap="Bias Density of $\\beta_{19}$ by Model and Proportion of Validation Samples. Proxy on the RHS.", fig.align="center"}

bias2 <- regressions.averaged %>%
  filter(
    # proportion!=0.25,
    Y=="19"
    ) %>%
  ggplot(aes(x=bias_mean, y=after_stat(max(group)*count/tapply(count, PANEL, FUN=sum)[PANEL]), 
             group=regression, fill=regression)) +
  geom_histogram(bins=n_bins, position=position_dodge()) +
  facet_grid(model ~ proportion, labeller=facet.labeller, scales="free_x") +
  
  xlab("Bias") +
  ylab("Probability Densities") +
  
  scale_fill_manual(name=NULL, values=my_colors) +
  scale_x_symmetric(mid=0) +
  scale_y_continuous(minor_breaks=seq(0,1, by=0.05), limits=c(0,1)) +
  theme.bar

bias2
```

```{r fig09_bias2_20, fig.height=3*1.5, fig.width=8, fig.cap="Bias Density of $\\beta_{20}$ by Model and Proportion of Validation Samples. Proxy on the RHS.", fig.align="center"}

bias2 <- regressions.averaged %>%
  filter(
    # proportion!=0.25,
    Y=="20"
    ) %>%
  ggplot(aes(x=bias_mean, y=after_stat(max(group)*count/tapply(count, PANEL, FUN=sum)[PANEL]), 
             group=regression, fill=regression)) +
  geom_histogram(bins=n_bins, position=position_dodge()) +
  facet_grid(model ~ proportion, labeller=facet.labeller, scales="free_x") +
  
  xlab("Bias") +
  ylab("Probability Densities") +
  
  scale_fill_manual(name=NULL, values=my_colors) +
  scale_x_symmetric(mid=0) +
  scale_y_continuous(minor_breaks=seq(0,1, by=0.05), limits=c(0,1)) +
  theme.bar

bias2
```

```{r fig10_bias2_Other, fig.height=3*1.5, fig.width=8, fig.cap="Bias Density of $\\beta_\\text{Other}$ by Model and Proportion of Validation Samples. Proxy on the RHS.", fig.align="center"}

bias2 <- regressions.averaged %>%
  filter(
    # proportion!=0.25,
    Y=="Other"
    ) %>%
  ggplot(aes(x=bias_mean, y=after_stat(max(group)*count/tapply(count, PANEL, FUN=sum)[PANEL]), 
             group=regression, fill=regression)) +
  geom_histogram(bins=n_bins, position=position_dodge()) +
  facet_grid(model ~ proportion, labeller=facet.labeller, scales="free_x") +
  
  xlab("Bias") +
  ylab("Probability Densities") +
  
  scale_fill_manual(name=NULL, values=my_colors) +
  scale_x_symmetric(mid=0) +
  scale_y_continuous(minor_breaks=seq(0,1, by=0.05), limits=c(0,1)) +
  theme.bar

bias2
```

\clearpage 

```{r fig11_bias2_norm_3, fig.height=3*1.5, fig.width=8, fig.cap="Normalized Bias Density of $\\beta_{3}$ by Model and Proportion of Validation Samples. Proxy on the RHS.", fig.align="center"}

bias2_norm <- regressions.averaged %>%
  filter(
    # proportion!=0.25,
    Y=="3"
    ) %>%
  ggplot(aes(x=bias_norm, y=after_stat(max(group)*count/tapply(count, PANEL, FUN=sum)[PANEL]),
             group=regression, fill=regression)) +
  geom_histogram(binwidth=0.09, position=position_dodge()) +
  facet_grid(model ~ proportion, labeller=facet.labeller, scales="free_x") +
  
  xlab("Normalized Bias") +
  ylab("Probability Densities") +
  
  scale_fill_manual(name=NULL, values=my_colors) +
  scale_x_symmetric(mid=0) +
  scale_y_continuous(minor_breaks=seq(0,1, by=0.05), limits=c(0,1)) +
  theme.bar

bias2_norm
```

```{r fig12_bias2_norm_14, fig.height=3*1.5, fig.width=8, fig.cap="Normalized Bias Density of $\\beta_{14}$ by Model and Proportion of Validation Samples. Proxy on the RHS.", fig.align="center"}

bias2_norm <- regressions.averaged %>%
  filter(
    # proportion!=0.25,
    Y=="14"
    ) %>%
  ggplot(aes(x=bias_norm, y=after_stat(max(group)*count/tapply(count, PANEL, FUN=sum)[PANEL]),
             group=regression, fill=regression)) +
  geom_histogram(binwidth=0.09, position=position_dodge()) +
  facet_grid(model ~ proportion, labeller=facet.labeller, scales="free_x") +
  
  xlab("Normalized Bias") +
  ylab("Probability Densities") +
  
  scale_fill_manual(name=NULL, values=my_colors) +
  scale_x_symmetric(mid=0) +
  scale_y_continuous(minor_breaks=seq(0,1, by=0.05), limits=c(0,1)) +
  theme.bar

bias2_norm
```

```{r fig13_bias2_norm_15, fig.height=3*1.5, fig.width=8, fig.cap="Normalized Bias Density of $\\beta_{15}$ by Model and Proportion of Validation Samples. Proxy on the RHS.", fig.align="center"}

bias2_norm <- regressions.averaged %>%
  filter(
    # proportion!=0.25,
    Y=="15"
    ) %>%
  ggplot(aes(x=bias_norm, y=after_stat(max(group)*count/tapply(count, PANEL, FUN=sum)[PANEL]),
             group=regression, fill=regression)) +
  geom_histogram(binwidth=0.09, position=position_dodge()) +
  facet_grid(model ~ proportion, labeller=facet.labeller, scales="free_x") +
  
  xlab("Normalized Bias") +
  ylab("Probability Densities") +
  
  scale_fill_manual(name=NULL, values=my_colors) +
  scale_x_symmetric(mid=0) +
  scale_y_continuous(minor_breaks=seq(0,1, by=0.05), limits=c(0,1)) +
  theme.bar

bias2_norm
```

```{r fig14_bias2_norm_19, fig.height=3*1.5, fig.width=8, fig.cap="Normalized Bias Density of $\\beta_{19}$ by Model and Proportion of Validation Samples. Proxy on the RHS.", fig.align="center"}

bias2_norm <- regressions.averaged %>%
  filter(
    # proportion!=0.25,
    Y=="19"
    ) %>%
  ggplot(aes(x=bias_norm, y=after_stat(max(group)*count/tapply(count, PANEL, FUN=sum)[PANEL]),
             group=regression, fill=regression)) +
  geom_histogram(binwidth=0.09, position=position_dodge()) +
  facet_grid(model ~ proportion, labeller=facet.labeller, scales="free_x") +
  
  xlab("Normalized Bias") +
  ylab("Probability Densities") +
  
  scale_fill_manual(name=NULL, values=my_colors) +
  scale_x_symmetric(mid=0) +
  scale_y_continuous(minor_breaks=seq(0,1, by=0.05), limits=c(0,1)) +
  theme.bar

bias2_norm
```

```{r fig15_bias2_norm_20, fig.height=3*1.5, fig.width=8, fig.cap="Normalized Bias Density of $\\beta_{20}$ by Model and Proportion of Validation Samples. Proxy on the RHS.", fig.align="center"}

bias2_norm <- regressions.averaged %>%
  filter(
    # proportion!=0.25,
    Y=="20"
    ) %>%
  ggplot(aes(x=bias_norm, y=after_stat(max(group)*count/tapply(count, PANEL, FUN=sum)[PANEL]),
             group=regression, fill=regression)) +
  geom_histogram(binwidth=0.09, position=position_dodge()) +
  facet_grid(model ~ proportion, labeller=facet.labeller, scales="free_x") +
  
  xlab("Normalized Bias") +
  ylab("Probability Densities") +
  
  scale_fill_manual(name=NULL, values=my_colors) +
  scale_x_symmetric(mid=0) +
  scale_y_continuous(minor_breaks=seq(0,1, by=0.05), limits=c(0,1)) +
  theme.bar

bias2_norm
```

```{r fig16_bias2_norm_Other, fig.height=3*1.5, fig.width=8, fig.cap="Normalized Bias Density of $\\beta_\\text{Other}$ by Model and Proportion of Validation Samples. Proxy on the RHS.", fig.align="center"}

bias2_norm <- regressions.averaged %>%
  filter(
    # proportion!=0.25,
    Y=="Other"
    ) %>%
  ggplot(aes(x=bias_norm, y=after_stat(max(group)*count/tapply(count, PANEL, FUN=sum)[PANEL]),
             group=regression, fill=regression)) +
  geom_histogram(binwidth=0.09, position=position_dodge()) +
  facet_grid(model ~ proportion, labeller=facet.labeller, scales="free_x") +
  
  xlab("Normalized Bias") +
  ylab("Probability Densities") +
  
  scale_fill_manual(name=NULL, values=my_colors) +
  scale_x_symmetric(mid=0) +
  scale_y_continuous(minor_breaks=seq(0,1, by=0.05), limits=c(0,1)) +
  theme.bar

bias2_norm
```


\clearpage

```{r fig17_mse1, fig.height=11, fig.width=8, fig.cap="MSE Empirical CDF for all $\\beta$s by Proportion of Validation Samples. Proxy on the RHS.", fig.align="center"}

mse1 <- regressions.averaged %>%
  filter(
    # proportion != 0.25,
    regression != "LLM"
    ) %>%
  ggplot(aes(x=mse_mean, color=regression, linetype=regression)) +
  
  stat_ecdf(linewidth=0.5) +
  facet_grid(Y ~ proportion, labeller=facet.labeller, scales="free_x") +
  
  xlab("MSE") +
  ylab("Empirical CDF") +
  
  coord_cartesian(xlim=c(0,0.03)) +
  scale_color_manual(name="", values=my_colors) +
  scale_linetype_manual(name="", values=c("dashed", "solid")) +
  theme.mse

mse1
```

```{r fig18_mse2_3, fig.height=4, fig.width=8, fig.cap="MSE Empirical CDF of $\\beta_3$ by Model and Proportion of Validation Samples. Proxy on the RHS.", fig.align="center"}

mse2 <- regressions.averaged %>%
  filter(
    # proportion != 0.25,
    regression != "LLM",
    Y == "3"
    ) %>%
  ggplot(aes(x=mse_mean, color=regression, linetype=regression)) +
  
  stat_ecdf(linewidth=0.5) +
  facet_grid(model ~ proportion, labeller=facet.labeller, scales="free_x") +
  
  xlab("MSE") +
  ylab("Empirical CDF") +
  
  coord_cartesian(xlim=c(0,0.02)) +
  scale_color_manual(name="", values=my_colors) +
  scale_linetype_manual(name="", values=c("dashed", "solid")) +
  theme.mse

mse2
```

```{r fig19_mse2_14, fig.height=4, fig.width=8, fig.cap="MSE Empirical CDF of $\\beta_{14}$ by Model and Proportion of Validation Samples. Proxy on the RHS.", fig.align="center"}

mse2 <- regressions.averaged %>%
  filter(
    # proportion != 0.25,
    regression != "LLM",
    Y == "14"
    ) %>%
  ggplot(aes(x=mse_mean, color=regression, linetype=regression)) +
  
  stat_ecdf(linewidth=0.5) +
  facet_grid(model ~ proportion, labeller=facet.labeller, scales="free_x") +
  
  xlab("MSE") +
  ylab("Empirical CDF") +
  
  coord_cartesian(xlim=c(0,0.09)) +
  scale_color_manual(name="", values=my_colors) +
  scale_linetype_manual(name="", values=c("dashed", "solid")) +
  theme.mse

mse2
```


```{r fig20_mse2_15, fig.height=4, fig.width=8, fig.cap="MSE Empirical CDF of $\\beta_{15}$ by Model and Proportion of Validation Samples. Proxy on the RHS.", fig.align="center"}

mse2 <- regressions.averaged %>%
  filter(
    # proportion != 0.25,
    regression != "LLM",
    Y == "15"
    ) %>%
  ggplot(aes(x=mse_mean, color=regression, linetype=regression)) +
  
  stat_ecdf(linewidth=0.5) +
  facet_grid(model ~ proportion, labeller=facet.labeller, scales="free_x") +
  
  xlab("MSE") +
  ylab("Empirical CDF") +
  
  coord_cartesian(xlim=c(0,0.03)) +
  scale_color_manual(name="", values=my_colors) +
  scale_linetype_manual(name="", values=c("dashed", "solid")) +
  theme.mse

mse2
```


```{r fig21_mse2_19, fig.height=4, fig.width=8, fig.cap="MSE Empirical CDF of $\\beta_{19}$ by Model and Proportion of Validation Samples. Proxy on the RHS.", fig.align="center"}

mse2 <- regressions.averaged %>%
  filter(
    # proportion != 0.25,
    regression != "LLM",
    Y == "19"
    ) %>%
  ggplot(aes(x=mse_mean, color=regression, linetype=regression)) +
  
  stat_ecdf(linewidth=0.5) +
  facet_grid(model ~ proportion, labeller=facet.labeller, scales="free_x") +
  
  xlab("MSE") +
  ylab("Empirical CDF") +
  
  coord_cartesian(xlim=c(0,0.03)) +
  scale_color_manual(name="", values=my_colors) +
  scale_linetype_manual(name="", values=c("dashed", "solid")) +
  theme.mse

mse2
```


```{r fig22_mse2_20, fig.height=4, fig.width=8, fig.cap="MSE Empirical CDF of $\\beta_{20}$ by Model and Proportion of Validation Samples. Proxy on the RHS.", fig.align="center"}

mse2 <- regressions.averaged %>%
  filter(
    # proportion != 0.25,
    regression != "LLM",
    Y == "20"
    ) %>%
  ggplot(aes(x=mse_mean, color=regression, linetype=regression)) +
  
  stat_ecdf(linewidth=0.5) +
  facet_grid(model ~ proportion, labeller=facet.labeller, scales="free_x") +
  
  xlab("MSE") +
  ylab("Empirical CDF") +
  
  coord_cartesian(xlim=c(0,0.015)) +
  scale_color_manual(name="", values=my_colors) +
  scale_linetype_manual(name="", values=c("dashed", "solid")) +
  theme.mse

mse2
```


```{r fig23_mse2_other, fig.height=4, fig.width=8, fig.cap="MSE Empirical CDF of $\\beta_\\text{Other}$ by Model and Proportion of Validation Samples. Proxy on the RHS.", fig.align="center"}

mse2 <- regressions.averaged %>%
  filter(
    # proportion != 0.25,
    regression != "LLM",
    Y == "Other"
    ) %>%
  ggplot(aes(x=mse_mean, color=regression, linetype=regression)) +
  
  stat_ecdf(linewidth=0.5) +
  facet_grid(model ~ proportion, labeller=facet.labeller, scales="free_x") +
  
  xlab("MSE") +
  ylab("Empirical CDF") +
  
  coord_cartesian(xlim=c(0,0.008)) +
  scale_color_manual(name="", values=my_colors) +
  scale_linetype_manual(name="", values=c("dashed", "solid")) +
  theme.mse

mse2
```

\clearpage

```{r tab_data}
regression.levels <- c("5k_V_Yllm", "train_V_Yhuman", "Vtilde_Ytilde")
regression.labels <- c("LLM", "Human Validation", "Debiased")

model.levels <- c("gpt-3.5", "gpt-4o")
model.labels <- c("GPT-3.5", "GPT-4o")

proportion.levels <- c(0.05, 0.10, 0.25, 0.50)
proportion.labels <- sprintf("%s\\%%", proportion.levels*100)

Y.levels <- c("3", "14", "15", "19", "20", "Other")
Y.labels <- sprintf("$Y_{%s}$", Y.levels)

regressions.averaged <- read.csv(file.path(data_dir, "rhs_5k_llm_human_debiased_averaged.csv")) %>%
  rename(proportion=train_proportion) %>%
   mutate(
     bias_norm = bias_mean/coef_sd, 
     Y = sub("Y","", coef_name),
     V = factor(V, levels=V.levels),
     model = factor(model, levels=model.levels, labels=model.labels),
     regression = factor(regression, levels=regression.levels, labels=regression.labels),
     proportion = factor(proportion, levels=proportion.levels, labels=proportion.labels),
     ) # %>%
  # filter(Y!="Other")

alpha <- 0.10
probs <- c(alpha/2, 1-alpha/2)

stripe <- function(nstriped=3, nrow=50){
  start_row <- rep(seq(0, (2*nstriped)*nrow, by=2*nstriped), each=nstriped)
  return(start_row + rep(1:nstriped, times=length(start_row)/nstriped))
}


```

```{r tab_bias1, results='asis'}
bias1 <- regressions.averaged %>%
  mutate(statistic=bias_mean) %>%
  group_by(Y, proportion, regression) %>%
  summarise(
    "Mean" = mean(statistic),
    "SD" = sd(statistic),
    "Median" = median(statistic),
    "5\\%" = quantile(statistic, probs[1]),
    "95\\%" = quantile(statistic, probs[2]),
    .groups = "drop"
    ) %>%
  rename(c(
    "Validation Proportion" = proportion, 
    "Bias" = regression)
    )
```

```{r tab_bias1_3, results='asis'}
bias1 %>% 
  filter(Y=="3") %>% select(!Y) %>%
  kbl(., align="rlrrrrr",
      caption="Bias Summary Statistics of $\\beta_{3}$ by Proportion of Validation Samples.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_\\text{Other} \\beta_\\text{Other}$",
      digits=3, booktabs=T, linesep = "", escape=F) %>%
    kable_styling(latex_options = "striped", stripe_index = stripe(3))
```

```{r tab_bias1_14, results='asis'}
bias1 %>% 
  filter(Y=="14") %>% select(!Y) %>%
  kbl(., align="rlrrrrr",
      caption="Bias Summary Statistics of $\\beta_{14}$ by Proportion of Validation Samples.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_\\text{Other} \\beta_\\text{Other}$",
      digits=3, booktabs=T, linesep = "", escape=F) %>%
    kable_styling(latex_options = "striped", stripe_index = stripe(3))
```

```{r tab_bias1_15, results='asis'}
bias1 %>% 
  filter(Y=="15") %>% select(!Y) %>%
  kbl(., align="rlrrrrr",
      caption="Bias Summary Statistics of $\\beta_{15}$ by Proportion of Validation Samples.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_\\text{Other} \\beta_\\text{Other}$",
      digits=3, booktabs=T, linesep = "", escape=F) %>%
    kable_styling(latex_options = "striped", stripe_index = stripe(3))
```

```{r tab_bias1_19, results='asis'}
bias1 %>% 
  filter(Y=="19") %>% select(!Y) %>%
  kbl(., align="rlrrrrr",
      caption="Bias Summary Statistics of $\\beta_{19}$ by Proportion of Validation Samples.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_\\text{Other} \\beta_\\text{Other}$",
      digits=3, booktabs=T, linesep = "", escape=F) %>%
    kable_styling(latex_options = "striped", stripe_index = stripe(3))
```

```{r tab_bias1_20, results='asis'}
bias1 %>% 
  filter(Y=="20") %>% select(!Y) %>%
  kbl(., align="rlrrrrr",
      caption="Bias Summary Statistics of $\\beta_{20}$ by Proportion of Validation Samples.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_\\text{Other} \\beta_\\text{Other}$",
      digits=3, booktabs=T, linesep = "", escape=F) %>%
    kable_styling(latex_options = "striped", stripe_index = stripe(3))

```

```{r tab_bias1_Other, results='asis'}
bias1 %>% 
  filter(Y=="Other") %>% select(!Y) %>%
  kbl(., align="rlrrrrr",
      caption="Bias Summary Statistics of $\\beta_\\text{Other}$ by Proportion of Validation Samples.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_\\text{Other} \\beta_\\text{Other}$",
      digits=3, booktabs=T, linesep = "", escape=F) %>%
    kable_styling(latex_options = "striped", stripe_index = stripe(3))
```

```{r tab_bias1_norm, results='asis'}
bias1_norm <- regressions.averaged %>%
  mutate(statistic=bias_norm) %>%
  group_by(Y, proportion, regression) %>%
  summarise(
    "Mean" = mean(statistic),
    "SD" = sd(statistic),
    "Median" = median(statistic),
    "5\\%" = quantile(statistic, probs[1]),
    "95\\%" = quantile(statistic, probs[2]),
    .groups = "drop"
    ) %>%
  rename(c(
    "Validation Proportion" = proportion, 
    "Normalized Bias" = regression)
    )
```

```{r tab_bias1_norm_3, results='asis'}
bias1_norm %>% 
  filter(Y=="3") %>% select(!Y) %>%
  kbl(., align="rlrrrrr",
    caption="Normalized Bias Summary Statistics of $\\beta_{3}$ by Proportion of Validation Samples.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_\\text{Other} \\beta_\\text{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))
```

```{r tab_bias1_norm_14, results='asis'}
bias1_norm %>% 
  filter(Y=="14") %>% select(!Y) %>%
  kbl(., align="rlrrrrr",
    caption="Normalized Bias Summary Statistics of $\\beta_{14}$ by Proportion of Validation Samples.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_\\text{Other} \\beta_\\text{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))
```

```{r tab_bias1_norm_15, results='asis'}
bias1_norm %>% 
  filter(Y=="15") %>% select(!Y) %>%
  kbl(., align="rlrrrrr",
    caption="Normalized Bias Summary Statistics of $\\beta_{15}$ by Proportion of Validation Samples.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_\\text{Other} \\beta_\\text{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))
```

```{r tab_bias1_norm_19, results='asis'}
bias1_norm %>% 
  filter(Y=="19") %>% select(!Y) %>%
  kbl(., align="rlrrrrr",
    caption="Normalized Bias Summary Statistics of $\\beta_{19}$ by Proportion of Validation Samples.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_\\text{Other} \\beta_\\text{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))
```

```{r tab_bias1_norm_20, results='asis'}
bias1_norm %>% 
  filter(Y=="20") %>% select(!Y) %>%
  kbl(., align="rlrrrrr",
    caption="Normalized Bias Summary Statistics of $\\beta_{20}$ by Proportion of Validation Samples.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_\\text{Other} \\beta_\\text{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))
```

```{r tab_bias1_norm_Other, results='asis'}
bias1_norm %>% 
  filter(Y=="Other") %>% select(!Y) %>%
  kbl(., align="rlrrrrr",
    caption="Normalized Bias Summary Statistics of $\\beta_\\text{Other}$ by Proportion of Validation Samples.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_\\text{Other} \\beta_\\text{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))
```


```{r tab_bias2, results='asis'}
bias2 <- regressions.averaged %>%
  mutate(statistic=bias_mean) %>%
  group_by(Y, model, proportion, regression) %>%
  summarise(
    "Mean" = mean(statistic),
    "SD" = sd(statistic),
    "Median" = median(statistic),
    "5\\%" = quantile(statistic, probs[1]),
    "95\\%" = quantile(statistic, probs[2]),
    .groups = "drop"
    ) %>%
  rename(c(
    "Model" = model, 
    "Validation Proportion" = proportion, 
    "Bias" = regression
    ))
```

```{r tab_bias2_3, results='asis'}
bias2 %>% 
  filter(Y=="3") %>% select(!Y) %>%
  kbl(., align="lrlrrrrr",
    caption="Bias Summary Statistics of $\\beta_{3}$ by Model and Proportion of Validation Samples.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_\\text{Other} \\beta_\\text{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))
```

```{r tab_bias2_14, results='asis'}
bias2 %>% 
  filter(Y=="14") %>% select(!Y) %>%
  kbl(., align="lrlrrrrr",
    caption="Bias Summary Statistics of $\\beta_{14}$ by Model and Proportion of Validation Samples.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_\\text{Other} \\beta_\\text{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))
```

```{r tab_bias2_15, results='asis'}
bias2 %>% 
  filter(Y=="15") %>% select(!Y) %>%
  kbl(., align="lrlrrrrr",
    caption="Bias Summary Statistics of $\\beta_{15}$ by Model and Proportion of Validation Samples.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_\\text{Other} \\beta_\\text{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))
```

```{r tab_bias2_19, results='asis'}
bias2 %>% 
  filter(Y=="19") %>% select(!Y) %>%
  kbl(., align="lrlrrrrr",
    caption="Bias Summary Statistics of $\\beta_{19}$ by Model and Proportion of Validation Samples.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_\\text{Other} \\beta_\\text{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))
```

```{r tab_bias2_20, results='asis'}
bias2 %>% 
  filter(Y=="20") %>% select(!Y) %>%
  kbl(., align="lrlrrrrr",
    caption="Bias Summary Statistics of $\\beta_{20}$ by Model and Proportion of Validation Samples.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_\\text{Other} \\beta_\\text{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))
```

```{r tab_bias2_Other, results='asis'}
bias2 %>% 
  filter(Y=="Other") %>% select(!Y) %>%
  kbl(., align="lrlrrrrr",
    caption="Bias Summary Statistics of $\\beta_\\text{Other}$ by Model and Proportion of Validation Samples for.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_\\text{Other} \\beta_\\text{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))
```


```{r tab_bias2_norm, results='asis'}
bias2_norm <- regressions.averaged %>%
  mutate(statistic=bias_norm) %>%
  group_by(Y, model, proportion, regression) %>%
  summarise(
    "Mean" = mean(statistic),
    "SD" = sd(statistic),
    "Median" = median(statistic),
    "5\\%" = quantile(statistic, probs[1]),
    "95\\%" = quantile(statistic, probs[2]),
    .groups = "drop"
    ) %>%
  rename(c(
    "Model" = model, 
    "Validation Proportion" = proportion, 
    "Normalized Bias" = regression
    ))
```

```{r tab_bias2_norm_3, results='asis'}
bias2_norm %>% 
  filter(Y=="3") %>% select(!Y) %>%
  kbl(., align="lrlrrrrr",
    caption="Normalized Bias Summary of $\\beta_{3}$ Statistics by Model and Proportion of Validation Samples.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_\\text{Other} \\beta_\\text{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))
```

```{r tab_bias2_norm_14, results='asis'}
bias2_norm %>% 
  filter(Y=="14") %>% select(!Y) %>%
  kbl(., align="lrlrrrrr",
    caption="Normalized Bias Summary Statistics of $\\beta_{14}$ by Model and Proportion of Validation Samples.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_\\text{Other} \\beta_\\text{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))
```

```{r tab_bias2_norm_15, results='asis'}
bias2_norm %>% 
  filter(Y=="15") %>% select(!Y) %>%
  kbl(., align="lrlrrrrr",
    caption="Normalized Bias Summary Statistics of $\\beta_{15}$ by Model and Proportion of Validation Samples.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_\\text{Other} \\beta_\\text{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))
```

```{r tab_bias2_norm_19, results='asis'}
bias2_norm %>% 
  filter(Y=="19") %>% select(!Y) %>%
  kbl(., align="lrlrrrrr",
    caption="Normalized Bias Summary Statistics of $\\beta_{19}$ by Model and Proportion of Validation Samples.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_\\text{Other} \\beta_\\text{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))
```

```{r tab_bias2_norm_20, results='asis'}
bias2_norm %>% 
  filter(Y=="20") %>% select(!Y) %>%
  kbl(., align="lrlrrrrr",
    caption="Normalized Bias Summary Statistics of $\\beta_{20}$ by Model and Proportion of Validation Samples.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_\\text{Other} \\beta_\\text{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))
```

```{r tab_bias2_norm_Other, results='asis'}
bias2_norm %>% 
  filter(Y=="Other") %>% select(!Y) %>%
  kbl(., align="lrlrrrrr",
    caption="Normalized Bias Summary Statistics of $\\beta_\\text{Other}$ by Model and Proportion of Validation Samples.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_\\text{Other} \\beta_\\text{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))
```

```{r tab_mse1, results='asis'}
mse1 <- regressions.averaged %>%
  mutate(statistic=mse_mean) %>%
  group_by(Y, proportion, regression) %>%
  summarise(
    "Mean" = mean(statistic),
    "SD" = sd(statistic),
    "Median" = median(statistic),
    "5\\%" = quantile(statistic, probs[1]),
    "95\\%" = quantile(statistic, probs[2]),
    .groups = "drop") %>%
  rename(c(
    "Validation Proportion" = proportion,
    "MSE" = regression)
    )
```

```{r tab_mse1_3, results='asis'}
mse1 %>% 
  filter(Y=="3") %>% select(!Y) %>%
  kbl(., align="rlrrrrr",
    caption="MSE Summary Statistics of $\\beta_{3}$ by Proportion of Validation Samples.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_\\text{Other} \\beta_\\text{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))
```

```{r tab_mse1_14, results='asis'}
mse1 %>% 
  filter(Y=="14") %>% select(!Y) %>%
  kbl(., align="rlrrrrr",
    caption="MSE Summary Statistics of $\\beta_{14}$ by Proportion of Validation Samples.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_\\text{Other} \\beta_\\text{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))
```

```{r tab_mse1_15, results='asis'}
mse1 %>% 
  filter(Y=="15") %>% select(!Y) %>%
  kbl(., align="rlrrrrr",
    caption="MSE Summary Statistics of $\\beta_{15}$ by Proportion of Validation Samples.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_\\text{Other} \\beta_\\text{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))
```

```{r tab_mse1_19, results='asis'}
mse1 %>% 
  filter(Y=="19") %>% select(!Y) %>%
  kbl(., align="rlrrrrr",
    caption="MSE Summary Statistics of $\\beta_{19}$ by Proportion of Validation Samples.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_\\text{Other} \\beta_\\text{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))
```

```{r tab_mse1_20, results='asis'}
mse1 %>% 
  filter(Y=="20") %>% select(!Y) %>%
  kbl(., align="rlrrrrr",
    caption="MSE Summary Statistics of $\\beta_{20}$ by Proportion of Validation Samples.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_\\text{Other} \\beta_\\text{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))
```

```{r tab_mse1_Other, results='asis'}
mse1 %>% 
  filter(Y=="Other") %>% select(!Y) %>%
  kbl(., align="rlrrrrr",
    caption="MSE Summary Statistics of $\\beta_\\text{Other}$ by Proportion of Validation Samples.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_\\text{Other} \\beta_\\text{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))
```


```{r tab_mse2, results='asis'}
mse2 <- regressions.averaged %>%
  mutate(statistic=mse_mean) %>%
  group_by(Y, model, proportion, regression) %>%
  summarise(
    "Mean" = mean(statistic),
    "SD" = sd(statistic),
    "Median" = median(statistic),
    "5\\%" = quantile(statistic, probs[1]),
    "95\\%" = quantile(statistic, probs[2]),
    .groups = "drop") %>%
  rename(c(
    "Model" = model,
    "Validation Proportion" = proportion,
    "MSE" = regression
    ))
```

```{r tab_mse2_3, results='asis'}
mse2 %>% 
  filter(Y=="3") %>% select(!Y) %>%
  kbl(., align="lrlrrrrr",
    caption="MSE Summary Statistics of $\\beta_{3}$ by Model and Proportion of Validation Samples.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_\\text{Other} \\beta_\\text{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))
```

```{r tab_mse2_14, results='asis'}
mse2 %>% 
  filter(Y=="14") %>% select(!Y) %>%
  kbl(., align="lrlrrrrr",
    caption="MSE Summary Statistics of $\\beta_{14}$ by Model and Proportion of Validation Samples.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_\\text{Other} \\beta_\\text{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))
```

```{r tab_mse2_15, results='asis'}
mse2 %>% 
  filter(Y=="15") %>% select(!Y) %>%
  kbl(., align="lrlrrrrr",
    caption="MSE Summary Statistics of $\\beta_{15}$ by Model and Proportion of Validation Samples.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_\\text{Other} \\beta_\\text{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))
```

```{r tab_mse2_19, results='asis'}
mse2 %>% 
  filter(Y=="19") %>% select(!Y) %>%
  kbl(., align="lrlrrrrr",
    caption="MSE Summary Statistics of $\\beta_{19}$ by Model and Proportion of Validation Samples.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_\\text{Other} \\beta_\\text{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))
```

```{r tab_mse2_20, results='asis'}
mse2 %>% 
  filter(Y=="20") %>% select(!Y) %>%
  kbl(., align="lrlrrrrr",
    caption="MSE Summary Statistics of $\\beta_{20}$ by Model and Proportion of Validation Samples.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_\\text{Other} \\beta_\\text{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))
```

```{r tab_mse2_Other, results='asis'}
mse2 %>% 
  filter(Y=="Other") %>% select(!Y) %>%
  kbl(., align="lrlrrrrr",
    caption="MSE Summary Statistics of $\\beta_\\text{Other}$ by Model and Proportion of Validation Samples.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_\\text{Other} \\beta_\\text{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))
```


```{r tab_coverage1, results='asis'}
coverage1 <- regressions.averaged %>%
  mutate(statistic=coverage_mean) %>%
  group_by(Y, proportion, regression) %>%
  summarise(
    "Mean" = mean(statistic),
    "SD" = sd(statistic),
    "Median" = median(statistic),
    "5\\%" = quantile(statistic, probs[1]),
    "95\\%" = quantile(statistic, probs[2]),
    .groups = "drop") %>%
  rename(c(
    "Validation Proportion" = proportion,
    "Coverage" = regression)
    )
```


```{r tab_coverage1_3, results='asis'}
coverage1 %>% 
  filter(Y=="3") %>% select(!Y) %>%
  kbl(., align="rllrrrrr",
    caption="Coverage Summary Statistics of $\\beta_{3}$ by Proportion of Validation Samples.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_\\text{Other} \\beta_\\text{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))
```


```{r tab_coverage1_14, results='asis'}
coverage1 %>% 
  filter(Y=="14") %>% select(!Y) %>%
  kbl(., align="rllrrrrr",
    caption="Coverage Summary Statistics of $\\beta_{14}$ by Proportion of Validation Samples.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_\\text{Other} \\beta_\\text{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))
```


```{r tab_coverage1_15, results='asis'}
coverage1 %>% 
  filter(Y=="15") %>% select(!Y) %>%
  kbl(., align="rllrrrrr",
    caption="Coverage Summary Statistics of $\\beta_{15}$ by Proportion of Validation Samples.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_\\text{Other} \\beta_\\text{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))
```


```{r tab_coverage1_19, results='asis'}
coverage1 %>% 
  filter(Y=="19") %>% select(!Y) %>%
  kbl(., align="rllrrrrr",
    caption="Coverage Summary Statistics of $\\beta_{19}$ by Proportion of Validation Samples.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_\\text{Other} \\beta_\\text{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))
```


```{r tab_coverage1_20, results='asis'}
coverage1 %>% 
  filter(Y=="20") %>% select(!Y) %>%
  kbl(., align="rllrrrrr",
    caption="Coverage Summary Statistics of $\\beta_{20}$ by Proportion of Validation Samples.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_\\text{Other} \\beta_\\text{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))
```


```{r tab_coverage1_Other, results='asis'}
coverage1 %>% 
  filter(Y=="Other") %>% select(!Y) %>%
  kbl(., align="rllrrrrr",
    caption="Coverage Summary Statistics of $\\beta_\\text{Other}$ by Proportion of Validation Samples.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_\\text{Other} \\beta_\\text{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))
```

```{r tab_coverage2, results='asis'}
coverage2 <- regressions.averaged %>%
  mutate(statistic=coverage_mean) %>%
  group_by(Y, model, proportion, regression) %>%
  summarise(
    "Mean" = mean(statistic),
    "SD" = sd(statistic),
    "Median" = median(statistic),
    "5\\%" = quantile(statistic, probs[1]),
    "95\\%" = quantile(statistic, probs[2]),
    .groups = "drop") %>%
  rename(c(
    "Model" = model,
    "Validation Proportion" = proportion,
    "MSE" = regression
    ))
```

```{r tab_coverage2_3, results='asis'}
coverage2 %>% 
  filter(Y=="3") %>% select(!Y) %>%
  kbl(., align="lrlrrrrr",
    caption="Coverage Summary Statistics of $\\beta_{3}$ by Model and Proportion of Validation Samples.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_\\text{Other} \\beta_\\text{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))
```

```{r tab_coverage2_14, results='asis'}
coverage2 %>% 
  filter(Y=="14") %>% select(!Y) %>%
  kbl(., align="lrlrrrrr",
    caption="Coverage Summary Statistics of $\\beta_{14}$ by Model and Proportion of Validation Samples.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_\\text{Other} \\beta_\\text{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))
```

```{r tab_coverage2_15, results='asis'}
coverage2 %>% 
  filter(Y=="15") %>% select(!Y) %>%
  kbl(., align="lrlrrrrr",
    caption="Coverage Summary Statistics of $\\beta_{15}$ by Model and Proportion of Validation Samples.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_\\text{Other} \\beta_\\text{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))
```

```{r tab_coverage2_19, results='asis'}
coverage2 %>% 
  filter(Y=="19") %>% select(!Y) %>%
  kbl(., align="lrlrrrrr",
    caption="Coverage Summary Statistics of $\\beta_{19}$ by Model and Proportion of Validation Samples.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_\\text{Other} \\beta_\\text{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))
```

```{r tab_coverage2_20, results='asis'}
coverage2 %>% 
  filter(Y=="20") %>% select(!Y) %>%
  kbl(., align="lrlrrrrr",
    caption="Coverage Summary Statistics of $\\beta_{20}$ by Model and Proportion of Validation Samples.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_\\text{Other} \\beta_\\text{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))
```

```{r tab_coverage2_Other, results='asis'}
coverage2 %>% 
  filter(Y=="Other") %>% select(!Y) %>%
  kbl(., align="lrlrrrrr",
    caption="Coverage Summary Statistics of $\\beta_\\text{Other}$ by Model and Proportion of Validation Samples.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_\\text{Other} \\beta_\\text{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))
```

