---
title: "Pre-Simulation"
output: html_document
date: "Aug 13, 2024"
---

```{r, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo=TRUE)

# Set the working directory 
repo_dir <- "/Users/haya1/Documents/LanguageModel_Labels/congressional_bills"
knitr::opts_knit$set(root.dir=repo_dir)
setwd(repo_dir)

require(dplyr)
require(ggplot2)
```

# Overview

This notebook generates the `combinations_lhs.csv` and `combinations_rhs.csv` files, which are then used in the simulation R scripts.

# Create `combinations_lhs.csv`

```{r}
simulation_dir <- file.path(repo_dir, "04_simulation/lhs/bayesian")
dir.create(simulation_dir, showWarnings=FALSE)

# Run 1: Generate the first set of combinations
combinations <- expand.grid(
  train_proportion = c(0.05, 0.1, 0.25, 0.5), # Proportions for training data: 5%, 10%, 25%, 50%
  prompt = 1:12, # List of prompt IDs
  model = c("gpt-3.5-turbo-0125", "gpt-4o"), # Model types
  variable = c("Senate", "Democrat", "DW1"), # Independent variables of interest
  major_topic = c(3, 14, 15, 19, 20), # Dependent variables of interest. These are the most common major topics based on Major/Yhuman column.
  stringsAsFactors = FALSE) %>%
  mutate(
    combination_id = 1:n(), # Assign a unique ID to each combination; used as seed for reproducibility
    N = 1000, # Number of simulations per a single combination
    B = 1000, # Number of bootstrap samples
    n_samples = 5000 # Number of samples drawn from 10K bill in each of the N simulations
  ) %>% relocate(combination_id) # Move combination_id to the first column

# Save the merged combinations to a csv file
write.csv(combinations, file.path(simulation_dir, "combinations_lhs.csv"), row.names=FALSE)
```

# Create `combinations_rhs.csv`

```{r}
simulation_dir <- file.path(repo_dir, "04_simulation/rhs/bayesian")
dir.create(simulation_dir, showWarnings=FALSE)

# Generate the first set of combinations
combinations <- expand.grid(
  train_proportion = c(0.05, 0.1, 0.25, 0.5), # Proportions for training data: 5%, 10%, 25%, 50%. 
  prompt = 1:12, # List of prompt IDs
  model = c("gpt-3.5-turbo-0125", "gpt-4o"), # Model types
  variable = c("Senate", "Democrat", "DW1"), # Independent variables of interest
  stringsAsFactors = FALSE) %>%
  mutate(
    combination_id = 1:n(), # Assign a unique ID to each combination; used as seed for reproducibility
    N = 1000, # Number of simulations per a single combination
    B = 1000, # Number of bootstrap samples
    n_samples = 5000 # Number of samples drawn from 10K bill in each of the N simulations
  ) %>% relocate(combination_id) # Move combination_id to the first column

# Save the merged combinations to a csv file
write.csv(combinations, file.path(simulation_dir, "combinations_rhs.csv"), row.names=FALSE)
```
