---
title: "Simulations"
date: "July 24, 2024"
output: html_document
---

This code is based on https://github.com/asheshrambachan/LanguageModel_Labels/blob/main/egami_et_al/code/LLM_errors.R

```{r setup, warning=FALSE, message=FALSE}
repo_dir = "/Users/haya1/Documents/LanguageModel_Labels/congressional_bills"
simulation_dir = file.path(repo_dir, "04_simulation")
knitr::opts_knit$set(root.dir = simulation_dir)
setwd(simulation_dir)

require(dplyr)
require(sandwich)
require(lmtest)
require(furrr)
library(progressr)

data = read.csv(file.path(repo_dir, "02_llm/bills_prompts_responses_10000.csv")) %>% 
  # select(
  #   Model, PromptingStrategyID, PromptingStrategyName,
  #   BillID, Description,
  #   Chamber, Party, Year, Cong, Postal, State, DW1, Major, MajorText, 
  #   MajorLLM, MajorTextLLM, ConfidenceLLM, ExplanationLLM  # TODO: ConfidenceLLM is not used at the moment
  #   ) %>%
  mutate(
    Senate = as.integer(Chamber == "Senate"),
    Democrat = as.integer(Party == "Democrat"),
    Prompt = PromptingStrategyID) %>% 
  select(Model, Prompt, Senate, Democrat, DW1, Major, MajorLLM) 

if (any(is.na(data)))
  warning("data contains NA")
```


## Functions

```{r}
get_se_robust = function(model){
  model_output = coeftest(model, vcov=vcovHC(model, type = "HC1"))
  return(model_output[,"Std. Error"])
}

get_ci_robust = function(model, alpha=0.05, use_z_score=TRUE){
  if (use_z_score){
    z_score = qnorm(1 - alpha/2)
    se_robust = get_se_robust(model)
    ci = cbind(coef(model) - z_score * se_robust, coef(model) + z_score * se_robust)
    colnames(ci) = c("2.5%", "97.5%")
  }
  else{ # t-score
    ci = coefci(model, level=1-alpha, vcov=vcovHC(model, type = "HC1"))
  }
  return(ci)
}

get_se_boot = function(samples_boot) apply(samples_boot, 2, sd)

get_ci_boot = function(samples_boot, alpha=0.05, method="percentile") {
  if (method!="percentile")
    stop("Only percentile method is implemented")
  
  probs = c(alpha/2, 1-alpha/2)
  ci_transposed = apply(samples_boot, 2, function(x){ 
    quantile(x, probs=probs)
    })
  ci = t(ci_transposed)
  
  return(ci)
}
```

```{r}
get_beta_debiased = function(train, test, variable){
  # estimate error using train data
  train$error = train$Y_human - train$Y_llm
  model_error = lm(formula=paste("error", "~", variable), data=train)
  
  # compute Y_debiased for the test data, regress Y_debiased ~ Xvar on the test data
  test$error = predict(model_error, newdata=test) # predict error for test data
  test$Y_debiased = test$Y_llm + test$error
  model_debiased = lm(formula=paste("Y_debiased", "~", variable), data=test) 
  return(coef(model_debiased))
}

outer_loop_function = function(data, combination, N, B, n_samples){
  major_topic = combination$major_topic
  variable = combination$variable
  model = combination$model 
  prompt = combination$prompt
  train_proportion = combination$train_proportion
  
  data = data %>% 
    filter(Model==model, 
           Prompt==prompt) %>%
    mutate(Y_human = as.integer(Major == major_topic),
           Y_llm = as.integer(MajorLLM == major_topic))
  
  # Using human-labeled major_topic topics on all 10K bills
  model_human = lm(formula=paste("Y_human", "~", variable), data=data)
  human.coef = coef(model_human)
  human.se = get_se_robust(model_human)
  human.lci = get_ci_robust(model_human, alpha=0.05, use_z_score=TRUE)[,1] # lower ci
  human.uci = get_ci_robust(model_human, alpha=0.05, use_z_score=TRUE)[,2] # upper ci
  
  names_betas = c("beta0", "beta1") # names(coef(human.coef))
  n_betas = length(names_betas)
  betas = list(
    "major_topic"      = major_topic, # matrix(data=major_topic, nrow=N, ncol=1),
    "variable"         = variable, # matrix(data=variable, nrow=N, ncol=1),
    "model"            = model, # matrix(data=model, nrow=N, ncol=1),
    "prompt"           = prompt, # matrix(data=prompt, nrow=N, ncol=1),
    "train_proportion" = train_proportion, # matrix(data=train_proportion, nrow=N, ncol=1),
    "sim_number" = 1:N,
    "human" = list(
      "coef" = matrix(data=human.coef, nrow=N, ncol=n_betas, dimnames=list(NULL, names_betas), byrow = TRUE),
      "se"   = matrix(data=human.se,   nrow=N, ncol=n_betas, dimnames=list(NULL, names_betas), byrow = TRUE),
      "lci"  = matrix(data=human.lci,  nrow=N, ncol=n_betas, dimnames=list(NULL, names_betas), byrow = TRUE),
      "uci"  = matrix(data=human.uci,  nrow=N, ncol=n_betas, dimnames=list(NULL, names_betas), byrow = TRUE)),
    "llm" = list(
      "coef" = matrix(nrow=N, ncol=n_betas, dimnames=list(NULL, names_betas)),
      "se"   = matrix(nrow=N, ncol=n_betas, dimnames=list(NULL, names_betas)),
      "lci"  = matrix(nrow=N, ncol=n_betas, dimnames=list(NULL, names_betas)),
      "uci"  = matrix(nrow=N, ncol=n_betas, dimnames=list(NULL, names_betas))),
    "human_train" = list(
      "coef" = matrix(nrow=N, ncol=n_betas, dimnames=list(NULL, names_betas)),
      "se"   = matrix(nrow=N, ncol=n_betas, dimnames=list(NULL, names_betas)),
      "lci"  = matrix(nrow=N, ncol=n_betas, dimnames=list(NULL, names_betas)),
      "uci"  = matrix(nrow=N, ncol=n_betas, dimnames=list(NULL, names_betas))),
    "error" = list(
      "coef" = matrix(nrow=N, ncol=n_betas, dimnames=list(NULL, names_betas)),
      "se"   = matrix(nrow=N, ncol=n_betas, dimnames=list(NULL, names_betas)),
      "lci"  = matrix(nrow=N, ncol=n_betas, dimnames=list(NULL, names_betas)),
      "uci"  = matrix(nrow=N, ncol=n_betas, dimnames=list(NULL, names_betas))),
    "debiased" = list(
      "coef" = matrix(nrow=N, ncol=n_betas, dimnames=list(NULL, names_betas)),
      "se"   = matrix(nrow=N, ncol=n_betas, dimnames=list(NULL, names_betas)),
      "lci"  = matrix(nrow=N, ncol=n_betas, dimnames=list(NULL, names_betas)),
      "uci"  = matrix(nrow=N, ncol=n_betas, dimnames=list(NULL, names_betas)))
  )
  
  for (i in (1:N)){ # outer loop
    # We randomly draw 5000 observations with replacement.
    data_sample = data[sample(x=nrow(data), size=n_samples, replace=TRUE) ,]
    
    # On the 5000 observations, we calculate model_llm
    model_llm = lm(formula=paste("Y_llm", "~", variable), data=data_sample) 
    betas$llm$coef[i,] = coef(model_llm)
    betas$llm$se[i,] = get_se_robust(model_llm)
    betas$llm$lci[i,] = get_ci_robust(model_llm, alpha=0.05, use_z_score=TRUE)[,1] # lower ci
    betas$llm$uci[i,] = get_ci_robust(model_llm, alpha=0.05, use_z_score=TRUE)[,2] # upper ci
    
    # On the 5000 observations, we split the data into a train/test split. Since it's already a random sample, we don't do it using the sample function
    train_idx = 1:(nrow(data_sample) * train_proportion) # sample(x=nrow(data_sample), size=nrow(data_sample) * train_proportion, replace=FALSE)
    train = data_sample[train_idx, ]
    test = data_sample[-train_idx, ]
    
    # Using the train/test split, we calculate 
    # (i) model_human_train using only train. We calculate the se of model_human_train using heteroskedasticity robust standard errors.
    model_human_train = lm(formula=paste("Y_human", "~", variable), data=train) # TODO: keep coef, se (robust), ci (z_score)
    betas$human_train$coef[i,] = coef(model_human_train)
    betas$human_train$se[i,] = get_se_robust(model_human_train)
    betas$human_train$lci[i,] = get_ci_robust(model_human_train, alpha=0.05, use_z_score=TRUE)[,1] # lower ci
    betas$human_train$uci[i,] = get_ci_robust(model_human_train, alpha=0.05, use_z_score=TRUE)[,2] # upper ci
    
    # (ii) estimate error from train data
    # TODO: verify that error should also use robust
    train$error = train$Y_human - train$Y_llm
    model_error = lm(formula=paste("error", "~", variable), data=train)
    betas$error$coef[i,] = coef(model_error)
    betas$error$se[i,] = get_se_robust(model_error)
    betas$error$lci[i,] = get_ci_robust(model_error, alpha=0.05, use_z_score=TRUE)[,1] # lower ci
    betas$error$uci[i,] = get_ci_robust(model_error, alpha=0.05, use_z_score=TRUE)[,2] # upper ci
    
    # (iii) corrected error, and estimate debiased model
    betas$debiased$coef[i,] = get_beta_debiased(train=train, test=test, variable=variable)
    
    # We then begin the bootstrap (inner loop), this is beacuse beta_debiased is a function of a predicted Y_debiased and so we can't use se and ci from the lm model.
    debiased_coef_boot = as.data.frame(t(sapply(
      1:B, 
      function(b){ # ignore b
        # We draw a bootstrap sample from each of the train and test data, keeping the train-test split fixed
        train_boot = train[sample(x=nrow(train), replace=TRUE), ]
        test_boot = test[sample(x=nrow(test), replace=TRUE), ]
        
        # Calculate the coef of the debiased model
        coef_boot = get_beta_debiased(train=train_boot, test=test_boot, variable=variable)
        return(coef_boot)
      }
    )))
    
    # We use bootstrap samples to calculate se and confidence intervals for corrected_beta.
    betas$debiased$se[i,] = get_se_boot(debiased_coef_boot)
    betas$debiased$lci[i,] = get_ci_boot(debiased_coef_boot, alpha=0.05, method="percentile")[,1] # lower ci
    betas$debiased$uci[i,] = get_ci_boot(debiased_coef_boot, alpha=0.05, method="percentile")[,2] # upper ci
  }
  
  return(as.data.frame(betas))
}

```

## Models

```{r}
combinations = expand.grid(
  train_proportion = c(0.1, 0.2, 0.3, 0.4, 0.5), # 10%train 90%test, ...
  prompt = unique(data$Prompt),
  model = unique(data$Model),
  variable = c("Senate", "Democrat", "DW1"),
  major_topic = sort(unique(data$Major))[1:2],
  stringsAsFactors = FALSE
  )
```

```{r}
n_cores = parallelly::availableCores()
plan(multisession, workers = n_cores) # or simply use: plan(multisession)
```

```{r}
# start.time = Sys.time()

N = 10
B = 10
n_samples = 5000

set.seed(123)
with_progress({
  p <- progressor(along = 1:nrow(combinations))

  betas_list = future_map(
    .options = furrr_options(seed=TRUE), # instead of using a new seed for each run, it's enough to use set.seed(123), and enable random seeding here
    .x = 1:nrow(combinations),
    .f = function(x) {
      betas = outer_loop_function(
        data=data, 
        combination=combinations[x,],
        N=N,
        B=B,
        n_samples=n_samples
        )
      p(sprintf("combination = %g", x))
      return(betas)
    })
})

# end.time <- Sys.time()
# print(end.time - start.time)
```


```{r}
plan(sequential)

betas_df = bind_rows(betas_list)
filename = paste("simulations_N", N, "_B", B, ".csv", sep = "")
write.csv(betas_df, file.path(simulation_dir, filename), row.names = FALSE)
```

```{r}
# ~1.5 - 2 secs/combination for N=1 B=1000 > 
# (1.8*1000)/60/60 = 0.5 hrs/combination, N=1000 B=1000
```
