---
title: "bias Estimattion"
date: "July 24, 2024"
output: html_document
---

This code is based on https://github.com/asheshrambachan/LanguageModel_Labels/blob/main/egami_et_al/code/LLM_errors.R

```{r setup, warning=FALSE, message=FALSE}
repo_dir = "/Users/haya1/Documents/LanguageModel_Labels/congressional_bills"
simulation_dir = file.path(repo_dir, "04_simulation")
knitr::opts_knit$set(root.dir = simulation_dir)
setwd(simulation_dir)

require(dplyr)
require(nnet)
require(stargazer)
require(sandwich)
require(ggplot2)
require(gridExtra)

rdata_dir = file.path(simulation_dir, "rds")
dir.create(rdata_dir, showWarnings=FALSE)

figures_dir = file.path(simulation_dir, "figures")
dir.create(figures_dir, showWarnings=FALSE)

data = read.csv(file.path(repo_dir, "02_llm/bills_prompts_responses_10000.csv"))

data = data %>% select(
    Model, PromptingStrategyID, PromptingStrategyName,
    BillID, Description,
    Chamber, Party, Year, Cong, Postal, State, DW1, Major, MajorText, 
    MajorLLM, MajorTextLLM, ConfidenceLLM, ExplanationLLM  # TODO: ConfidenceLLM is not used at the moment
    ) 

if (any(is.na(data)))
  warning("data contains NA")

```

## Functions

```{r}
get_model_debiased = function(data, variable, train_test_split){
  # split data into train/test set
  # split 5K, 50% train, 50% test, use the 2.5K for the estimate 
  n_train = nrow(data)*train_test_split
  train_idx = sample(x=nrow(data), size=n_train)
  train = data[train_idx, ]
  test = data[-train_idx, ]
  
  # estimate bias using train data
  train$bias = train$Y_human - train$Y_llm
  model_bias = lm(formula=paste("bias", "~", variable), data=train)
  
  # compute Y_debiased for the test data
  test$bias_hat = predict(model_bias, newdata=test)
  test$Y_debiased = test$Y_llm + test$bias_hat
  
  # regress Y_debiased ~ variable on the test data
  model_debiased = lm(formula=paste("Y_debiased", "~", variable), data=test) 
  
  return(list(
    "model_bias"=model_bias, 
    "model_debiased"=model_debiased
    ))
}

get_beta_debiased = function(data, variable, train_test_split){
  models = get_model_debiased(data, variable, train_test_split)
  return(list(
    "beta_error"=coef(models$model_bias), 
    "beta_debiased"=coef(models$model_debiased)
    ))
}

draw_bootstrap_samples = function(data, B, func, ... ){
  # Source: Efron
  out_template = func(data, ... ) # get output dim
  if (typeof(out_template)!="list"){
    stop("Current implementation requires the function return to be a list")
  }
  n_lists = length(out_template)
  lists = vector(mode="list", length=n_lists)
  names(lists) = names(out_template)
  for (n in 1:n_lists){
    lists[[n]] = matrix(nrow=B, ncol=length(out_template[[n]]))
    colnames(lists[[n]]) = names(out_template[[n]])
  }
  samples_boot = vector(mode="list", length=B)
  for (b in 1:B){
    idx_boot = sample(nrow(data), replace=TRUE)
    out = func(data=data[idx_boot, ], ... ) 
    for (n in 1:n_lists)
      lists[[n]][b,] = out[[n]]
  }
  return(lists)
}

get_se_robust = function(model){
  model_output = coeftest(model, vcov=vcovHC(model, type = "HC1"))
  return(model_output[,"Std. Error"])
}

get_ci_robust = function(model, alpha=0.05, use_t_score=FALSE){
  if (use_t_score){
    ci = coefci(model, level=1-alpha, vcov=vcovHC(model, type = "HC1"))
  }
  else{ 
    z_score = qnorm(1 - alpha/2)
    se_robust = get_se_robust(model)
    ci = cbind(coef(model) - z_score * se_robust, coef(model) + z_score * se_robust)
    colnames(ci) = c("2.5%", "97.5%")
  }
  return(ci)
}

get_se_boot = function(samples_boot) apply(samples_boot, 2, sd)

get_ci_boot = function(samples_boot, alpha=0.05, method="percentile") {
  probs = c(alpha/2, 1-alpha/2)
  if (method=="percentile"){
    ci_transposed = apply(samples_boot, 2, function(x){ 
      quantile(x, probs=probs)
      })
    ci = t(ci_transposed)
  }
  else {
    stop("Only percentile method is implemented")
  }
  return(ci)
}
```

## Models

For each model and each prompt modification, we perform the following:

$$X_i \in \{\text{Senate}_i, \text{Democrat}_i, \text{DW1}_i\}$$
$$ Y_i^\text{human} = 1\{ \text{Y}_i = \text{major_topic}\}$$

$$ Y_i^\text{naive} = 1\{ \text{Y_llm}_i = k\}$$

$$ Y_i^\text{debiased} = Y_i^\text{naive} + \widehat{\text{bias}_i}$$

where the bias is estimated by fitting this model using the training data: 
$$\text{bias}_i =  Y_i^\text{human} - Y_i^\text{naive} = \beta_0^\text{bias} + \beta_1^\text{bias} X_i^\text{5K sample, 50% train}$$

We then fit a model (currently using test data):

$$Y^\text{human} = \beta_0^\text{human} + \beta_1^\text{human} variable^\text{all} + \epsilon^\text{human}$$

$$Y^\text{naive} = \beta_0^\text{naive} + \beta_1^\text{naive} variable^\text{5K sample}  + \epsilon^\text{naive}$$

$$Y^\text{debiased} = \beta_0^\text{debiased} + \beta_1^\text{debiased} variable^\text{5K sample, 50% test} + \epsilon^\text{debiased}$$


```{r}
start.time = Sys.time()

set.seed(123)
major_topic = 1 # TODO: I currently do it for the first major_topic topic only

N = 1 # 5000
B = 1000 #1000 # of bootstrap samples
n_samples = 5000 # for naive
train_test_split = 0.5 # 50% of n_sample for train and 50% for test for debiased

for (variable in c("Senate", "Democrat", "DW1")){
  for (model in c("gpt-3.5-turbo-0125", "gpt-4o")){
    for (prompt in (1:12)){
      data_filtered = data %>%
        mutate(
          Prompt = PromptingStrategyID,
          Senate = as.integer(Chamber == "Senate"),
          Democrat = as.integer(Party == "Democrat"),
          Y_human = as.integer(Major == major_topic),
          Y_llm = as.integer(MajorLLM == major_topic)) %>% 
        select(Model, Prompt, Senate, Democrat, DW1, Y_human, Y_llm) %>% 
        filter(Model==model, Prompt==prompt)
      
      # Using human-labeled major_topic topics on all 10K bills
      model_human = lm(formula=paste("Y_human", "~", variable), data=data_filtered)
      beta_human = coef(model_human)
      beta_human_se = get_se_robust(model_human)
      beta_ci = get_ci_robust(model_human, alpha=0.05, use_t_score=FALSE)
      beta_human_lci = beta_ci[,1] # lower ci
      beta_human_uci = beta_ci[,2] # upper ci
      
      # Using naive LLM-labeled and bias-corrected LLM-labeled major_topic topics
      names_betas = names(beta_human)
      n_betas = length(beta_human)
      
      beta_llm = matrix(nrow=N, ncol=n_betas, dimnames=list(NULL, names_betas))
      beta_llm_se = matrix(nrow=N, ncol=n_betas, dimnames=list(NULL, names_betas))
      beta_llm_lci = matrix(nrow=N, ncol=n_betas, dimnames=list(NULL, names_betas))
      beta_llm_uci = matrix(nrow=N, ncol=n_betas, dimnames=list(NULL, names_betas))
      
      beta_debiased = matrix(nrow=N, ncol=n_betas, dimnames=list(NULL, names_betas))
      beta_debiased_se = matrix(nrow=N, ncol=n_betas, dimnames=list(NULL, names_betas))
      beta_debiased_lci = matrix(nrow=N, ncol=n_betas, dimnames=list(NULL, names_betas))
      beta_debiased_uci = matrix(nrow=N, ncol=n_betas, dimnames=list(NULL, names_betas))
      
      beta_error = matrix(nrow=N, ncol=n_betas, dimnames=list(NULL, names_betas))
      beta_error_se = matrix(nrow=N, ncol=n_betas, dimnames=list(NULL, names_betas))
      beta_error_lci = matrix(nrow=N, ncol=n_betas, dimnames=list(NULL, names_betas))
      beta_error_uci = matrix(nrow=N, ncol=n_betas, dimnames=list(NULL, names_betas))
      
      for (i in (1:N)){
        # sample 5K first
        sample_idx = sample(x=nrow(data_filtered), size=n_samples)
        data_filtered_sample = data_filtered[sample_idx,]
          
        model_naive = lm(formula=paste("Y_llm", "~", variable), data=data_filtered_sample) 
        beta_llm[i,] = coef(model_naive)
        beta_llm_se[i,] = get_se_robust(model_naive)
        beta_llm_ci = get_ci_robust(model_naive, alpha=0.05, use_t_score=FALSE)
        beta_llm_lci[i,] = beta_llm_ci[,1] # lower ci
        beta_llm_uci[i,] = beta_llm_ci[,2] # upper ci
        
        out = get_beta_debiased(data_filtered_sample, variable, train_test_split) 
        beta_debiased[i,] = out$beta_debiased
        beta_error[i,] = out$beta_error
        
        out_boot = draw_bootstrap_samples(
          data=data_filtered_sample, B=B, func=get_beta_debiased, variable=variable, 
          train_test_split=train_test_split)
        beta_debiased_boot = out_boot$beta_debiased
        beta_debiased_se[i,] = get_se_boot(beta_debiased_boot)
        beta_debiased_ci = get_ci_boot(beta_debiased_boot, alpha=0.05, method="percentile")
        beta_debiased_lci[i,] = beta_debiased_ci[,1] # lower ci
        beta_debiased_uci[i,] = beta_debiased_ci[,2] # upper ci
        
        beta_error_boot = out_boot$beta_error
        beta_error_se[i,] = get_se_boot(beta_error_boot)
        beta_error_ci = get_ci_boot(beta_error_boot, alpha=0.05, method="percentile")
        beta_error_lci[i,] = beta_error_ci[,1] # lower ci
        beta_error_uci[i,] = beta_error_ci[,2] # upper ci
      }
      
      out = list(
        "model"=model,
        "prompt"=prompt,
        "major_topic"=major_topic,
        "variable"=variable,
        "beta_human"=beta_human,
        "beta_human_se"  =beta_human_se,
        "beta_human_lci" =beta_human_lci,
        "beta_human_uci" =beta_human_uci,
        "beta_llm"=beta_llm,
        "beta_llm_se"  =beta_llm_se,
        "beta_llm_lci" =beta_llm_lci,
        "beta_llm_uci" =beta_llm_uci,
        "beta_error"=beta_llm,
        "beta_error_se"  =beta_error_se,
        "beta_error_lci" =beta_error_lci,
        "beta_error_uci" =beta_error_uci,
        "beta_debiased"=beta_debiased,
        "beta_debiased_se"  =beta_debiased_se,
        "beta_debiased_lci" =beta_debiased_lci,
        "beta_debiased_uci" =beta_debiased_uci
      )
      
      filename = paste0(c("major_topic", major_topic, "_", model, "_prompt", prompt, "_", variable),
        collapse="")
      saveRDS(out, file=file.path(rdata_dir, paste0(c(filename, ".rds"), collapse="")) )
      print(sprintf("saved %s", filename))
      
      # colors = c("beta_human"="black","beta_llm" = "#1f77b4", "beta_debiased" = "#ff7f0e")
      # p1 = ggplot() + 
      #   geom_vline(aes(xintercept=beta_human[1], color="beta_human"), linetype = "dashed") +
      #   geom_density(aes(x=beta_llm[,1], color="beta_llm")) +
      #   geom_density(aes(x=beta_debiased[,1], color="beta_debiased")) +
      #   labs(title = paste("Density Plot for",names(beta_human[1])),
      #        x = names(beta_human[1]),
      #        y = "Density") +
      #   scale_color_manual(name="", values=colors, breaks=names(colors)) +
      #   theme_bw() +
      #   theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
      #   theme(legend.position = "bottom")
      # 
      # p2 = ggplot() + 
      #   geom_vline(aes(xintercept=beta_human[2], color="beta_human"), linetype = "dashed") +
      #   geom_density(aes(x=beta_llm[,2], color="beta_llm")) +
      #   geom_density(aes(x=beta_debiased[,2], color="beta_debiased")) +
      #   labs(title = paste("Density Plot for",names(beta_human[2])),
      #        x = names(beta_human[2]),
      #        y = "Density") +
      #   scale_color_manual(name="", values=colors, breaks=names(colors)) +
      #   theme_bw() +
      #   theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
      #   theme(legend.position = "bottom")
      # 
      # # Arrange plots side by side
      # p = arrangeGrob(p1, p2, ncol=2) 
      # ggsave(file=file.path(figures_dir, paste0(c(filename,".pdf"), collapse="")), plot=p, width=8, height=4)
    }
  }
}

end.time <- Sys.time()
print(round(end.time - start.time,2))

```

```{r}
# [1] "saved major_topic1_gpt-3.5-turbo-0125_prompt1_Senate"
# Time difference of 2.66 secs (N=1, B=1000)
# 2.66*1000/60/60
# 0.7388889 hours to complete (N=1000, B=1000)
```

```{r}
# i = 6 # nrow(beta_llm)
# stargazer(
#   model_human, model_naive_last, model_debiased_last, # this is used to create the table template. Do not use the stats returned by models ending with _last.
#   coef = list(beta_human, beta_llm[i,], beta_debiased[i,]),
#   se = list(beta_human_se, beta_llm_se[i,], beta_debiased_se[i,]), 
#   p.auto=TRUE, # TODO: Verify that p values and * align with the used coef and not based on the templates
#   ci.custom = list(
#     matrix(c(beta_human_lci, beta_human_uci), ncol=2),
#     matrix(c(beta_llm_lci[i,], beta_llm_uci[i,]), ncol=2),
#     matrix(c(beta_debiased_lci[i,], beta_debiased_uci[i,]), ncol=2)
#     ),
#   keep.stat = c("n"), # TODO: verify what to use for number of observations for Y_llm and Y_debiased
#   type = "text"
# )
```
