---
title: "bias Estimattion"
date: July 24, 2024
output: html_document
---

This code is based on https://github.com/asheshrambachan/LanguageModel_Labels/blob/main/egami_et_al/code/LLM_errors.R

```{r setup, warning=FALSE, message=FALSE}
repo_dir = "/Users/haya1/Documents/LanguageModel_Labels/congressional_bills"
knitr::opts_knit$set(root.dir = repo_dir)
setwd(repo_dir)

require(dplyr)
require(nnet)
require(stargazer)
require(sandwich)
require(ggplot2)
require(gridExtra)

rdata_dir = file.path(repo_dir, "04_bias/rds")
dir.create(rdata_dir, showWarnings=FALSE)

figures_dir = file.path(repo_dir, "04_bias/figures")
dir.create(figures_dir, showWarnings=FALSE)

data = read.csv(file.path(repo_dir, "02_llm/bills_prompts_responses_10000.csv"))

data = data %>% select(
    Model, PromptingStrategyID, PromptingStrategyName,
    BillID, Description,
    Chamber, Party, Year, Cong, Postal, State, DW1, Major, MajorText, 
    MajorLLM, MajorTextLLM, ConfidenceLLM, ExplanationLLM  # TODO: ConfidenceLLM is not used at the moment
    ) 

if (any(is.na(data)))
  warning("data contains NA")

```

## Functions

```{r}
get_model_debiased = function(data, X, test_train_split, return_bias=TRUE){
  # split data into train/test set
  # split 5K, 50% train, 50% test, use the 2.5K for the estimate 
  n_train = nrow(data)*test_train_split
  train_idx = sample(x=nrow(data), size=n_train)
  train = data[train_idx, ]
  test = data[-train_idx, ]
  
  # estimate bias using train data
  train$bias = train$Y_human - train$Y_naive
  model_bias = lm(formula=paste("bias", "~", X), data=train)
  
  # compute Y_debiased for the test data
  test$bias_hat = predict(model_bias, newdata=test)
  test$Y_debiased = test$Y_naive + test$bias_hat
  
  # regress Y_debiased ~ X on the test data
  model_debiased = lm(formula=paste("Y_debiased", "~", X), data=test) 
  
  if (return_bias)
    return(list(
      "model_bias"=model_bias, 
      "model_debiased"=model_debiased
      ))
  else
    return(list(
      "model_debiased"=model_debiased
      ))
}

get_model_debiased_coef = function(data, X, test_train_split, return_bias=TRUE){
  models = get_model_debiased(data, X, test_train_split, return_bias)
  if (return_bias)
    return(list(
      "model_bias_coef"=coef(models$model_bias), 
      "model_debiased_coef"=coef(models$model_debiased)
      ))
  else
    return(list(
      "model_debiased_coef"=coef(models$model_debiased)
      ))
}

draw_bootstrap_samples = function(data, B, func, ... ){
  # Source: Efron
  out_template = func(data, ... ) # get output dim
  if (typeof(out_template)!="list"){
    stop("Current implementation requires the function return to be a list")
  }
  n_lists = length(out_template)
  lists = vector(mode="list", length=n_lists)
  names(lists) = names(out_template)
  for (n in 1:n_lists){
    lists[[n]] = matrix(nrow=B, ncol=length(out_template[[n]]))
    colnames(lists[[n]]) = names(out_template[[n]])
  }
  samples_boot = vector(mode="list", length=B)
  for (b in 1:B){
    idx_boot = sample(nrow(data), replace=TRUE)
    out = func(data=data[idx_boot, ], ... ) 
    for (n in 1:n_lists)
      lists[[n]][b,] = out[[n]]
  }
  return(lists)
}

get_se_robust = function(model){
  model_output = coeftest(model, vcov=vcovHC(model, type = "HC1"))
  return(model_output[,"Std. Error"])
}

get_ci_robust = function(model, alpha=0.05, use_t_score=FALSE){
  if (use_t_score){
    ci = coefci(model, level=1-alpha, vcov=vcovHC(model, type = "HC1"))
  }
  else{ 
    z_score = qnorm(1 - alpha/2)
    se_robust = get_se_robust(model)
    ci = cbind(coef(model) - z_score * se_robust, coef(model) + z_score * se_robust)
    colnames(ci) = c("2.5%", "97.5%")
  }
  return(ci)
}

get_se_boot = function(samples_boot) apply(samples_boot, 2, sd)

get_ci_boot = function(samples_boot, alpha=0.05, method="percentile") {
  probs = c(alpha/2, 1-alpha/2)
  if (method=="percentile"){
    ci_transposed = apply(samples_boot, 2, function(x){ 
      quantile(x, probs=probs)
      })
    ci = t(ci_transposed)
  }
  else {
    stop("Only percentile method is implemented")
  }
  return(ci)
}
```

## Models

For each model and each prompt modification, we perform the following:

$$X_i \in \{\text{Senate}_i, \text{Democrat}_i, \text{DW1}_i\}$$
$$ Y_i^\text{human} = 1\{ \text{Y_human}_i = \text{major}\}$$

$$ Y_i^\text{naive} = 1\{ \text{Y_naive}_i = k\}$$

$$ Y_i^\text{debiased} = Y_i^\text{naive} + \widehat{\text{bias}_i}$$

where the bias is estimated by fitting this model using the training data: 
$$\text{bias}_i =  Y_i^\text{human} - Y_i^\text{naive} = \beta_0^\text{bias} + \beta_1^\text{bias} X_i^\text{5K sample, 50% train}$$

We then fit a model (currently using test data):

$$Y^\text{human} = \beta_0^\text{human} + \beta_1^\text{human} X^\text{all} + \epsilon^\text{human}$$

$$Y^\text{naive} = \beta_0^\text{naive} + \beta_1^\text{naive} X^\text{5K sample}  + \epsilon^\text{naive}$$

$$Y^\text{debiased} = \beta_0^\text{debiased} + \beta_1^\text{debiased} X^\text{5K sample, 50% test} + \epsilon^\text{debiased}$$


```{r}
set.seed(123)
major = 1 # TODO: I currently do it for the first major topic only

iter_outter = 200
B = 200 # of bootstrap samples
n_samples = 5000 # for naive
test_train_split = 0.5 # 50% of n_sample for train and 50% for test for debiased
return_bias = TRUE

for (model in c("gpt-3.5-turbo-0125", "gpt-4o")){
  for (prompt_mod_id in (1:12)){
    for (X in c("Senate", "Democrat", "DW1")){
      data_filtered = data %>%
        mutate(
          Senate = as.integer(Chamber == "Senate"),
          Democrat = as.integer(Party == "Democrat"),
          Y_human = as.integer(Major == major),
          Y_naive = as.integer(MajorLLM == major)) %>% 
        select(
          Model, PromptingStrategyID, PromptingStrategyName,
          BillID, Description,
          Senate, Democrat, DW1, Y_human, Y_naive) %>% 
        filter(
          Model==model, 
          PromptingStrategyID==prompt_mod_id)
      
      # Using human-labeled major topics on all 10K bills
      model_human = lm(formula=paste("Y_human", "~", X), data=data_filtered)
      model_human_coef = coef(model_human)
      model_human_se = get_se_robust(model_human)
      model_human_ci = get_ci_robust(model_human, alpha=0.05, use_t_score=FALSE)
      model_human_lci = model_human_ci[,1] # lower ci
      model_human_uci = model_human_ci[,2] # upper ci
      rm(model_human_ci)
      
      # Using naive LLM-labeled and bias-corrected LLM-labeled major topics
      names_betas = names(model_human_coef)
      n_betas = length(model_human_coef)
      
      model_naive_coef = matrix(nrow=iter_outter, ncol=n_betas, dimnames=list(NULL, names_betas))
      model_naive_se = matrix(nrow=iter_outter, ncol=n_betas, dimnames=list(NULL, names_betas))
      model_naive_lci = matrix(nrow=iter_outter, ncol=n_betas, dimnames=list(NULL, names_betas))
      model_naive_uci = matrix(nrow=iter_outter, ncol=n_betas, dimnames=list(NULL, names_betas))
      
      model_debiased_coef = matrix(nrow=iter_outter, ncol=n_betas, dimnames=list(NULL, names_betas))
      model_debiased_se = matrix(nrow=iter_outter, ncol=n_betas, dimnames=list(NULL, names_betas))
      model_debiased_lci = matrix(nrow=iter_outter, ncol=n_betas, dimnames=list(NULL, names_betas))
      model_debiased_uci = matrix(nrow=iter_outter, ncol=n_betas, dimnames=list(NULL, names_betas))
      
      if (return_bias){
        model_bias_coef = matrix(nrow=iter_outter, ncol=n_betas, dimnames=list(NULL, names_betas))
        model_bias_se = matrix(nrow=iter_outter, ncol=n_betas, dimnames=list(NULL, names_betas))
        model_bias_lci = matrix(nrow=iter_outter, ncol=n_betas, dimnames=list(NULL, names_betas))
        model_bias_uci = matrix(nrow=iter_outter, ncol=n_betas, dimnames=list(NULL, names_betas))
      }
      
      for (i in (1:iter_outter)){
        # sample 5K first
        sample_idx = sample(x=nrow(data_filtered), size=n_samples)
        data_filtered_sample = data_filtered[sample_idx,]
          
        model_naive = lm(formula=paste("Y_naive", "~", X), data=data_filtered_sample) 
        model_naive_coef[i,] = coef(model_naive)
        model_naive_se[i,] = get_se_robust(model_naive)
        model_naive_ci = get_ci_robust(model_naive, alpha=0.05, use_t_score=FALSE)
        model_naive_lci[i,] = model_naive_ci[,1] # lower ci
        model_naive_uci[i,] = model_naive_ci[,2] # upper ci
        
        out = get_model_debiased_coef(data_filtered_sample, X, test_train_split, return_bias) 
        model_debiased_coef[i,] = out$model_debiased_coef
        if (return_bias){
          model_bias_coef[i,] = out$model_bias_coef
        }
        
        out_boot = draw_bootstrap_samples(
          data=data_filtered_sample, B=B, func=get_model_debiased_coef, X=X, 
          test_train_split=test_train_split, return_bias=return_bias)
        model_debiased_coef_boot = out_boot$model_debiased_coef
        model_debiased_se[i,] = get_se_boot(model_debiased_coef_boot)
        model_debiased_ci = get_ci_boot(model_debiased_coef_boot, alpha=0.05, method="percentile")
        model_debiased_lci[i,] = model_debiased_ci[,1] # lower ci
        model_debiased_uci[i,] = model_debiased_ci[,2] # upper ci
        
        if (return_bias){
          model_bias_coef_boot = out_boot$model_bias_coef
          model_bias_se[i,] = get_se_boot(model_bias_coef_boot)
          model_bias_ci = get_ci_boot(model_bias_coef_boot, alpha=0.05, method="percentile")
          model_bias_lci[i,] = model_bias_ci[,1] # lower ci
          model_bias_uci[i,] = model_bias_ci[,2] # upper ci
        }
      }
      
      out = list(
        "Model"=model,
        "PromptModificationID"=prompt_mod_id,
        "Major"=major,
        "X"=X,
        "model_human_coef"=model_human_coef,
        "model_human_se"  =model_human_se,
        "model_human_lci" =model_human_lci,
        "model_human_uci" =model_human_uci,
        "model_naive_coef"=model_naive_coef,
        "model_naive_se"  =model_naive_se,
        "model_naive_lci" =model_naive_lci,
        "model_naive_uci" =model_naive_uci,
        "model_bias_coef"=model_naive_coef,
        "model_bias_se"  =model_naive_se,
        "model_bias_lci" =model_naive_lci,
        "model_bias_uci" =model_naive_uci,
        "model_debiased_coef"=model_debiased_coef,
        "model_debiased_se"  =model_debiased_se,
        "model_debiased_lci" =model_debiased_lci,
        "model_debiased_uci" =model_debiased_uci
      )
      # variables = ls()[grep(pattern="^model_", x=ls())]
      filename = paste0(c("Major", major, "_", model, "_PromptModificationID", prompt_mod_id, "_", X),
        collapse="")
      saveRDS(out, file=file.path(rdata_dir, paste0(c(filename, ".rds"), collapse="")) )
      print(sprintf("saved %s", filename))
      
      colors = c("beta_human"="black","beta_naive" = "#1f77b4", "beta_debiased" = "#ff7f0e")
      p1 = ggplot() + 
        geom_vline(aes(xintercept=model_human_coef[1], color="beta_human"), linetype = "dashed") +
        geom_density(aes(x=model_naive_coef[,1], color="beta_naive")) +
        geom_density(aes(x=model_debiased_coef[,1], color="beta_debiased")) +
        labs(title = paste("Density Plot for",names(model_human_coef[1])),
             x = names(model_human_coef[1]),
             y = "Density") +
        scale_color_manual(name="", values=colors, breaks=names(colors)) +
        theme_bw() +
        theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
        theme(legend.position = "bottom")
      
      p2 = ggplot() + 
        geom_vline(aes(xintercept=model_human_coef[2], color="beta_human"), linetype = "dashed") +
        geom_density(aes(x=model_naive_coef[,2], color="beta_naive")) +
        geom_density(aes(x=model_debiased_coef[,2], color="beta_debiased")) +
        labs(title = paste("Density Plot for",names(model_human_coef[2])),
             x = names(model_human_coef[2]),
             y = "Density") +
        scale_color_manual(name="", values=colors, breaks=names(colors)) +
        theme_bw() +
        theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
        theme(legend.position = "bottom")
      
      # Arrange plots side by side
      p = arrangeGrob(p1, p2, ncol=2) 
      ggsave(file=file.path(figures_dir, paste0(c(filename,".pdf"), collapse="")), plot=p, width=8, height=4)
    }
  }
}

```

```{r}
# i = 6 # nrow(model_naive_coef)
# stargazer(
#   model_human, model_naive_last, model_debiased_last, # this is used to create the table template. Do not use the stats returned by models ending with _last.
#   coef = list(model_human_coef, model_naive_coef[i,], model_debiased_coef[i,]),
#   se = list(model_human_se, model_naive_se[i,], model_debiased_se[i,]), 
#   p.auto=TRUE, # TODO: Verify that p values and * align with the used coef and not based on the templates
#   ci.custom = list(
#     matrix(c(model_human_lci, model_human_uci), ncol=2),
#     matrix(c(model_naive_lci[i,], model_naive_uci[i,]), ncol=2),
#     matrix(c(model_debiased_lci[i,], model_debiased_uci[i,]), ncol=2)
#     ),
#   keep.stat = c("n"), # TODO: verify what to use for number of observations for Y_naive and Y_debiased
#   type = "text"
# )
```

## To-Dos:

- [ ] repeat for all models and all prompt modifications and all 3 X

