---
title: "Simulations"
date: "July 24, 2024"
output: html_document
---

This code is based on https://github.com/asheshrambachan/LanguageModel_Labels/blob/main/egami_et_al/code/LLM_errors.R

```{r setup, warning=FALSE, message=FALSE}
repo_dir = "/Users/haya1/Documents/LanguageModel_Labels/congressional_bills"
bias_dir = file.path(repo_dir, "04_bias")
knitr::opts_knit$set(root.dir = bias_dir)
setwd(bias_dir)

require(dplyr)
require(nnet)
require(stargazer)
require(sandwich)
require(lmtest)
require(ggplot2)
require(gridExtra)
require(furrr)
library(progressr)

rdata_dir = file.path(bias_dir, "rds")
dir.create(rdata_dir, showWarnings=FALSE)

figures_dir = file.path(bias_dir, "figures")
dir.create(figures_dir, showWarnings=FALSE)

data = read.csv(file.path(repo_dir, "02_llm/bills_prompts_responses_10000.csv"))

data = data %>% 
  # select(
  #   Model, PromptingStrategyID, PromptingStrategyName,
  #   BillID, Description,
  #   Chamber, Party, Year, Cong, Postal, State, DW1, Major, MajorText, 
  #   MajorLLM, MajorTextLLM, ConfidenceLLM, ExplanationLLM  # TODO: ConfidenceLLM is not used at the moment
  #   ) %>%
  mutate(
    Senate = as.integer(Chamber == "Senate"),
    Democrat = as.integer(Party == "Democrat")) %>% 
  select(
    Model, PromptingStrategyID, PromptingStrategyName,
    BillID, Description,
    Senate, Democrat, DW1, Major, MajorLLM) 

if (any(is.na(data)))
  warning("data contains NA")

```


## Functions

```{r}

get_se_robust = function(model){
  model_output = coeftest(model, vcov=vcovHC(model, type = "HC1"))
  return(model_output[,"Std. Error"])
}

get_ci_robust = function(model, alpha=0.05, use_z_score=TRUE){
  if (use_z_score){
    z_score = qnorm(1 - alpha/2)
    se_robust = get_se_robust(model)
    ci = cbind(coef(model) - z_score * se_robust, coef(model) + z_score * se_robust)
    colnames(ci) = c("2.5%", "97.5%")
  }
  else{ # t-score
    ci = coefci(model, level=1-alpha, vcov=vcovHC(model, type = "HC1"))
  }
  return(ci)
}

get_se_boot = function(samples_boot) apply(samples_boot, 2, sd)

get_ci_boot = function(samples_boot, alpha=0.05, method="percentile") {
  if (method!="percentile")
    stop("Only percentile method is implemented")
  
  probs = c(alpha/2, 1-alpha/2)
  ci_transposed = apply(samples_boot, 2, function(x){ 
    quantile(x, probs=probs)
    })
  ci = t(ci_transposed)
  
  return(ci)
}
```

```{r}
# TODO: add an option to compute the coef, se, ci, off
get_beta_debiased = function(train, test, X){
  # estimate error using train data
  train$error = train$Y_human - train$Y_llm
  model_error = lm(formula=paste("error", "~", X), data=train)
  
  # compute Y_debiased for the test data, regress Y_debiased ~ Xvar on the test data
  test$error = predict(model_error, newdata=test) # predict error for test data
  test$Y_debiased = test$Y_llm + test$error
  model_debiased = lm(formula=paste("Y_debiased", "~", X), data=test) 
  return(coef(model_debiased))
}

outer_loop_function = function(data, combo, N, B, n_samples, test_train_split){
  # combo = combos[combo_index,]
  major = combo$major
  X = combo$X
  model = combo$model 
  prompt_mod_id = combo$prompt_mod_id
  
  
  data = data %>% 
    filter(
      Model==model, 
      PromptingStrategyID==prompt_mod_id) %>%
    mutate(
      Y_human = as.integer(Major == major),
      Y_llm = as.integer(MajorLLM == major))
  
  names_betas = c("(Intercept)", X)
  n_betas = length(names_betas)
  betas = list(
    "human" = list(
      "coef" = vector(length=n_betas),
      "se"   = vector(length=n_betas),
      "lci"  = vector(length=n_betas),
      "uci"  = vector(length=n_betas)),
    "llm" = list(
      "coef" = matrix(nrow=N, ncol=n_betas, dimnames=list(NULL, names_betas)),
      "se"   = matrix(nrow=N, ncol=n_betas, dimnames=list(NULL, names_betas)),
      "lci"  = matrix(nrow=N, ncol=n_betas, dimnames=list(NULL, names_betas)),
      "uci"  = matrix(nrow=N, ncol=n_betas, dimnames=list(NULL, names_betas))),
    "human_train" = list(
      "coef" = matrix(nrow=N, ncol=n_betas, dimnames=list(NULL, names_betas)),
      "se"   = matrix(nrow=N, ncol=n_betas, dimnames=list(NULL, names_betas)),
      "lci"  = matrix(nrow=N, ncol=n_betas, dimnames=list(NULL, names_betas)),
      "uci"  = matrix(nrow=N, ncol=n_betas, dimnames=list(NULL, names_betas))),
    "error" = list(
      "coef" = matrix(nrow=N, ncol=n_betas, dimnames=list(NULL, names_betas)),
      "se"   = matrix(nrow=N, ncol=n_betas, dimnames=list(NULL, names_betas)),
      "lci"  = matrix(nrow=N, ncol=n_betas, dimnames=list(NULL, names_betas)),
      "uci"  = matrix(nrow=N, ncol=n_betas, dimnames=list(NULL, names_betas))),
    "debiased" = list(
      "coef" = matrix(nrow=N, ncol=n_betas, dimnames=list(NULL, names_betas)),
      "se"   = matrix(nrow=N, ncol=n_betas, dimnames=list(NULL, names_betas)),
      "lci"  = matrix(nrow=N, ncol=n_betas, dimnames=list(NULL, names_betas)),
      "uci"  = matrix(nrow=N, ncol=n_betas, dimnames=list(NULL, names_betas)))
  )
  
  # Using human-labeled major topics on all 10K bills
  model_human = lm(formula=paste("Y_human", "~", X), data=data)
  betas$human$coef = coef(model_human)
  betas$human$se = get_se_robust(model_human)
  betas$human$lci = get_ci_robust(model_human, alpha=0.05, use_z_score=TRUE)[,1] # lower ci
  betas$human$uci = get_ci_robust(model_human, alpha=0.05, use_z_score=TRUE)[,2] # upper ci
  
  for (i in (1:N)){ # outer loop
    # We randomly draw 5000 observations with replacement.
    data_sample = data[sample(x=nrow(data), size=n_samples, replace=TRUE) ,]
    
    # On the 5000 observations, we calculate model_llm
    model_llm = lm(formula=paste("Y_llm", "~", X), data=data_sample) 
    betas$llm$coef[i,] = coef(model_llm)
    betas$llm$se[i,] = get_se_robust(model_llm)
    betas$llm$lci[i,] = get_ci_robust(model_llm, alpha=0.05, use_z_score=TRUE)[,1] # lower ci
    betas$llm$uci[i,] = get_ci_robust(model_llm, alpha=0.05, use_z_score=TRUE)[,2] # upper ci
    
    # On the 5000 observations, we split the data into a train/test split. Since it's already a random sample, we don't do it using the sample function
    train_idx = 1:(nrow(data_sample) * test_train_split) # sample(x=nrow(data_sample), size=nrow(data_sample) * test_train_split, replace=FALSE)
    train = data_sample[train_idx, ]
    test = data_sample[-train_idx, ]
    
    # Using the train/test split, we calculate 
    # (i) model_human_train using only train. We calculate the se of model_human_train using heteroskedasticity robust standard errors.
    model_human_train = lm(formula=paste("Y_human", "~", X), data=train) # TODO: keep coef, se (robust), ci (z_score)
    betas$human_train$coef[i,] = coef(model_human_train)
    betas$human_train$se[i,] = get_se_robust(model_human_train)
    betas$human_train$lci[i,] = get_ci_robust(model_human_train, alpha=0.05, use_z_score=TRUE)[,1] # lower ci
    betas$human_train$uci[i,] = get_ci_robust(model_human_train, alpha=0.05, use_z_score=TRUE)[,2] # upper ci
    
    # (ii) estimate error from train data 
    # TODO: verify that beta should also use robust
    train$error = train$Y_human - train$Y_llm
    model_error = lm(formula=paste("error", "~", X), data=train)
    betas$error$coef[i,] = coef(model_error)
    betas$error$se[i,] = get_se_robust(model_error)
    betas$error$lci[i,] = get_ci_robust(model_error, alpha=0.05, use_z_score=TRUE)[,1] # lower ci
    betas$error$uci[i,] = get_ci_robust(model_error, alpha=0.05, use_z_score=TRUE)[,2] # upper ci
    
    # (iii) corrected error, and estimate debiased model
    betas$debiased$coef[i,] = get_beta_debiased(train=train, test=test, X=X)
    
    # but since beta_debiased function based on the predicted Y_debiased, we can't use robust se and ci. 
    # TODO: I think we should bootstrapping from the fixed train/test split instead. Otherwise, the result above is simply 1 sample since test/train split is random?
    
    # We then begin the bootstrap (inner loop):
    debiased_coef_boot = as.data.frame(t(sapply(
      1:B, 
      function(b){ # ignore b
        data_sample_boot = data_sample[sample(x=nrow(data_sample), replace=TRUE) ,] # TODO: double check this as train/test split is not with replacement
        
        # We redraw train/test splits, and on each train/test split, we calculate corrected_beta.
        train_idx_boot = 1:(nrow(data_sample_boot)*test_train_split)
        train_boot = data_sample_boot[train_idx_boot, ]
        test_boot = data_sample_boot[-train_idx_boot, ]
        return(get_beta_debiased(train=train_boot, test=test_boot, X=X))
      }
    )))
    
    # We use bootstrap samples to calculate se and confidence intervals for corrected_beta.
    betas$debiased$se[i,] = get_se_boot(debiased_coef_boot)
    betas$debiased$lci[i,] = get_ci_boot(debiased_coef_boot, alpha=0.05, method="percentile")[,1] # lower ci
    betas$debiased$uci[i,] = get_ci_boot(debiased_coef_boot, alpha=0.05, method="percentile")[,2] # upper ci
  }
  
  return(betas)
}

```

## Models


```{r}
# progressr::handlers(global = TRUE)
```


```{r}
combos = expand.grid(
  prompt_mod_id = (1:12),
  model = c("gpt-3.5-turbo-0125", "gpt-4o"),
  X = c("Senate", "Democrat", "DW1"),
  major = (1:20)[1:2],
  stringsAsFactors = FALSE
  )

n_cores = parallelly::availableCores()
plan(multisession, workers = n_cores) # or simply use: plan(multisession)

start.time = Sys.time()
with_progress({
  p <- progressor(along = 1:nrow(combos)) # steps = length(x)

  betas_list = future_map(
    # .progress = TRUE,
    .options = furrr_options(seed=123), # enable change of seed as the seed is fixed by default and this will be used in a loop
    .x = 1:nrow(combos),
    # .f = ~ outer_loop_function(
    #   data=data,
    #   combo=combos[.x,],
    #   N=10,
    #   B=100,
    #   n_samples=5000, # for llm
    #   test_train_split=0.5)
    # )
    .f = function(x) {
      betas = outer_loop_function(
        data=data, 
        combo=combos[x,],
        N=10,
        B=100,
        n_samples=5000, # for llm
        test_train_split=0.5
        )
      p(sprintf("combo = %g", x))
      return(betas)
    })
})

end.time <- Sys.time()
print(round(end.time - start.time,2))
```


```{r}
# ~14 sec to run N=1 B=1000
(14*1000)/60/60
# 4 hours per combo
```

```{r}
plan(sequential)

for (i in 1:nrow(combos)){
  combo = combos[i,]
  out = list(
      "Model"= combo$model,
      "PromptModificationID"= combo$prompt_mod_id,
      "Major"= combo$major,
      "X"= combo$X,
      "betas" = betas_list[[i]]
    )
  filename = paste0(c("Major", combo$major, "_", combo$model, "_PromptModificationID", combo$prompt_mod_id, "_", combo$X), collapse="")
  saveRDS(out, file=file.path(rdata_dir, paste0(c(filename, ".rds"), collapse="")) )
}
```

## To-Dos:

- [ ] separate betas into beta0 beta1?