source("./tables/code/estimation_legislation/tab_point_est_cb_lhs.R")
source("./tables/code/estimation_legislation/tab_point_est_cb_rhs.R")

source("./tables/code/estimation_legislation/tab_summary_stat_gpt3_cb_lhs_prop05.R")
source("./tables/code/estimation_legislation/tab_summary_stat_gpt4o_cb_lhs_prop05.R")
source("./tables/code/estimation_legislation/tab_summary_stat_gpt5mini_cb_lhs_prop05.R")
source("./tables/code/estimation_legislation/tab_summary_stat_gpt5nano_cb_lhs_prop05.R")

source("./tables/code/estimation_legislation/tab_summary_stat_gpt3_cb_rhs_prop05.R")
source("./tables/code/estimation_legislation/tab_summary_stat_gpt4o_cb_rhs_prop05.R")
source("./tables/code/estimation_legislation/tab_summary_stat_gpt5mini_cb_rhs_prop05.R")
source("./tables/code/estimation_legislation/tab_summary_stat_gpt5nano_cb_rhs_prop05.R")

# source("./tables/code/estimation_legislation/tab_summary_stat_gpt3_cb_lhs_prop10.R")
# source("./tables/code/estimation_legislation/tab_summary_stat_gpt4o_cb_lhs_prop10.R")
# source("./tables/code/estimation_legislation/tab_summary_stat_gpt5mini_cb_lhs_prop10.R")
# source("./tables/code/estimation_legislation/tab_summary_stat_gpt5nano_cb_lhs_prop10.R")
# 
# source("./tables/code/estimation_legislation/tab_summary_stat_gpt3_cb_rhs_prop10.R")
# source("./tables/code/estimation_legislation/tab_summary_stat_gpt4o_cb_rhs_prop10.R")
# source("./tables/code/estimation_legislation/tab_summary_stat_gpt5mini_cb_rhs_prop10.R")
# source("./tables/code/estimation_legislation/tab_summary_stat_gpt5nano_cb_rhs_prop10.R")

source("./tables/code/estimation_legislation/tab_summary_stat_gpt3_cb_lhs_all_prop_plugin.R")
source("./tables/code/estimation_legislation/tab_summary_stat_gpt3_cb_lhs_all_prop_debiased.R")
source("./tables/code/estimation_legislation/tab_summary_stat_gpt4o_cb_lhs_all_prop_plugin.R")
source("./tables/code/estimation_legislation/tab_summary_stat_gpt4o_cb_lhs_all_prop_debiased.R")
source("./tables/code/estimation_legislation/tab_summary_stat_gpt5mini_cb_lhs_all_prop_plugin.R")
source("./tables/code/estimation_legislation/tab_summary_stat_gpt5mini_cb_lhs_all_prop_debiased.R")
source("./tables/code/estimation_legislation/tab_summary_stat_gpt5nano_cb_lhs_all_prop_plugin.R")
source("./tables/code/estimation_legislation/tab_summary_stat_gpt5nano_cb_lhs_all_prop_debiased.R")

source("./tables/code/estimation_legislation/tab_summary_stat_gpt3_cb_rhs_all_prop_plugin.R")
source("./tables/code/estimation_legislation/tab_summary_stat_gpt3_cb_rhs_all_prop_debiased.R")
source("./tables/code/estimation_legislation/tab_summary_stat_gpt4o_cb_rhs_all_prop_plugin.R")
source("./tables/code/estimation_legislation/tab_summary_stat_gpt4o_cb_rhs_all_prop_debiased.R")
source("./tables/code/estimation_legislation/tab_summary_stat_gpt5mini_cb_rhs_all_prop_plugin.R")
source("./tables/code/estimation_legislation/tab_summary_stat_gpt5mini_cb_rhs_all_prop_debiased.R")
source("./tables/code/estimation_legislation/tab_summary_stat_gpt5nano_cb_rhs_all_prop_plugin.R")
source("./tables/code/estimation_legislation/tab_summary_stat_gpt5nano_cb_rhs_all_prop_debiased.R")
