---
title: "Results"
header-includes:
  - \usepackage{amsmath}
  - \usepackage{floatrow}
  - \floatsetup[figure]{capposition=top}
  - \floatsetup[table]{capposition=top}
output:
  pdf_document: 
    fig_caption: true
    fig_crop: false
  # html_document: default
date: "Aug 12, 2024"
editor_options: 
  chunk_output_type: console
---

```{r theme, warning=FALSE, message=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)

repo_dir = "/Users/haya1/Documents/LanguageModel_Labels/congressional_bills"
results_dir = file.path(repo_dir, "05_results")

knitr::opts_knit$set(root.dir = results_dir)
knitr::opts_current$set(dpi = 300)
knitr::opts_chunk$set(warning=FALSE, message=FALSE, echo=FALSE, dev = "cairo_pdf")

setwd(results_dir)

require(dplyr)
require(ggplot2)
require(latex2exp)
require(kableExtra)
require(extrafont)
require(lemon)

# download ttf file from https://www.fontsquirrel.com/fonts/computer-modern
# install on mac 
# Run once in R: 
# font_import(paths="/Users/haya1/Library/Fonts/", pattern="cmun*")
loadfonts(quiet=T)
# names(pdfFonts()) # uncomment to get list of fonts

my_palette <- c("red"="#F85427", "blue"="#277BB6", "green"="#97BD59", "yellow"="#FFD166", "black"="#262626", "gray"="gray")
my_colors <- c(

  "5k_V_Yllm" = my_palette[["red"]], 
  "train_V_Yhuman" = my_palette[["blue"]],
  "test_Vtilde_Ytilde" = my_palette[["green"]],
  
  "star" = my_palette[["red"]], 
  "gpt-3.5" =  my_palette[["green"]],
  "gpt-4o" = my_palette[["blue"]],
  
  "LLM" = my_palette[["red"]], 
  "Human Train" = my_palette[["blue"]],
  "Debiased" = my_palette[["green"]]
  )

theme.point <- theme_bw() + 
  theme(
    panel.grid.major.x=element_blank(), 
    panel.grid.minor.x=element_blank(), 
    panel.grid.major.y=element_line(linewidth=0.2),
    panel.grid.minor.y=element_blank(),
    legend.position="top", 
    axis.text=element_text(size=7),
    axis.ticks=element_line(linewidth=0.3),
    text=element_text(size=12, family="CMU Sans Serif"),
    legend.title=element_text(size=10, family="CMU Sans Serif Bold"),
    plot.title=element_text(size=14, family="CMU Sans Serif Bold"),
    plot.subtitle=element_text(size=12, family="CMU Sans Serif")
    ) 

theme.bar <- theme_bw() + 
  theme(
    panel.grid.major.x=element_blank(), 
    panel.grid.minor.x=element_blank(), 
    panel.grid.major.y=element_line(linewidth=0.3),
    panel.grid.minor.y=element_line(linewidth=0.1),
    legend.position="top", 
    axis.text=element_text(size=7),
    axis.ticks=element_line(linewidth=0.3),
    text=element_text(size=12, family="CMU Sans Serif"),
    legend.title=element_text(size=10, family="CMU Sans Serif Bold"),
    plot.title=element_text(size=14, family="CMU Sans Serif Bold"),
    plot.subtitle=element_text(size=12, family="CMU Sans Serif")
    )

theme.mse <- theme_bw() + 
  theme(
    panel.grid.major.x=element_line(linewidth=0.3), 
    panel.grid.minor.x=element_line(linewidth=0.1), 
    panel.grid.major.y=element_line(linewidth=0.3),
    panel.grid.minor.y=element_line(linewidth=0.1),
    legend.position="top", 
    axis.text=element_text(size=7),
    axis.ticks=element_line(linewidth=0.3),
    text=element_text(size=12, family="CMU Sans Serif"),
    legend.title=element_text(size=10, family="CMU Sans Serif Bold"),
    plot.title=element_text(size=14, family="CMU Sans Serif Bold"),
    plot.subtitle=element_text(size=12, family="CMU Sans Serif")
    )
```


```{r fig_accuracy, echo=FALSE, fig.height=3, fig.width=4, fig.cap="Accuracy of Topic Predictions vs. Prompt. Accuracy = $P[\\hat{Y}=Y^*] = \\frac{1}{10k} \\sum_{i=1}^{10k} 1\\{\\hat{Y}_i=Y_i^*\\}$"}

bills_prompts_responses <- read.csv(file.path(repo_dir, "02_llm/bills_prompts_responses_10000.csv")) %>%
  rename(c(prompt=PromptingStrategyID, model=Model, Yhuman=Major, Yllm=MajorLLM)) %>%
  select(c(prompt, model, Yhuman, Yllm)) %>%
  mutate(model = factor(
    model, 
    levels=c("gpt-3.5-turbo-0125", "gpt-4o"), 
    labels=c("gpt-3.5", "gpt-4o")
    )) %>%
  group_by(model, prompt) %>%
  summarise(accuracy = mean(Yhuman==Yllm), .groups="drop")

accuracy <- bills_prompts_responses %>%
  ggplot(aes(x=as.factor(prompt), y=accuracy, fill=model)) +
  geom_col(position=position_dodge()) +
  xlab("Prompt Index") +
  ylab("Accuracy") +
  scale_y_continuous(minor_breaks=seq(0,1, by=0.05), limits=c(0,1)) +
  scale_fill_manual(name="", values=my_colors, labels=c("gpt-3.5"="GPT3.5", "gpt-4o"="GPT4o")) +
  theme.bar

accuracy
```

\clearpage

# Proxy on the LHS

```{r lhs_data_10k, echo=FALSE}
# Note: prompts were sorted based on the coefficients values of GPT3.5 model.
V.levels <- c("Democrat", "Senate", "DW1")

model.levels <- c("star", "gpt-3.5", "gpt-4o")
model.labels <- c(TeX("$\\beta^*$"), TeX("$\\hat{\\beta}_{GPT3.5}$"), TeX("$\\hat{\\beta}_{GPT4o}$"))

Y.labeller <- function(Y) TeX(sprintf("$Y_{%s}$", Y)) 

prompt_index <- read.csv(file.path(repo_dir, "04_simulation/lhs/bayesian/10k_llm_lhs.csv")) %>%
  filter(tolower(model)=="gpt-3.5") %>%
  group_by(V, Y, coef_name) %>%
  arrange(V, Y, coef_name, coef) %>% mutate(prompt.ordered_coef = row_number()) %>% # create prompt index ordered by coef
  arrange(V, Y, coef_name, t) %>% mutate(prompt.ordered_t = row_number()) %>% # create prompt index ordered by t scores
  ungroup() %>%
  select(V, Y, coef_name, prompt, prompt.ordered_coef, prompt.ordered_t) %>%
  distinct()

regressions.llm <- read.csv(file.path(repo_dir, "04_simulation/lhs/bayesian/10k_llm_lhs.csv")) %>%
  merge(x=., y=prompt_index, all=TRUE, sort=FALSE) %>%
  mutate(
    prompt.ordered_coef = as.factor(prompt.ordered_coef),
    prompt.ordered_t = as.factor(prompt.ordered_t),
    model = factor(model, levels=model.levels),
    V = factor(V, levels=V.levels)
    ) %>%
  filter(coef_name!="(Intercept)")

regressions.human <- read.csv(file.path(repo_dir, "04_simulation/lhs/bayesian/10k_human_lhs.csv")) %>%
  mutate(
    model = "star",
    model = factor(model, levels=model.levels),
    V = factor(V, levels=V.levels)
    ) %>%
  filter(coef_name!="(Intercept)")
```

```{r lhs_fig_coef, echo=FALSE, fig.height=5.5, fig.width=9, fig.cap="$\\hat{\\beta}$ vs. Prompt. Proxy on the LHS: $Y = \\beta_{0} + \\beta_{1} V$"}
coefs <- regressions.llm %>%
  ggplot(aes(x=prompt.ordered_coef, color=model, shape=model)) +
  geom_hline(yintercept=0, color=my_palette[["black"]], linewidth=0.2) +

  geom_hline(aes(yintercept=lci, color=model), linetype="dashed", linewidth=0.3, data=regressions.human) +
  geom_hline(aes(yintercept=uci, color=model), linetype="dashed", linewidth=0.3, data=regressions.human) +
  geom_hline(aes(yintercept=coef, color=model), linewidth=0.5, data=regressions.human) +

  geom_errorbar(aes(ymin=lci, ymax=uci), position=position_dodge(width=0.5), width=0.5, linewidth=0.3) +
  geom_point(aes(y=coef), size=1.25, alpha=0.7, position=position_dodge(width=0.5)) +
  
  facet_grid(V ~ Y, labeller=labeller(Y=Y.labeller, .default = label_parsed)) +
  
  xlab("Prompt Index") +
  ylab("Coefficients") +
  
  scale_color_manual(name=NULL, values=my_colors, labels=model.labels) +
  guides(color = guide_legend(override.aes = list(shape = c(NA, 16, 17))), 
         shape = "none") +  # merge color and shape legends
  theme.point

coefs
```

```{r lhs_fig_tscore, echo=FALSE, fig.height=5.5, fig.width=9, fig.cap="t-scores vs. Prompt. Proxy on the LHS: $Y = \\beta_{0} + \\beta_{1} V$"}
tscores <- regressions.llm %>%
  ggplot(aes(x=prompt.ordered_t, color=model, shape=model)) +
  geom_hline(yintercept=0, color=my_palette[["black"]], linewidth=0.2) +

  geom_hline(aes(yintercept=t, color=model), linewidth=0.5, data=regressions.human) +
  geom_point(aes(y=t), size=1.25, alpha=0.7, position=position_dodge(width=0.5)) +

  facet_grid(V ~ Y, labeller=labeller(Y=Y.labeller, .default = label_parsed)) +
  
  xlab("Prompt Index") +
  ylab("t-scores") +

  scale_color_manual(name=NULL, values=my_colors, labels=model.labels) +
  guides(color = guide_legend(override.aes = list(shape = c(NA, 16, 17))), 
         shape = "none") +  # merge color and shape legends
  
  theme.point

tscores
```

\clearpage

```{r lhs_data_regressions.averaged, echo=FALSE}
regression.levels <- c("5k_Yllm_V", "train_Yhuman_V", "test_Ytilde_V")
regression.labels <- c("LLM", "Human Train", "Debiased")

model.levels <- c("gpt-3.5", "gpt-4o")
model.labels <- c("GPT3.5", "GPT4o")

regressions.averaged <- read.csv(file.path(repo_dir, "04_simulation/lhs/bayesian/simulations_averaged_lhs.csv")) %>%
  filter(coef_name!="(Intercept)") %>% # Plot only beta_1
   mutate(
     bias_norm = bias_mean/coef_sd, 
     V = factor(V, levels=V.levels),
     model = factor(model, levels=model.levels, labels=model.labels),
     regression = factor(regression, levels=regression.levels, labels=regression.labels)
     ) %>%
  rename(proportion=train_proportion) 

facet.labeller <- labeller(proportion = function(proportion) sprintf("Validation Proportion = %s%%", as.numeric(proportion)*100))

n_bins <- 20
```

```{r lhs_fig_bias1, echo=FALSE, fig.height=3, fig.width=8, fig.cap="Bias Density by Proportion of Validation Samples. Proxy on the LHS: $Y = \\beta_{0} + \\beta_{1} V$"}
bias1 <- regressions.averaged %>%
  filter(proportion!=0.25) %>%
  ggplot(aes(x=bias_mean, y=after_stat(max(group)*count/tapply(count, PANEL, FUN=sum)[PANEL]), 
             group=regression, fill=regression)) +
  # geom_vline(xintercept=0, color=my_palette[["black"]], linewidth=0.2) +
  geom_histogram(bins=n_bins, position=position_dodge()) +
  facet_grid(. ~ proportion, labeller=facet.labeller) +
  
  xlab("Bias") +
  ylab("Probability Densities") +
  
  scale_fill_manual(name=NULL, values=my_colors) +
  scale_x_symmetric(mid=0) +
  scale_y_continuous(minor_breaks=seq(0,1, by=0.05), limits=c(0,1)) +
  theme.bar

bias1
```

```{r lhs_fig_bias1_norm, echo=FALSE, fig.height=3, fig.width=8, fig.cap="Normalized Bias Density by Proportion of Validation Samples. Proxy on the LHS: $Y = \\beta_{0} + \\beta_{1} V$"}

bias1_norm <- regressions.averaged %>%
  filter(proportion!=0.25) %>%
  ggplot(aes(x=bias_norm, 
             y=after_stat(max(group)*count/tapply(count, PANEL, FUN=sum)[PANEL]),
             group=regression, fill=regression)) +
  geom_histogram(binwidth=0.09, position=position_dodge()) +
  facet_grid(. ~ proportion, labeller=facet.labeller) +
  
  xlab("Normalized Bias") +
  ylab("Probability Densities") +
  
  scale_fill_manual(name=NULL, values=my_colors) +
  scale_x_symmetric(mid=0) +
  scale_y_continuous(minor_breaks=seq(0,1, by=0.05), limits=c(0,1)) +
  theme.bar

bias1_norm
```


\clearpage

```{r lhs_fig_bias2, echo=FALSE, fig.height=3*1.5, fig.width=8, fig.cap="Bias Density by Model and Proportion of Validation Samples. Proxy on the LHS: $Y = \\beta_{0} + \\beta_{1} V$"}

bias2 <- regressions.averaged %>%
  filter(proportion!=0.25) %>%
  ggplot(aes(x=bias_mean, y=after_stat(max(group)*count/tapply(count, PANEL, FUN=sum)[PANEL]), 
             group=regression, fill=regression)) +
  geom_histogram(bins=n_bins, position=position_dodge()) +
  facet_grid(model ~ proportion, labeller=facet.labeller) +
  
  xlab("Bias") +
  ylab("Probability Densities") +
  
  scale_fill_manual(name=NULL, values=my_colors) +
  scale_x_symmetric(mid=0) +
  scale_y_continuous(minor_breaks=seq(0,1, by=0.05), limits=c(0,1)) +
  theme.bar

bias2
```

```{r lhs_fig_bias2_norm, echo=FALSE, fig.height=3*1.5, fig.width=8, fig.cap="Normalized Bias Density by Model and Proportion of Validation Samples. Proxy on the LHS: $Y = \\beta_{0} + \\beta_{1} V$"}

bias2_norm <- regressions.averaged %>%
  filter(proportion!=0.25) %>%
  ggplot(aes(x=bias_norm, y=after_stat(max(group)*count/tapply(count, PANEL, FUN=sum)[PANEL]),
             group=regression, fill=regression)) +
  geom_histogram(binwidth=0.09, position=position_dodge()) +
  facet_grid(model ~ proportion, labeller=facet.labeller) +
  
  xlab("Normalized Bias") +
  ylab("Probability Densities") +
  
  scale_fill_manual(name=NULL, values=my_colors) +
  scale_x_symmetric(mid=0) +
  scale_y_continuous(minor_breaks=seq(0,1, by=0.05), limits=c(0,1)) +
  theme.bar

bias2_norm
```

\clearpage

```{r lhs_fig_mse1, echo=FALSE, fig.height=3, fig.width=8, fig.cap="MSE Empirical CDF by Proportion of Validation Samples. Proxy on the LHS: $Y = \\beta_{0} + \\beta_{1} V$"}

mse1 <- regressions.averaged %>%
  filter(
    proportion != 0.25,
    regression != "LLM"
    ) %>%
  ggplot(aes(x=mse_mean, color=regression, linetype=regression)) +
  
  stat_ecdf(linewidth=0.5) +
  facet_grid(. ~ proportion, labeller=facet.labeller) +
  
  xlab("MSE") +
  ylab("Empirical CDF") +
  
  scale_x_continuous(minor_breaks = seq(0,1,0.0001)) +
  scale_color_manual(name="", values=my_colors) +
  scale_linetype_manual(name="", values=c("dashed", "solid")) +
  theme.mse

mse1
```

```{r lhs_fig_mse2, echo=FALSE, fig.height=3*1.5, fig.width=8, fig.cap="MSE Empirical CDF by Model and Proportion of Validation Samples. Proxy on the LHS: $Y = \\beta_{0} + \\beta_{1} V$"}

mse2 <- regressions.averaged %>%
  filter(
    proportion != 0.25,
    regression != "LLM"
    ) %>%
  ggplot(aes(x=mse_mean, color=regression, linetype=regression)) +
  
  stat_ecdf(linewidth=0.5) +
  facet_grid(model ~ proportion, labeller=facet.labeller) +
  
  xlab("MSE") +
  ylab("Empirical CDF") +
  
  scale_x_continuous(minor_breaks = seq(0,1,0.0001)) +
  scale_color_manual(name="", values=my_colors) +
  scale_linetype_manual(name="", values=c("dashed", "solid")) +
  theme.mse

mse2
```

\clearpage

```{r lhs_tab_data}

proportion.levels <- c(0.05, 0.10, 0.25, 0.50)
regressions.averaged$proportion <- factor(
  regressions.averaged$proportion, 
  levels=proportion.levels, 
  labels=sprintf("%s\\%%", proportion.levels*100))

alpha <- 0.10
probs <- c(alpha/2, 1-alpha/2)

stripe <- function(nstriped=3, nrow=50){
  start_row <- rep(seq(0, (2*nstriped)*nrow, by=2*nstriped), each=nstriped)
  return(start_row + rep(1:nstriped, times=length(start_row)/nstriped))
}
  
```

```{r lhs_tab_bias1, echo=FALSE, results='asis'}
bias1 <- regressions.averaged %>%
  mutate(statistic=bias_mean) %>%
  group_by(proportion, regression) %>%
  summarise(
    "Mean" = mean(statistic),
    "SD" = sd(statistic),
    "Median" = median(statistic),
    "5\\%" = quantile(statistic, probs[1]),
    "95\\%" = quantile(statistic, probs[2]),
    .groups = "drop"
    ) %>%
  rename(c(
    "Validation Proportion" = proportion, 
    "Bias" = regression)
    )

kbl(bias1, align="rlrrrrr",
    caption="Bias Summary Statistics by Proportion of Validation Samples for $\\beta_1$. Proxy on the LHS: $Y = \\beta_{0} + \\beta_{1} V$.",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))
```

```{r lhs_tab_bias1_norm, echo=FALSE, results='asis'}
bias1_norm <- regressions.averaged %>%
  mutate(statistic=bias_norm) %>%
  group_by(proportion, regression) %>%
  summarise(
    "Mean" = mean(statistic),
    "SD" = sd(statistic),
    "Median" = median(statistic),
    "5\\%" = quantile(statistic, probs[1]),
    "95\\%" = quantile(statistic, probs[2]),
    .groups = "drop"
    ) %>%
  rename(c(
    "Validation Proportion" = proportion, 
    "Normalized Bias" = regression)
    )

kbl(bias1_norm, align="rlrrrrr",
    caption="Normalized Bias Summary Statistics by Proportion of Validation Samples for $\\beta_1$. Proxy on the LHS: $Y = \\beta_{0} + \\beta_{1} V$.",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))
```


```{r lhs_tab_bias2, echo=FALSE, results='asis'}
bias2 <- regressions.averaged %>%
  mutate(statistic=bias_mean) %>%
  group_by(model, proportion, regression) %>%
  summarise(
    "Mean" = mean(statistic),
    "SD" = sd(statistic),
    "Median" = median(statistic),
    "5\\%" = quantile(statistic, probs[1]),
    "95\\%" = quantile(statistic, probs[2]),
    .groups = "drop"
    ) %>%
  rename(c(
    "Model" = model, 
    "Validation Proportion" = proportion, 
    "Bias" = regression
    ))

kbl(bias2, align="lrlrrrrr",
    caption="Bias Summary Statistics by Model and Proportion of Validation Samples for $\\beta_1$. Proxy on the LHS: $Y = \\beta_{0} + \\beta_{1} V$.",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))
```


```{r lhs_tab_bias2_norm, echo=FALSE, results='asis'}
bias2_norm <- regressions.averaged %>%
  mutate(statistic=bias_norm) %>%
  group_by(model, proportion, regression) %>%
  summarise(
    "Mean" = mean(statistic),
    "SD" = sd(statistic),
    "Median" = median(statistic),
    "5\\%" = quantile(statistic, probs[1]),
    "95\\%" = quantile(statistic, probs[2]),
    .groups = "drop"
    ) %>%
  rename(c(
    "Model" = model, 
    "Validation Proportion" = proportion, 
    "Normalized Bias" = regression
    ))

kbl(bias2_norm, align="lrlrrrrr",
    caption="Normalized Bias Summary Statistics by Model and Proportion of Validation Samples for $\\beta_1$. Proxy on the LHS: $Y = \\beta_{0} + \\beta_{1} V$.",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))
```

```{r lhs_tab_mse1, echo=FALSE, results='asis'}
mse1 <- regressions.averaged %>%
  mutate(statistic=mse_mean) %>%
  group_by(proportion, regression) %>%
  summarise(
    "Mean" = mean(statistic),
    "SD" = sd(statistic),
    "Median" = median(statistic),
    "5\\%" = quantile(statistic, probs[1]),
    "95\\%" = quantile(statistic, probs[2]),
    .groups = "drop") %>%
  rename(c(
    "Validation Proportion" = proportion, 
    "MSE" = regression)
    )

kbl(mse1, align="rlrrrrr",
    caption="MSE Summary Statistics by Proportion of Validation Samples for $\\beta_1$. Proxy on the LHS: $Y = \\beta_{0} + \\beta_{1} V$.",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))
```


```{r lhs_tab_mse2, echo=FALSE, results='asis'}
mse2 <- regressions.averaged %>%
  mutate(statistic=mse_mean) %>%
  group_by(model, proportion, regression) %>%
  summarise(
    "Mean" = mean(statistic),
    "SD" = sd(statistic),
    "Median" = median(statistic),
    "5\\%" = quantile(statistic, probs[1]),
    "95\\%" = quantile(statistic, probs[2]),
    .groups = "drop") %>%
  rename(c(
    "Model" = model, 
    "Validation Proportion" = proportion, 
    "MSE" = regression
    ))

kbl(mse2, align="lrlrrrrr",
    caption="MSE Summary Statistics by Model and Proportion of Validation Samples for $\\beta_1$. Proxy on the LHS: $Y = \\beta_{0} + \\beta_{1} V$.",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))
```


```{r lhs_tab_coverage1, echo=FALSE, results='asis'}
coverage1 <- regressions.averaged %>%
  mutate(statistic=coverage_mean) %>%
  group_by(proportion, regression) %>%
  summarise(
    "Mean" = mean(statistic),
    "SD" = sd(statistic),
    "Median" = median(statistic),
    "5\\%" = quantile(statistic, probs[1]),
    "95\\%" = quantile(statistic, probs[2]),
    .groups = "drop") %>%
  rename(c(
    "Validation Proportion" = proportion, 
    "Coverage" = regression)
    )

kbl(coverage1, align="rllrrrrr",
    caption="Coverage Summary Statistics by Proportion of Validation Samples for $\\beta_1$. Proxy on the LHS: $Y = \\beta_{0} + \\beta_{1} V$.",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))
```


```{r lhs_tab_coverage2, echo=FALSE, results='asis'}
coverage2 <- regressions.averaged %>%
  mutate(statistic=coverage_mean) %>%
  group_by(model, proportion, regression) %>%
  summarise(
    "Mean" = mean(statistic),
    "SD" = sd(statistic),
    "Median" = median(statistic),
    "5\\%" = quantile(statistic, probs[1]),
    "95\\%" = quantile(statistic, probs[2]),
    .groups = "drop") %>%
  rename(c(
    "Model" = model, 
    "Validation Proportion" = proportion, 
    "MSE" = regression
    ))
  
kbl(coverage2, align="lrlrrrrr",
    caption="Coverage Summary Statistics by Model and Proportion of Validation Samples for $\\beta_1$. Proxy on the LHS: $Y = \\beta_{0} + \\beta_{1} V$.",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))
```


\clearpage

# Proxy on the RHS


```{r rhs_data_10k, echo=FALSE}
# Note: prompts were sorted based on the coefficients values of GPT3.5 model.
V.levels <- c("Democrat", "Senate", "DW1")

model.levels <- c("star", "gpt-3.5", "gpt-4o")
model.labels <- c(TeX("$\\beta^*$"), TeX("$\\hat{\\beta}_{GPT3.5}$"), TeX("$\\hat{\\beta}_{GPT4o}$"))

Y.labeller <- function(Y) TeX(sprintf("$Y_{%s}$", Y)) 

prompt_index <- read.csv(file.path(repo_dir, "04_simulation/rhs/bayesian/10k_llm_rhs.csv")) %>%
  filter(tolower(model)=="gpt-3.5") %>%
  group_by(V, coef_name) %>%
  arrange(V, coef_name, coef) %>% mutate(prompt.ordered_coef = row_number()) %>% # create prompt index ordered by coef
  arrange(V, coef_name, t) %>% mutate(prompt.ordered_t = row_number()) %>% # create prompt index ordered by t scores
  ungroup() %>%
  select(V, coef_name, prompt, prompt.ordered_coef, prompt.ordered_t) %>%
  distinct()

regressions.llm <- read.csv(file.path(repo_dir, "04_simulation/rhs/bayesian/10k_llm_rhs.csv")) %>%
  merge(x=., y=prompt_index, all=TRUE, sort=FALSE) %>%
  mutate(
    prompt.ordered_coef = as.factor(prompt.ordered_coef),
    prompt.ordered_t = as.factor(prompt.ordered_t),
    model = factor(model, levels=model.levels),
    Y = sub("Y","", coef_name), 
    V = factor(V, levels=V.levels)
    ) # %>%
  # filter(coef_name!="Other")

regressions.human <- read.csv(file.path(repo_dir, "04_simulation/rhs/bayesian/10k_human_rhs.csv")) %>%
  mutate(
    model = "star",
    model = factor(model, levels=model.levels),
    Y = sub("Y","", coef_name), 
    V = factor(V, levels=V.levels)
    ) # %>%
  # filter(coef_name!="Other")
```


```{r rhs_fig_coef, echo=FALSE, fig.height=5.5, fig.width=9, fig.cap="$\\hat{\\beta}$ vs. Prompt for all $\\beta$s. Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_{Other} \\beta_{Other}$"}
coefs <- regressions.llm %>%
  ggplot(aes(x=prompt.ordered_coef, color=model, shape=model)) +

  geom_hline(aes(yintercept=lci, color=model), linetype="dashed", linewidth=0.3, data=regressions.human) +
  geom_hline(aes(yintercept=uci, color=model), linetype="dashed", linewidth=0.3, data=regressions.human) +
  geom_hline(aes(yintercept=coef, color=model), linewidth=0.5, data=regressions.human) +

  geom_errorbar(aes(ymin=lci, ymax=uci), position=position_dodge(width=0.5), width=0.5, linewidth=0.3) +
  geom_point(aes(y=coef), size=1.25, alpha=0.7, position=position_dodge(width=0.5)) +
  
  facet_grid(V ~ Y, labeller=labeller(Y=Y.labeller, .default = label_parsed), scales="free_y") +
  
  xlab("Prompt Index") +
  ylab("Coefficients") +
  
  scale_color_manual(name=NULL, values=my_colors, labels=model.labels) +
  guides(color = guide_legend(override.aes = list(shape = c(NA, 16, 17))), 
         shape = "none") +  # merge color and shape legends
  theme.point

coefs
```

```{r rhs_fig_tscore, echo=FALSE, fig.height=5.5, fig.width=9, fig.cap="t-scores vs. Prompt for all $\\beta$s. Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_{Other} \\beta_{Other}$"}
tscores <- regressions.llm %>%
  ggplot(aes(x=prompt.ordered_t, color=model, shape=model)) +

  geom_hline(aes(yintercept=t, color=model), linewidth=0.5, data=regressions.human) +
  geom_point(aes(y=t), size=1.25, alpha=0.7, position=position_dodge(width=0.5)) +

  facet_grid(V ~ Y, labeller=labeller(Y=Y.labeller, .default = label_parsed), scales="free_y") +
  
  xlab("Prompt Index") +
  ylab("t-scores") +

  scale_color_manual(name=NULL, values=my_colors, labels=model.labels) +
  guides(color = guide_legend(override.aes = list(shape = c(NA, 16, 17))), 
         shape = "none") +  # merge color and shape legends
  
  theme.point

tscores
```


\clearpage

```{r rhs_data_regressions.averaged, echo=FALSE}
regression.levels <- c("5k_V_Yllm", "train_V_Yhuman", "test_Vtilde_Ytilde")
regression.labels <- c("LLM", "Human Train", "Debiased")

model.levels <- c("gpt-3.5", "gpt-4o")
model.labels <- c("GPT3.5", "GPT4o")

Y.levels <- c("3", "14", "15", "19", "20", "Other")

regressions.averaged <- read.csv(file.path(repo_dir, "04_simulation/rhs/bayesian/simulations_averaged_rhs.csv")) %>%
   mutate(
     bias_norm = bias_mean/coef_sd, 
     Y = factor(sub("Y","", coef_name), levels=Y.levels), 
     V = factor(V, levels=V.levels),
     model = factor(model, levels=model.levels, labels=model.labels),
     regression = factor(regression, levels=regression.levels, labels=regression.labels)
     ) %>%
  rename(proportion=train_proportion) # %>%
  # filter(Y!="Other")



facet.labeller <- labeller(
  Y = function(Y) TeX(sprintf("$Y_{%s}$", Y)),
  proportion = function(proportion) paste("'", sprintf("Validation Proportion=%s%%", as.numeric(proportion)*100),"'"),
  .default = label_parsed
  )

n_bins <- 20
```

```{r rhs_fig_bias1, echo=FALSE, fig.height=10, fig.width=8, fig.cap="Bias Density Plots by Proportion of Validation Samples for all $\\beta$s. Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_{Other} \\beta_{Other}$"}

bias1 <- regressions.averaged %>%
  # filter(proportion!=0.25) %>%
  ggplot(aes(x=bias_mean, y=after_stat(max(group)*count/tapply(count, PANEL, FUN=sum)[PANEL]), 
             group=regression, fill=regression)) +
  geom_histogram(bins=n_bins, position=position_dodge()) +
  facet_grid(Y ~ proportion, labeller=facet.labeller, scales="free_x") +
  
  xlab("Bias") +
  ylab("Probability Densities") +
  
  scale_fill_manual(name=NULL, values=my_colors) +
  scale_x_symmetric(mid=0) + 
  scale_y_continuous(minor_breaks=seq(0,1, by=0.05), limits=c(0,1)) +
  theme.bar

bias1
```


```{r rhs_fig_bias1_norm, echo=FALSE, fig.height=10, fig.width=8, fig.cap="Normalized Bias Density Plots by Proportion of Validation Samples for all $\\beta$s. Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_{Other} \\beta_{Other}$"}

bias1_norm <- regressions.averaged %>%
  # filter(proportion!=0.25) %>%
  ggplot(aes(x=bias_norm, y=after_stat(max(group)*count/tapply(count, PANEL, FUN=sum)[PANEL]),
             group=regression, fill=regression)) +
  geom_histogram(binwidth=0.09, position=position_dodge()) +
  facet_grid(Y ~ proportion, labeller=facet.labeller, scales="free_x") +
  
  xlab("Normalized Bias") +
  ylab("Probability Densities") +
  
  scale_fill_manual(name=NULL, values=my_colors) +
  scale_x_symmetric(mid=0) +
  scale_y_continuous(minor_breaks=seq(0,1, by=0.05), limits=c(0,1)) +
  theme.bar

bias1_norm
```


\clearpage

```{r rhs_fig_bias2_3, echo=FALSE, fig.height=3*1.5, fig.width=8, fig.cap="Bias Density Plots by Model and Proportion of Validation Samples for $\\beta_{3}$. Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_{Other} \\beta_{Other}$"}
bias2 <- regressions.averaged %>%
  filter(
    # proportion!=0.25,
    Y=="3"
    ) %>%
  ggplot(aes(x=bias_mean, y=after_stat(max(group)*count/tapply(count, PANEL, FUN=sum)[PANEL]), 
             group=regression, fill=regression)) +
  geom_histogram(bins=n_bins, position=position_dodge()) +
  facet_grid(model ~ proportion, labeller=facet.labeller, scales="free_x") +
  
  xlab("Bias") +
  ylab("Probability Densities") +
  
  scale_fill_manual(name=NULL, values=my_colors) +
  scale_x_symmetric(mid=0) +
  scale_y_continuous(minor_breaks=seq(0,1, by=0.05), limits=c(0,1)) +
  theme.bar

bias2
```

```{r rhs_fig_bias2_14, echo=FALSE, fig.height=3*1.5, fig.width=8, fig.cap="Bias Density Plots by Model and Proportion of Validation Samples for $\\beta_{14}$. Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_{Other} \\beta_{Other}$"}

bias2 <- regressions.averaged %>%
  filter(
    # proportion!=0.25,
    Y=="14"
    ) %>%
  ggplot(aes(x=bias_mean, y=after_stat(max(group)*count/tapply(count, PANEL, FUN=sum)[PANEL]), 
             group=regression, fill=regression)) +
  geom_histogram(bins=n_bins, position=position_dodge()) +
  facet_grid(model ~ proportion, labeller=facet.labeller, scales="free_x") +
  
  xlab("Bias") +
  ylab("Probability Densities") +
  
  scale_fill_manual(name=NULL, values=my_colors) +
  scale_x_symmetric(mid=0) +
  scale_y_continuous(minor_breaks=seq(0,1, by=0.05), limits=c(0,1)) +
  theme.bar

bias2
```


```{r rhs_fig_bias2_15, echo=FALSE, fig.height=3*1.5, fig.width=8, fig.cap="Bias Density Plots by Model and Proportion of Validation Samples for $\\beta_{15}$. Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_{Other} \\beta_{Other}$"}

bias2 <- regressions.averaged %>%
  filter(
    # proportion!=0.25,
    Y=="15"
    ) %>%
  ggplot(aes(x=bias_mean, y=after_stat(max(group)*count/tapply(count, PANEL, FUN=sum)[PANEL]), 
             group=regression, fill=regression)) +
  geom_histogram(bins=n_bins, position=position_dodge()) +
  facet_grid(model ~ proportion, labeller=facet.labeller, scales="free_x") +
  
  xlab("Bias") +
  ylab("Probability Densities") +
  
  scale_fill_manual(name=NULL, values=my_colors) +
  scale_x_symmetric(mid=0) +
  scale_y_continuous(minor_breaks=seq(0,1, by=0.05), limits=c(0,1)) +
  theme.bar

bias2
```

```{r rhs_fig_bias2_19, echo=FALSE, fig.height=3*1.5, fig.width=8, fig.cap="Bias Density Plots by Model and Proportion of Validation Samples for $\\beta_{19}$. Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_{Other} \\beta_{Other}$"}

bias2 <- regressions.averaged %>%
  filter(
    # proportion!=0.25,
    Y=="19"
    ) %>%
  ggplot(aes(x=bias_mean, y=after_stat(max(group)*count/tapply(count, PANEL, FUN=sum)[PANEL]), 
             group=regression, fill=regression)) +
  geom_histogram(bins=n_bins, position=position_dodge()) +
  facet_grid(model ~ proportion, labeller=facet.labeller, scales="free_x") +
  
  xlab("Bias") +
  ylab("Probability Densities") +
  
  scale_fill_manual(name=NULL, values=my_colors) +
  scale_x_symmetric(mid=0) +
  scale_y_continuous(minor_breaks=seq(0,1, by=0.05), limits=c(0,1)) +
  theme.bar

bias2
```

```{r rhs_fig_bias2_20, echo=FALSE, fig.height=3*1.5, fig.width=8, fig.cap="Bias Density Plots by Model and Proportion of Validation Samples for $\\beta_{20}$. Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_{Other} \\beta_{Other}$"}

bias2 <- regressions.averaged %>%
  filter(
    # proportion!=0.25,
    Y=="20"
    ) %>%
  ggplot(aes(x=bias_mean, y=after_stat(max(group)*count/tapply(count, PANEL, FUN=sum)[PANEL]), 
             group=regression, fill=regression)) +
  geom_histogram(bins=n_bins, position=position_dodge()) +
  facet_grid(model ~ proportion, labeller=facet.labeller, scales="free_x") +
  
  xlab("Bias") +
  ylab("Probability Densities") +
  
  scale_fill_manual(name=NULL, values=my_colors) +
  scale_x_symmetric(mid=0) +
  scale_y_continuous(minor_breaks=seq(0,1, by=0.05), limits=c(0,1)) +
  theme.bar

bias2
```

```{r rhs_fig_bias2_Other, echo=FALSE, fig.height=3*1.5, fig.width=8, fig.cap="Bias Density Plots by Model and Proportion of Validation Samples for $\\beta_{Other}$. Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_{Other} \\beta_{Other}$"}

bias2 <- regressions.averaged %>%
  filter(
    # proportion!=0.25,
    Y=="Other"
    ) %>%
  ggplot(aes(x=bias_mean, y=after_stat(max(group)*count/tapply(count, PANEL, FUN=sum)[PANEL]), 
             group=regression, fill=regression)) +
  geom_histogram(bins=n_bins, position=position_dodge()) +
  facet_grid(model ~ proportion, labeller=facet.labeller, scales="free_x") +
  
  xlab("Bias") +
  ylab("Probability Densities") +
  
  scale_fill_manual(name=NULL, values=my_colors) +
  scale_x_symmetric(mid=0) +
  scale_y_continuous(minor_breaks=seq(0,1, by=0.05), limits=c(0,1)) +
  theme.bar

bias2
```

\clearpage 

```{r rhs_fig_bias2_norm_3, echo=FALSE, fig.height=3*1.5, fig.width=8, fig.cap="Normalized Bias Density Plots by Model and Proportion of Validation Samples for $\\beta_{3}$. Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_{Other} \\beta_{Other}$"}

bias2_norm <- regressions.averaged %>%
  filter(
    # proportion!=0.25,
    Y=="3"
    ) %>%
  ggplot(aes(x=bias_norm, y=after_stat(max(group)*count/tapply(count, PANEL, FUN=sum)[PANEL]),
             group=regression, fill=regression)) +
  geom_histogram(binwidth=0.09, position=position_dodge()) +
  facet_grid(model ~ proportion, labeller=facet.labeller, scales="free_x") +
  
  xlab("Normalized Bias") +
  ylab("Probability Densities") +
  
  scale_fill_manual(name=NULL, values=my_colors) +
  scale_x_symmetric(mid=0) +
  scale_y_continuous(minor_breaks=seq(0,1, by=0.05), limits=c(0,1)) +
  theme.bar

bias2_norm
```

```{r rhs_fig_bias2_norm_14, echo=FALSE, fig.height=3*1.5, fig.width=8, fig.cap="Normalized Bias Density Plots by Model and Proportion of Validation Samples for $\\beta_{14}$. Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_{Other} \\beta_{Other}$"}

bias2_norm <- regressions.averaged %>%
  filter(
    # proportion!=0.25,
    Y=="14"
    ) %>%
  ggplot(aes(x=bias_norm, y=after_stat(max(group)*count/tapply(count, PANEL, FUN=sum)[PANEL]),
             group=regression, fill=regression)) +
  geom_histogram(binwidth=0.09, position=position_dodge()) +
  facet_grid(model ~ proportion, labeller=facet.labeller, scales="free_x") +
  
  xlab("Normalized Bias") +
  ylab("Probability Densities") +
  
  scale_fill_manual(name=NULL, values=my_colors) +
  scale_x_symmetric(mid=0) +
  scale_y_continuous(minor_breaks=seq(0,1, by=0.05), limits=c(0,1)) +
  theme.bar

bias2_norm
```

```{r rhs_fig_bias2_norm_15, echo=FALSE, fig.height=3*1.5, fig.width=8, fig.cap="Normalized Bias Density Plots by Model and Proportion of Validation Samples for $\\beta_{15}$. Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_{Other} \\beta_{Other}$"}

bias2_norm <- regressions.averaged %>%
  filter(
    # proportion!=0.25,
    Y=="15"
    ) %>%
  ggplot(aes(x=bias_norm, y=after_stat(max(group)*count/tapply(count, PANEL, FUN=sum)[PANEL]),
             group=regression, fill=regression)) +
  geom_histogram(binwidth=0.09, position=position_dodge()) +
  facet_grid(model ~ proportion, labeller=facet.labeller, scales="free_x") +
  
  xlab("Normalized Bias") +
  ylab("Probability Densities") +
  
  scale_fill_manual(name=NULL, values=my_colors) +
  scale_x_symmetric(mid=0) +
  scale_y_continuous(minor_breaks=seq(0,1, by=0.05), limits=c(0,1)) +
  theme.bar

bias2_norm
```

```{r rhs_fig_bias2_norm_19, echo=FALSE, fig.height=3*1.5, fig.width=8, fig.cap="Normalized Bias Density Plots by Model and Proportion of Validation Samples for $\\beta_{19}$. Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_{Other} \\beta_{Other}$"}

bias2_norm <- regressions.averaged %>%
  filter(
    # proportion!=0.25,
    Y=="19"
    ) %>%
  ggplot(aes(x=bias_norm, y=after_stat(max(group)*count/tapply(count, PANEL, FUN=sum)[PANEL]),
             group=regression, fill=regression)) +
  geom_histogram(binwidth=0.09, position=position_dodge()) +
  facet_grid(model ~ proportion, labeller=facet.labeller, scales="free_x") +
  
  xlab("Normalized Bias") +
  ylab("Probability Densities") +
  
  scale_fill_manual(name=NULL, values=my_colors) +
  scale_x_symmetric(mid=0) +
  scale_y_continuous(minor_breaks=seq(0,1, by=0.05), limits=c(0,1)) +
  theme.bar

bias2_norm
```

```{r rhs_fig_bias2_norm_20, echo=FALSE, fig.height=3*1.5, fig.width=8, fig.cap="Normalized Bias Density Plots by Model and Proportion of Validation Samples for $\\beta_{20}$. Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_{Other} \\beta_{Other}$"}

bias2_norm <- regressions.averaged %>%
  filter(
    # proportion!=0.25,
    Y=="20"
    ) %>%
  ggplot(aes(x=bias_norm, y=after_stat(max(group)*count/tapply(count, PANEL, FUN=sum)[PANEL]),
             group=regression, fill=regression)) +
  geom_histogram(binwidth=0.09, position=position_dodge()) +
  facet_grid(model ~ proportion, labeller=facet.labeller, scales="free_x") +
  
  xlab("Normalized Bias") +
  ylab("Probability Densities") +
  
  scale_fill_manual(name=NULL, values=my_colors) +
  scale_x_symmetric(mid=0) +
  scale_y_continuous(minor_breaks=seq(0,1, by=0.05), limits=c(0,1)) +
  theme.bar

bias2_norm
```

```{r rhs_fig_bias2_norm_Other, echo=FALSE, fig.height=3*1.5, fig.width=8, fig.cap="Normalized Bias Density Plots by Model and Proportion of Validation Samples for $\\beta_{Other}$. Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_{Other} \\beta_{Other}$"}

bias2_norm <- regressions.averaged %>%
  filter(
    # proportion!=0.25,
    Y=="Other"
    ) %>%
  ggplot(aes(x=bias_norm, y=after_stat(max(group)*count/tapply(count, PANEL, FUN=sum)[PANEL]),
             group=regression, fill=regression)) +
  geom_histogram(binwidth=0.09, position=position_dodge()) +
  facet_grid(model ~ proportion, labeller=facet.labeller, scales="free_x") +
  
  xlab("Normalized Bias") +
  ylab("Probability Densities") +
  
  scale_fill_manual(name=NULL, values=my_colors) +
  scale_x_symmetric(mid=0) +
  scale_y_continuous(minor_breaks=seq(0,1, by=0.05), limits=c(0,1)) +
  theme.bar

bias2_norm
```


\clearpage

```{r rhs_fig_mse1, echo=FALSE, fig.height=11, fig.width=8, fig.cap="MSE Empirical CDF by Proportion of Validation Samples for all $\\beta$s. Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_{Other} \\beta_{Other}$"}

mse1 <- regressions.averaged %>%
  filter(
    # proportion != 0.25,
    regression != "LLM"
    ) %>%
  ggplot(aes(x=mse_mean, color=regression, linetype=regression)) +
  
  stat_ecdf(linewidth=0.5) +
  facet_grid(Y ~ proportion, labeller=facet.labeller, scales="free_x") +
  
  xlab("MSE") +
  ylab("Empirical CDF") +
  
  coord_cartesian(xlim=c(0,0.03)) +
  scale_color_manual(name="", values=my_colors) +
  scale_linetype_manual(name="", values=c("dashed", "solid")) +
  theme.mse

mse1
```

```{r rhs_fig_mse2_3, echo=FALSE, fig.height=4, fig.width=8, fig.cap="MSE Empirical CDF by Model and Proportion of Validation Samples for $\\beta_3$. Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_{Other} \\beta_{Other}$"}

mse2 <- regressions.averaged %>%
  filter(
    # proportion != 0.25,
    regression != "LLM",
    Y == "3"
    ) %>%
  ggplot(aes(x=mse_mean, color=regression, linetype=regression)) +
  
  stat_ecdf(linewidth=0.5) +
  facet_grid(model ~ proportion, labeller=facet.labeller, scales="free_x") +
  
  xlab("MSE") +
  ylab("Empirical CDF") +
  
  coord_cartesian(xlim=c(0,0.02)) +
  scale_color_manual(name="", values=my_colors) +
  scale_linetype_manual(name="", values=c("dashed", "solid")) +
  theme.mse

mse2
```

```{r rhs_fig_mse2_14, echo=FALSE, fig.height=4, fig.width=8, fig.cap="MSE Empirical CDF by Model and Proportion of Validation Samples for $\\beta_{14}$. Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_{Other} \\beta_{Other}$"}

mse2 <- regressions.averaged %>%
  filter(
    # proportion != 0.25,
    regression != "LLM",
    Y == "14"
    ) %>%
  ggplot(aes(x=mse_mean, color=regression, linetype=regression)) +
  
  stat_ecdf(linewidth=0.5) +
  facet_grid(model ~ proportion, labeller=facet.labeller, scales="free_x") +
  
  xlab("MSE") +
  ylab("Empirical CDF") +
  
  coord_cartesian(xlim=c(0,0.09)) +
  scale_color_manual(name="", values=my_colors) +
  scale_linetype_manual(name="", values=c("dashed", "solid")) +
  theme.mse

mse2
```


```{r rhs_fig_mse2_15, echo=FALSE, fig.height=4, fig.width=8, fig.cap="MSE Empirical CDF by Model and Proportion of Validation Samples for $\\beta_{15}$. Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_{Other} \\beta_{Other}$"}

mse2 <- regressions.averaged %>%
  filter(
    # proportion != 0.25,
    regression != "LLM",
    Y == "15"
    ) %>%
  ggplot(aes(x=mse_mean, color=regression, linetype=regression)) +
  
  stat_ecdf(linewidth=0.5) +
  facet_grid(model ~ proportion, labeller=facet.labeller, scales="free_x") +
  
  xlab("MSE") +
  ylab("Empirical CDF") +
  
  coord_cartesian(xlim=c(0,0.03)) +
  scale_color_manual(name="", values=my_colors) +
  scale_linetype_manual(name="", values=c("dashed", "solid")) +
  theme.mse

mse2
```


```{r rhs_fig_mse2_19, echo=FALSE, fig.height=4, fig.width=8, fig.cap="MSE Empirical CDF by Model and Proportion of Validation Samples for $\\beta_{19}$. Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_{Other} \\beta_{Other}$"}

mse2 <- regressions.averaged %>%
  filter(
    # proportion != 0.25,
    regression != "LLM",
    Y == "19"
    ) %>%
  ggplot(aes(x=mse_mean, color=regression, linetype=regression)) +
  
  stat_ecdf(linewidth=0.5) +
  facet_grid(model ~ proportion, labeller=facet.labeller, scales="free_x") +
  
  xlab("MSE") +
  ylab("Empirical CDF") +
  
  coord_cartesian(xlim=c(0,0.03)) +
  scale_color_manual(name="", values=my_colors) +
  scale_linetype_manual(name="", values=c("dashed", "solid")) +
  theme.mse

mse2
```


```{r rhs_fig_mse2_20, echo=FALSE, fig.height=4, fig.width=8, fig.cap="MSE Empirical CDF by Model and Proportion of Validation Samples for $\\beta_{20}$. Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_{Other} \\beta_{Other}$"}

mse2 <- regressions.averaged %>%
  filter(
    # proportion != 0.25,
    regression != "LLM",
    Y == "20"
    ) %>%
  ggplot(aes(x=mse_mean, color=regression, linetype=regression)) +
  
  stat_ecdf(linewidth=0.5) +
  facet_grid(model ~ proportion, labeller=facet.labeller, scales="free_x") +
  
  xlab("MSE") +
  ylab("Empirical CDF") +
  
  coord_cartesian(xlim=c(0,0.015)) +
  scale_color_manual(name="", values=my_colors) +
  scale_linetype_manual(name="", values=c("dashed", "solid")) +
  theme.mse

mse2
```


```{r rhs_fig_mse2_other, echo=FALSE, fig.height=4, fig.width=8, fig.cap="MSE Empirical CDF by Model and Proportion of Validation Samples for $\\beta_{Other}$. Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_{Other} \\beta_{Other}$"}

mse2 <- regressions.averaged %>%
  filter(
    # proportion != 0.25,
    regression != "LLM",
    Y == "Other"
    ) %>%
  ggplot(aes(x=mse_mean, color=regression, linetype=regression)) +
  
  stat_ecdf(linewidth=0.5) +
  facet_grid(model ~ proportion, labeller=facet.labeller, scales="free_x") +
  
  xlab("MSE") +
  ylab("Empirical CDF") +
  
  coord_cartesian(xlim=c(0,0.008)) +
  scale_color_manual(name="", values=my_colors) +
  scale_linetype_manual(name="", values=c("dashed", "solid")) +
  theme.mse

mse2
```

\clearpage

```{r rhs_tab_data}
regression.levels <- c("5k_V_Yllm", "train_V_Yhuman", "test_Vtilde_Ytilde")
regression.labels <- c("LLM", "Human Train", "Debiased")

model.levels <- c("gpt-3.5", "gpt-4o")
model.labels <- c("GPT-3.5", "GPT-4o")

proportion.levels <- c(0.05, 0.10, 0.25, 0.50)
proportion.labels <- sprintf("%s\\%%", proportion.levels*100)

Y.levels <- c("3", "14", "15", "19", "20", "Other")
Y.labels <- sprintf("$Y_{%s}$", Y.levels)

regressions.averaged <- read.csv(file.path(repo_dir, "04_simulation/rhs/bayesian/simulations_averaged_rhs.csv")) %>%
  rename(proportion=train_proportion) %>%
   mutate(
     bias_norm = bias_mean/coef_sd, 
     Y = sub("Y","", coef_name),
     # Y = factor(sub("Y","", coef_name), levels=Y.levels, labels=Y.labels), 
     V = factor(V, levels=V.levels),
     model = factor(model, levels=model.levels, labels=model.labels),
     regression = factor(regression, levels=regression.levels, labels=regression.labels),
     proportion = factor(proportion, levels=proportion.levels, labels=proportion.labels),
     ) # %>%
  # filter(Y!="Other")

```

```{r rhs_tab_bias1, echo=FALSE, results='asis'}
bias1 <- regressions.averaged %>%
  mutate(statistic=bias_mean) %>%
  group_by(Y, proportion, regression) %>%
  summarise(
    "Mean" = mean(statistic),
    "SD" = sd(statistic),
    "Median" = median(statistic),
    "5\\%" = quantile(statistic, probs[1]),
    "95\\%" = quantile(statistic, probs[2]),
    .groups = "drop"
    ) %>%
  rename(c(
    "Validation Proportion" = proportion, 
    "Bias" = regression)
    )

bias1 %>% 
  filter(Y=="3") %>% select(!Y) %>%
  kbl(., align="rlrrrrr",
      caption="Bias Summary Statistics by Proportion of Validation Samples for $\\beta_{3}$.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_{Other} \\beta_{Other}$",
      digits=3, booktabs=T, linesep = "", escape=F) %>%
    kable_styling(latex_options = "striped", stripe_index = stripe(3))

bias1 %>% 
  filter(Y=="14") %>% select(!Y) %>%
  kbl(., align="rlrrrrr",
      caption="Bias Summary Statistics by Proportion of Validation Samples for $\\beta_{14}$.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_{Other} \\beta_{Other}$",
      digits=3, booktabs=T, linesep = "", escape=F) %>%
    kable_styling(latex_options = "striped", stripe_index = stripe(3))

bias1 %>% 
  filter(Y=="15") %>% select(!Y) %>%
  kbl(., align="rlrrrrr",
      caption="Bias Summary Statistics by Proportion of Validation Samples for $\\beta_{15}$.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_{Other} \\beta_{Other}$",
      digits=3, booktabs=T, linesep = "", escape=F) %>%
    kable_styling(latex_options = "striped", stripe_index = stripe(3))

bias1 %>% 
  filter(Y=="19") %>% select(!Y) %>%
  kbl(., align="rlrrrrr",
      caption="Bias Summary Statistics by Proportion of Validation Samples for $\\beta_{19}$.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_{Other} \\beta_{Other}$",
      digits=3, booktabs=T, linesep = "", escape=F) %>%
    kable_styling(latex_options = "striped", stripe_index = stripe(3))

bias1 %>% 
  filter(Y=="20") %>% select(!Y) %>%
  kbl(., align="rlrrrrr",
      caption="Bias Summary Statistics by Proportion of Validation Samples for $\\beta_{20}$.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_{Other} \\beta_{Other}$",
      digits=3, booktabs=T, linesep = "", escape=F) %>%
    kable_styling(latex_options = "striped", stripe_index = stripe(3))


bias1 %>% 
  filter(Y=="Other") %>% select(!Y) %>%
  kbl(., align="rlrrrrr",
      caption="Bias Summary Statistics by Proportion of Validation Samples for $\\beta_{Other}$.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_{Other} \\beta_{Other}$",
      digits=3, booktabs=T, linesep = "", escape=F) %>%
    kable_styling(latex_options = "striped", stripe_index = stripe(3))
```

```{r rhs_tab_bias1_norm, echo=FALSE, results='asis'}
bias1_norm <- regressions.averaged %>%
  mutate(statistic=bias_norm) %>%
  group_by(Y, proportion, regression) %>%
  summarise(
    "Mean" = mean(statistic),
    "SD" = sd(statistic),
    "Median" = median(statistic),
    "5\\%" = quantile(statistic, probs[1]),
    "95\\%" = quantile(statistic, probs[2]),
    .groups = "drop"
    ) %>%
  rename(c(
    "Validation Proportion" = proportion, 
    "Normalized Bias" = regression)
    )

bias1_norm %>% 
  filter(Y=="3") %>% select(!Y) %>%
  kbl(., align="rlrrrrr",
    caption="Normalized Bias Summary Statistics by Proportion of Validation Samples for $\\beta_{3}$.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_{Other} \\beta_{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))

bias1_norm %>% 
  filter(Y=="14") %>% select(!Y) %>%
  kbl(., align="rlrrrrr",
    caption="Normalized Bias Summary Statistics by Proportion of Validation Samples for $\\beta_{14}$.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_{Other} \\beta_{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))

bias1_norm %>% 
  filter(Y=="15") %>% select(!Y) %>%
  kbl(., align="rlrrrrr",
    caption="Normalized Bias Summary Statistics by Proportion of Validation Samples for $\\beta_{15}$.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_{Other} \\beta_{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))

bias1_norm %>% 
  filter(Y=="19") %>% select(!Y) %>%
  kbl(., align="rlrrrrr",
    caption="Normalized Bias Summary Statistics by Proportion of Validation Samples for $\\beta_{19}$.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_{Other} \\beta_{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))

bias1_norm %>% 
  filter(Y=="20") %>% select(!Y) %>%
  kbl(., align="rlrrrrr",
    caption="Normalized Bias Summary Statistics by Proportion of Validation Samples for $\\beta_{20}$.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_{Other} \\beta_{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))

bias1_norm %>% 
  filter(Y=="Other") %>% select(!Y) %>%
  kbl(., align="rlrrrrr",
    caption="Normalized Bias Summary Statistics by Proportion of Validation Samples for $\\beta_{Other}$.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_{Other} \\beta_{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))
```


```{r rhs_tab_bias2, echo=FALSE, results='asis'}
bias2 <- regressions.averaged %>%
  mutate(statistic=bias_mean) %>%
  group_by(Y, model, proportion, regression) %>%
  summarise(
    "Mean" = mean(statistic),
    "SD" = sd(statistic),
    "Median" = median(statistic),
    "5\\%" = quantile(statistic, probs[1]),
    "95\\%" = quantile(statistic, probs[2]),
    .groups = "drop"
    ) %>%
  rename(c(
    "Model" = model, 
    "Validation Proportion" = proportion, 
    "Bias" = regression
    ))

bias2 %>% 
  filter(Y=="3") %>% select(!Y) %>%
  kbl(., align="lrlrrrrr",
    caption="Bias Summary Statistics by Model and Proportion of Validation Samples for $\\beta_{3}$.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_{Other} \\beta_{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))

bias2 %>% 
  filter(Y=="14") %>% select(!Y) %>%
  kbl(., align="lrlrrrrr",
    caption="Bias Summary Statistics by Model and Proportion of Validation Samples for $\\beta_{14}$.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_{Other} \\beta_{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))

bias2 %>% 
  filter(Y=="15") %>% select(!Y) %>%
  kbl(., align="lrlrrrrr",
    caption="Bias Summary Statistics by Model and Proportion of Validation Samples for $\\beta_{15}$.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_{Other} \\beta_{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))

bias2 %>% 
  filter(Y=="19") %>% select(!Y) %>%
  kbl(., align="lrlrrrrr",
    caption="Bias Summary Statistics by Model and Proportion of Validation Samples for $\\beta_{19}$.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_{Other} \\beta_{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))

bias2 %>% 
  filter(Y=="20") %>% select(!Y) %>%
  kbl(., align="lrlrrrrr",
    caption="Bias Summary Statistics by Model and Proportion of Validation Samples for $\\beta_{20}$.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_{Other} \\beta_{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))

bias2 %>% 
  filter(Y=="Other") %>% select(!Y) %>%
  kbl(., align="lrlrrrrr",
    caption="Bias Summary Statistics by Model and Proportion of Validation Samples for $\\beta_{Other}$.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_{Other} \\beta_{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))
```


```{r rhs_tab_bias2_norm, echo=FALSE, results='asis'}
bias2_norm <- regressions.averaged %>%
  mutate(statistic=bias_norm) %>%
  group_by(Y, model, proportion, regression) %>%
  summarise(
    "Mean" = mean(statistic),
    "SD" = sd(statistic),
    "Median" = median(statistic),
    "5\\%" = quantile(statistic, probs[1]),
    "95\\%" = quantile(statistic, probs[2]),
    .groups = "drop"
    ) %>%
  rename(c(
    "Model" = model, 
    "Validation Proportion" = proportion, 
    "Normalized Bias" = regression
    ))

bias2_norm %>% 
  filter(Y=="3") %>% select(!Y) %>%
  kbl(., align="lrlrrrrr",
    caption="Normalized Bias Summary Statistics by Model and Proportion of Validation Samples for $\\beta_{3}$.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_{Other} \\beta_{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))

bias2_norm %>% 
  filter(Y=="14") %>% select(!Y) %>%
  kbl(., align="lrlrrrrr",
    caption="Normalized Bias Summary Statistics by Model and Proportion of Validation Samples for $\\beta_{14}$.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_{Other} \\beta_{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))

bias2_norm %>% 
  filter(Y=="15") %>% select(!Y) %>%
  kbl(., align="lrlrrrrr",
    caption="Normalized Bias Summary Statistics by Model and Proportion of Validation Samples for $\\beta_{15}$.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_{Other} \\beta_{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))

bias2_norm %>% 
  filter(Y=="19") %>% select(!Y) %>%
  kbl(., align="lrlrrrrr",
    caption="Normalized Bias Summary Statistics by Model and Proportion of Validation Samples for $\\beta_{19}$.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_{Other} \\beta_{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))

bias2_norm %>% 
  filter(Y=="20") %>% select(!Y) %>%
  kbl(., align="lrlrrrrr",
    caption="Normalized Bias Summary Statistics by Model and Proportion of Validation Samples for $\\beta_{20}$.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_{Other} \\beta_{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))

bias2_norm %>% 
  filter(Y=="Other") %>% select(!Y) %>%
  kbl(., align="lrlrrrrr",
    caption="Normalized Bias Summary Statistics by Model and Proportion of Validation Samples for $\\beta_{Other}$.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_{Other} \\beta_{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))
```

```{r rhs_tab_mse1, echo=FALSE, results='asis'}
mse1 <- regressions.averaged %>%
  mutate(statistic=mse_mean) %>%
  group_by(Y, proportion, regression) %>%
  summarise(
    "Mean" = mean(statistic),
    "SD" = sd(statistic),
    "Median" = median(statistic),
    "5\\%" = quantile(statistic, probs[1]),
    "95\\%" = quantile(statistic, probs[2]),
    .groups = "drop") %>%
  rename(c(
    "Validation Proportion" = proportion,
    "MSE" = regression)
    )

mse1 %>% 
  filter(Y=="3") %>% select(!Y) %>%
  kbl(., align="rlrrrrr",
    caption="MSE Summary Statistics by Proportion of Validation Samples for $\\beta_{3}$.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_{Other} \\beta_{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))


mse1 %>% 
  filter(Y=="14") %>% select(!Y) %>%
  kbl(., align="rlrrrrr",
    caption="MSE Summary Statistics by Proportion of Validation Samples for $\\beta_{14}$.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_{Other} \\beta_{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))


mse1 %>% 
  filter(Y=="15") %>% select(!Y) %>%
  kbl(., align="rlrrrrr",
    caption="MSE Summary Statistics by Proportion of Validation Samples for $\\beta_{15}$.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_{Other} \\beta_{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))

mse1 %>% 
  filter(Y=="19") %>% select(!Y) %>%
  kbl(., align="rlrrrrr",
    caption="MSE Summary Statistics by Proportion of Validation Samples for $\\beta_{19}$.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_{Other} \\beta_{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))

mse1 %>% 
  filter(Y=="20") %>% select(!Y) %>%
  kbl(., align="rlrrrrr",
    caption="MSE Summary Statistics by Proportion of Validation Samples for $\\beta_{20}$.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_{Other} \\beta_{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))

mse1 %>% 
  filter(Y=="Other") %>% select(!Y) %>%
  kbl(., align="rlrrrrr",
    caption="MSE Summary Statistics by Proportion of Validation Samples for $\\beta_{Other}$.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_{Other} \\beta_{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))
```


```{r rhs_tab_mse2, echo=FALSE, results='asis'}
mse2 <- regressions.averaged %>%
  mutate(statistic=mse_mean) %>%
  group_by(Y, model, proportion, regression) %>%
  summarise(
    "Mean" = mean(statistic),
    "SD" = sd(statistic),
    "Median" = median(statistic),
    "5\\%" = quantile(statistic, probs[1]),
    "95\\%" = quantile(statistic, probs[2]),
    .groups = "drop") %>%
  rename(c(
    "Model" = model,
    "Validation Proportion" = proportion,
    "MSE" = regression
    ))

mse2 %>% 
  filter(Y=="3") %>% select(!Y) %>%
  kbl(., align="lrlrrrrr",
    caption="MSE Summary Statistics by Model and Proportion of Validation Samples for $\\beta_{3}$.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_{Other} \\beta_{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))

mse2 %>% 
  filter(Y=="14") %>% select(!Y) %>%
  kbl(., align="lrlrrrrr",
    caption="MSE Summary Statistics by Model and Proportion of Validation Samples for $\\beta_{14}$.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_{Other} \\beta_{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))

mse2 %>% 
  filter(Y=="15") %>% select(!Y) %>%
  kbl(., align="lrlrrrrr",
    caption="MSE Summary Statistics by Model and Proportion of Validation Samples for $\\beta_{15}$.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_{Other} \\beta_{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))

mse2 %>% 
  filter(Y=="19") %>% select(!Y) %>%
  kbl(., align="lrlrrrrr",
    caption="MSE Summary Statistics by Model and Proportion of Validation Samples for $\\beta_{19}$.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_{Other} \\beta_{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))

mse2 %>% 
  filter(Y=="20") %>% select(!Y) %>%
  kbl(., align="lrlrrrrr",
    caption="MSE Summary Statistics by Model and Proportion of Validation Samples for $\\beta_{20}$.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_{Other} \\beta_{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))

mse2 %>% 
  filter(Y=="Other") %>% select(!Y) %>%
  kbl(., align="lrlrrrrr",
    caption="MSE Summary Statistics by Model and Proportion of Validation Samples for $\\beta_{Other}$.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_{Other} \\beta_{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))
```


```{r rhs_tab_coverage1, echo=FALSE, results='asis'}
coverage1 <- regressions.averaged %>%
  mutate(statistic=coverage_mean) %>%
  group_by(Y, proportion, regression) %>%
  summarise(
    "Mean" = mean(statistic),
    "SD" = sd(statistic),
    "Median" = median(statistic),
    "5\\%" = quantile(statistic, probs[1]),
    "95\\%" = quantile(statistic, probs[2]),
    .groups = "drop") %>%
  rename(c(
    "Validation Proportion" = proportion,
    "Coverage" = regression)
    )

coverage1 %>% 
  filter(Y=="3") %>% select(!Y) %>%
  kbl(., align="rllrrrrr",
    caption="Coverage Summary Statistics by Proportion of Validation Samples for $\\beta_{3}$.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_{Other} \\beta_{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))

coverage1 %>% 
  filter(Y=="14") %>% select(!Y) %>%
  kbl(., align="rllrrrrr",
    caption="Coverage Summary Statistics by Proportion of Validation Samples for $\\beta_{14}$.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_{Other} \\beta_{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))

coverage1 %>% 
  filter(Y=="15") %>% select(!Y) %>%
  kbl(., align="rllrrrrr",
    caption="Coverage Summary Statistics by Proportion of Validation Samples for $\\beta_{15}$.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_{Other} \\beta_{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))

coverage1 %>% 
  filter(Y=="19") %>% select(!Y) %>%
  kbl(., align="rllrrrrr",
    caption="Coverage Summary Statistics by Proportion of Validation Samples for $\\beta_{19}$.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_{Other} \\beta_{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))

coverage1 %>% 
  filter(Y=="20") %>% select(!Y) %>%
  kbl(., align="rllrrrrr",
    caption="Coverage Summary Statistics by Proportion of Validation Samples for $\\beta_{20}$.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_{Other} \\beta_{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))

coverage1 %>% 
  filter(Y=="Other") %>% select(!Y) %>%
  kbl(., align="rllrrrrr",
    caption="Coverage Summary Statistics by Proportion of Validation Samples for $\\beta_{Other}$.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_{Other} \\beta_{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))
```


```{r rhs_tab_coverage2, echo=FALSE, results='asis'}
coverage2 <- regressions.averaged %>%
  mutate(statistic=coverage_mean) %>%
  group_by(Y, model, proportion, regression) %>%
  summarise(
    "Mean" = mean(statistic),
    "SD" = sd(statistic),
    "Median" = median(statistic),
    "5\\%" = quantile(statistic, probs[1]),
    "95\\%" = quantile(statistic, probs[2]),
    .groups = "drop") %>%
  rename(c(
    "Model" = model,
    "Validation Proportion" = proportion,
    "MSE" = regression
    ))

coverage2 %>% 
  filter(Y=="3") %>% select(!Y) %>%
  kbl(., align="lrlrrrrr",
    caption="Coverage Summary Statistics by Model and Proportion of Validation Samples for $\\beta_{3}$.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_{Other} \\beta_{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))

coverage2 %>% 
  filter(Y=="14") %>% select(!Y) %>%
  kbl(., align="lrlrrrrr",
    caption="Coverage Summary Statistics by Model and Proportion of Validation Samples for $\\beta_{14}$.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_{Other} \\beta_{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))

coverage2 %>% 
  filter(Y=="15") %>% select(!Y) %>%
  kbl(., align="lrlrrrrr",
    caption="Coverage Summary Statistics by Model and Proportion of Validation Samples for $\\beta_{15}$.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_{Other} \\beta_{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))

coverage2 %>% 
  filter(Y=="19") %>% select(!Y) %>%
  kbl(., align="lrlrrrrr",
    caption="Coverage Summary Statistics by Model and Proportion of Validation Samples for $\\beta_{19}$.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_{Other} \\beta_{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))

coverage2 %>% 
  filter(Y=="20") %>% select(!Y) %>%
  kbl(., align="lrlrrrrr",
    caption="Coverage Summary Statistics by Model and Proportion of Validation Samples for $\\beta_{20}$.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_{Other} \\beta_{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))

coverage2 %>% 
  filter(Y=="Other") %>% select(!Y) %>%
  kbl(., align="lrlrrrrr",
    caption="Coverage Summary Statistics by Model and Proportion of Validation Samples for $\\beta_{Other}$.
      Proxy on the RHS: $V = Y^\\top \\beta = Y_3 \\beta_3 + Y_{14} \\beta_{14} + Y_{15} \\beta_{15} + Y_{19}  \\beta_{19}+ Y_{20} \\beta_{20} + Y_{Other} \\beta_{Other}$",
    digits=3, booktabs=T, linesep = "", escape=F) %>%
  kable_styling(latex_options = "striped", stripe_index = stripe(3))
```

